/* Warm Up: content for STORY DICE. Generated with a permanent id on every item.
   pictures[level]: the pictures that can appear on the dice. { id, pic, text } (text empty = the picture's own word).
   Add, remove or change them in Edit mode to choose which pictures can appear.
   id is PERMANENT: teacher edits (Edit mode) point at it. Never change or reuse an id. */
window.WU = window.WU || {}; WU.content = WU.content || {};
WU.content.dice = [
  /* ---------- 0. Beginner (A1) ---------- */
  { pictures: [
      { id: "a1-d-cat", pic: "cat" },
      { id: "a1-d-dog", pic: "dog" },
      { id: "a1-d-fish", pic: "fish" },
      { id: "a1-d-bird", pic: "bird" },
      { id: "a1-d-cow", pic: "cow" },
      { id: "a1-d-pig", pic: "pig" },
      { id: "a1-d-horse", pic: "horse" },
      { id: "a1-d-rabbit", pic: "rabbit" },
      { id: "a1-d-lion", pic: "lion" },
      { id: "a1-d-elephant", pic: "elephant" },
      { id: "a1-d-monkey", pic: "monkey" },
      { id: "a1-d-frog", pic: "frog" },
      { id: "a1-d-bear", pic: "bear" },
      { id: "a1-d-apple", pic: "apple" },
      { id: "a1-d-banana", pic: "banana" },
      { id: "a1-d-pizza", pic: "pizza" },
      { id: "a1-d-cake", pic: "cake" },
      { id: "a1-d-ice-cream", pic: "ice cream" },
      { id: "a1-d-sandwich", pic: "sandwich" },
      { id: "a1-d-car", pic: "car" },
      { id: "a1-d-bus", pic: "bus" },
      { id: "a1-d-bike", pic: "bike" },
      { id: "a1-d-plane", pic: "plane" },
      { id: "a1-d-boat", pic: "boat" },
      { id: "a1-d-train", pic: "train" },
      { id: "a1-d-house", pic: "house" },
      { id: "a1-d-tree", pic: "tree" },
      { id: "a1-d-flower", pic: "flower" },
      { id: "a1-d-sun", pic: "sun" },
      { id: "a1-d-rain", pic: "rain" },
      { id: "a1-d-snow", pic: "snow" },
      { id: "a1-d-moon", pic: "moon" },
      { id: "a1-d-star", pic: "star" },
      { id: "a1-d-ball", pic: "ball" },
      { id: "a1-d-teddy-bear", pic: "teddy bear" },
      { id: "a1-d-robot", pic: "robot" },
      { id: "a1-d-guitar", pic: "guitar" },
      { id: "a1-d-book", pic: "book" },
      { id: "a1-d-phone", pic: "phone" },
      { id: "a1-d-hat", pic: "hat" },
      { id: "a1-d-umbrella", pic: "umbrella" }
    ] },
  /* ---------- 1. Elementary (A2) ---------- */
  { pictures: [
      { id: "a2-d-cat", pic: "cat" },
      { id: "a2-d-dog", pic: "dog" },
      { id: "a2-d-fish", pic: "fish" },
      { id: "a2-d-bird", pic: "bird" },
      { id: "a2-d-cow", pic: "cow" },
      { id: "a2-d-pig", pic: "pig" },
      { id: "a2-d-horse", pic: "horse" },
      { id: "a2-d-rabbit", pic: "rabbit" },
      { id: "a2-d-lion", pic: "lion" },
      { id: "a2-d-elephant", pic: "elephant" },
      { id: "a2-d-monkey", pic: "monkey" },
      { id: "a2-d-frog", pic: "frog" },
      { id: "a2-d-bear", pic: "bear" },
      { id: "a2-d-apple", pic: "apple" },
      { id: "a2-d-banana", pic: "banana" },
      { id: "a2-d-pizza", pic: "pizza" },
      { id: "a2-d-cake", pic: "cake" },
      { id: "a2-d-ice-cream", pic: "ice cream" },
      { id: "a2-d-sandwich", pic: "sandwich" },
      { id: "a2-d-car", pic: "car" },
      { id: "a2-d-bus", pic: "bus" },
      { id: "a2-d-bike", pic: "bike" },
      { id: "a2-d-plane", pic: "plane" },
      { id: "a2-d-boat", pic: "boat" },
      { id: "a2-d-train", pic: "train" },
      { id: "a2-d-house", pic: "house" },
      { id: "a2-d-tree", pic: "tree" },
      { id: "a2-d-flower", pic: "flower" },
      { id: "a2-d-sun", pic: "sun" },
      { id: "a2-d-rain", pic: "rain" },
      { id: "a2-d-snow", pic: "snow" },
      { id: "a2-d-moon", pic: "moon" },
      { id: "a2-d-star", pic: "star" },
      { id: "a2-d-ball", pic: "ball" },
      { id: "a2-d-teddy-bear", pic: "teddy bear" },
      { id: "a2-d-robot", pic: "robot" },
      { id: "a2-d-guitar", pic: "guitar" },
      { id: "a2-d-book", pic: "book" },
      { id: "a2-d-phone", pic: "phone" },
      { id: "a2-d-hat", pic: "hat" },
      { id: "a2-d-umbrella", pic: "umbrella" },
      { id: "a2-d-king", pic: "king" },
      { id: "a2-d-queen", pic: "queen" },
      { id: "a2-d-teacher", pic: "teacher" },
      { id: "a2-d-doctor", pic: "doctor" },
      { id: "a2-d-chef", pic: "chef" },
      { id: "a2-d-pilot", pic: "pilot" },
      { id: "a2-d-police-officer", pic: "police officer" },
      { id: "a2-d-firefighter", pic: "firefighter" },
      { id: "a2-d-farmer", pic: "farmer" },
      { id: "a2-d-singer", pic: "singer" },
      { id: "a2-d-baby", pic: "baby" },
      { id: "a2-d-rocket", pic: "rocket" },
      { id: "a2-d-helicopter", pic: "helicopter" },
      { id: "a2-d-island", pic: "island" },
      { id: "a2-d-mountain", pic: "mountain" },
      { id: "a2-d-beach", pic: "beach" },
      { id: "a2-d-hospital", pic: "hospital" },
      { id: "a2-d-school", pic: "school" },
      { id: "a2-d-shop", pic: "shop" },
      { id: "a2-d-farm", pic: "farm" },
      { id: "a2-d-key", pic: "key" },
      { id: "a2-d-box", pic: "box" },
      { id: "a2-d-present", pic: "present" },
      { id: "a2-d-camera", pic: "camera" },
      { id: "a2-d-kite", pic: "kite" },
      { id: "a2-d-balloon", pic: "balloon" },
      { id: "a2-d-clock", pic: "clock" },
      { id: "a2-d-candle", pic: "candle" },
      { id: "a2-d-computer", pic: "computer" },
      { id: "a2-d-storm", pic: "storm" },
      { id: "a2-d-rainbow", pic: "rainbow" },
      { id: "a2-d-fire", pic: "fire" },
      { id: "a2-d-snowman", pic: "snowman" },
      { id: "a2-d-whale", pic: "whale" },
      { id: "a2-d-octopus", pic: "octopus" },
      { id: "a2-d-snake", pic: "snake" },
      { id: "a2-d-owl", pic: "owl" },
      { id: "a2-d-bee", pic: "bee" },
      { id: "a2-d-glasses", pic: "glasses" },
      { id: "a2-d-bag", pic: "bag" }
    ] },
  /* ---------- 2. Pre-Intermediate (A2+) ---------- */
  { pictures: [
      { id: "a2p-d-cat", pic: "cat" },
      { id: "a2p-d-dog", pic: "dog" },
      { id: "a2p-d-fish", pic: "fish" },
      { id: "a2p-d-bird", pic: "bird" },
      { id: "a2p-d-cow", pic: "cow" },
      { id: "a2p-d-pig", pic: "pig" },
      { id: "a2p-d-horse", pic: "horse" },
      { id: "a2p-d-rabbit", pic: "rabbit" },
      { id: "a2p-d-lion", pic: "lion" },
      { id: "a2p-d-elephant", pic: "elephant" },
      { id: "a2p-d-monkey", pic: "monkey" },
      { id: "a2p-d-frog", pic: "frog" },
      { id: "a2p-d-bear", pic: "bear" },
      { id: "a2p-d-apple", pic: "apple" },
      { id: "a2p-d-banana", pic: "banana" },
      { id: "a2p-d-pizza", pic: "pizza" },
      { id: "a2p-d-cake", pic: "cake" },
      { id: "a2p-d-ice-cream", pic: "ice cream" },
      { id: "a2p-d-sandwich", pic: "sandwich" },
      { id: "a2p-d-car", pic: "car" },
      { id: "a2p-d-bus", pic: "bus" },
      { id: "a2p-d-bike", pic: "bike" },
      { id: "a2p-d-plane", pic: "plane" },
      { id: "a2p-d-boat", pic: "boat" },
      { id: "a2p-d-train", pic: "train" },
      { id: "a2p-d-house", pic: "house" },
      { id: "a2p-d-tree", pic: "tree" },
      { id: "a2p-d-flower", pic: "flower" },
      { id: "a2p-d-sun", pic: "sun" },
      { id: "a2p-d-rain", pic: "rain" },
      { id: "a2p-d-snow", pic: "snow" },
      { id: "a2p-d-moon", pic: "moon" },
      { id: "a2p-d-star", pic: "star" },
      { id: "a2p-d-ball", pic: "ball" },
      { id: "a2p-d-teddy-bear", pic: "teddy bear" },
      { id: "a2p-d-robot", pic: "robot" },
      { id: "a2p-d-guitar", pic: "guitar" },
      { id: "a2p-d-book", pic: "book" },
      { id: "a2p-d-phone", pic: "phone" },
      { id: "a2p-d-hat", pic: "hat" },
      { id: "a2p-d-umbrella", pic: "umbrella" },
      { id: "a2p-d-king", pic: "king" },
      { id: "a2p-d-queen", pic: "queen" },
      { id: "a2p-d-teacher", pic: "teacher" },
      { id: "a2p-d-doctor", pic: "doctor" },
      { id: "a2p-d-chef", pic: "chef" },
      { id: "a2p-d-pilot", pic: "pilot" },
      { id: "a2p-d-police-officer", pic: "police officer" },
      { id: "a2p-d-firefighter", pic: "firefighter" },
      { id: "a2p-d-farmer", pic: "farmer" },
      { id: "a2p-d-singer", pic: "singer" },
      { id: "a2p-d-baby", pic: "baby" },
      { id: "a2p-d-rocket", pic: "rocket" },
      { id: "a2p-d-helicopter", pic: "helicopter" },
      { id: "a2p-d-island", pic: "island" },
      { id: "a2p-d-mountain", pic: "mountain" },
      { id: "a2p-d-beach", pic: "beach" },
      { id: "a2p-d-hospital", pic: "hospital" },
      { id: "a2p-d-school", pic: "school" },
      { id: "a2p-d-shop", pic: "shop" },
      { id: "a2p-d-farm", pic: "farm" },
      { id: "a2p-d-key", pic: "key" },
      { id: "a2p-d-box", pic: "box" },
      { id: "a2p-d-present", pic: "present" },
      { id: "a2p-d-camera", pic: "camera" },
      { id: "a2p-d-kite", pic: "kite" },
      { id: "a2p-d-balloon", pic: "balloon" },
      { id: "a2p-d-clock", pic: "clock" },
      { id: "a2p-d-candle", pic: "candle" },
      { id: "a2p-d-computer", pic: "computer" },
      { id: "a2p-d-storm", pic: "storm" },
      { id: "a2p-d-rainbow", pic: "rainbow" },
      { id: "a2p-d-fire", pic: "fire" },
      { id: "a2p-d-snowman", pic: "snowman" },
      { id: "a2p-d-whale", pic: "whale" },
      { id: "a2p-d-octopus", pic: "octopus" },
      { id: "a2p-d-snake", pic: "snake" },
      { id: "a2p-d-owl", pic: "owl" },
      { id: "a2p-d-bee", pic: "bee" },
      { id: "a2p-d-glasses", pic: "glasses" },
      { id: "a2p-d-bag", pic: "bag" }
    ] },
  /* ---------- 3. Intermediate (B1) ---------- */
  { pictures: [
      { id: "b1-d-cat", pic: "cat" },
      { id: "b1-d-dog", pic: "dog" },
      { id: "b1-d-fish", pic: "fish" },
      { id: "b1-d-bird", pic: "bird" },
      { id: "b1-d-cow", pic: "cow" },
      { id: "b1-d-pig", pic: "pig" },
      { id: "b1-d-horse", pic: "horse" },
      { id: "b1-d-rabbit", pic: "rabbit" },
      { id: "b1-d-lion", pic: "lion" },
      { id: "b1-d-elephant", pic: "elephant" },
      { id: "b1-d-monkey", pic: "monkey" },
      { id: "b1-d-frog", pic: "frog" },
      { id: "b1-d-bear", pic: "bear" },
      { id: "b1-d-apple", pic: "apple" },
      { id: "b1-d-banana", pic: "banana" },
      { id: "b1-d-pizza", pic: "pizza" },
      { id: "b1-d-cake", pic: "cake" },
      { id: "b1-d-ice-cream", pic: "ice cream" },
      { id: "b1-d-sandwich", pic: "sandwich" },
      { id: "b1-d-car", pic: "car" },
      { id: "b1-d-bus", pic: "bus" },
      { id: "b1-d-bike", pic: "bike" },
      { id: "b1-d-plane", pic: "plane" },
      { id: "b1-d-boat", pic: "boat" },
      { id: "b1-d-train", pic: "train" },
      { id: "b1-d-house", pic: "house" },
      { id: "b1-d-tree", pic: "tree" },
      { id: "b1-d-flower", pic: "flower" },
      { id: "b1-d-sun", pic: "sun" },
      { id: "b1-d-rain", pic: "rain" },
      { id: "b1-d-snow", pic: "snow" },
      { id: "b1-d-moon", pic: "moon" },
      { id: "b1-d-star", pic: "star" },
      { id: "b1-d-ball", pic: "ball" },
      { id: "b1-d-teddy-bear", pic: "teddy bear" },
      { id: "b1-d-robot", pic: "robot" },
      { id: "b1-d-guitar", pic: "guitar" },
      { id: "b1-d-book", pic: "book" },
      { id: "b1-d-phone", pic: "phone" },
      { id: "b1-d-hat", pic: "hat" },
      { id: "b1-d-umbrella", pic: "umbrella" },
      { id: "b1-d-king", pic: "king" },
      { id: "b1-d-queen", pic: "queen" },
      { id: "b1-d-teacher", pic: "teacher" },
      { id: "b1-d-doctor", pic: "doctor" },
      { id: "b1-d-chef", pic: "chef" },
      { id: "b1-d-pilot", pic: "pilot" },
      { id: "b1-d-police-officer", pic: "police officer" },
      { id: "b1-d-firefighter", pic: "firefighter" },
      { id: "b1-d-farmer", pic: "farmer" },
      { id: "b1-d-singer", pic: "singer" },
      { id: "b1-d-baby", pic: "baby" },
      { id: "b1-d-rocket", pic: "rocket" },
      { id: "b1-d-helicopter", pic: "helicopter" },
      { id: "b1-d-island", pic: "island" },
      { id: "b1-d-mountain", pic: "mountain" },
      { id: "b1-d-beach", pic: "beach" },
      { id: "b1-d-hospital", pic: "hospital" },
      { id: "b1-d-school", pic: "school" },
      { id: "b1-d-shop", pic: "shop" },
      { id: "b1-d-farm", pic: "farm" },
      { id: "b1-d-key", pic: "key" },
      { id: "b1-d-box", pic: "box" },
      { id: "b1-d-present", pic: "present" },
      { id: "b1-d-camera", pic: "camera" },
      { id: "b1-d-kite", pic: "kite" },
      { id: "b1-d-balloon", pic: "balloon" },
      { id: "b1-d-clock", pic: "clock" },
      { id: "b1-d-candle", pic: "candle" },
      { id: "b1-d-computer", pic: "computer" },
      { id: "b1-d-storm", pic: "storm" },
      { id: "b1-d-rainbow", pic: "rainbow" },
      { id: "b1-d-fire", pic: "fire" },
      { id: "b1-d-snowman", pic: "snowman" },
      { id: "b1-d-whale", pic: "whale" },
      { id: "b1-d-octopus", pic: "octopus" },
      { id: "b1-d-snake", pic: "snake" },
      { id: "b1-d-owl", pic: "owl" },
      { id: "b1-d-bee", pic: "bee" },
      { id: "b1-d-glasses", pic: "glasses" },
      { id: "b1-d-bag", pic: "bag" },
      { id: "b1-d-igloo", pic: "igloo" },
      { id: "b1-d-zebra", pic: "zebra" },
      { id: "b1-d-butterfly", pic: "butterfly" },
      { id: "b1-d-lamp", pic: "lamp" },
      { id: "b1-d-door", pic: "door" },
      { id: "b1-d-window", pic: "window" },
      { id: "b1-d-drum", pic: "drum" },
      { id: "b1-d-microphone", pic: "microphone" },
      { id: "b1-d-watch", pic: "watch" },
      { id: "b1-d-scissors", pic: "scissors" }
    ] },
  /* ---------- 4. IELTS 1 (B2) ---------- */
  { pictures: [
      { id: "i1-d-cat", pic: "cat" },
      { id: "i1-d-dog", pic: "dog" },
      { id: "i1-d-fish", pic: "fish" },
      { id: "i1-d-bird", pic: "bird" },
      { id: "i1-d-cow", pic: "cow" },
      { id: "i1-d-pig", pic: "pig" },
      { id: "i1-d-horse", pic: "horse" },
      { id: "i1-d-rabbit", pic: "rabbit" },
      { id: "i1-d-lion", pic: "lion" },
      { id: "i1-d-elephant", pic: "elephant" },
      { id: "i1-d-monkey", pic: "monkey" },
      { id: "i1-d-frog", pic: "frog" },
      { id: "i1-d-bear", pic: "bear" },
      { id: "i1-d-apple", pic: "apple" },
      { id: "i1-d-banana", pic: "banana" },
      { id: "i1-d-pizza", pic: "pizza" },
      { id: "i1-d-cake", pic: "cake" },
      { id: "i1-d-ice-cream", pic: "ice cream" },
      { id: "i1-d-sandwich", pic: "sandwich" },
      { id: "i1-d-car", pic: "car" },
      { id: "i1-d-bus", pic: "bus" },
      { id: "i1-d-bike", pic: "bike" },
      { id: "i1-d-plane", pic: "plane" },
      { id: "i1-d-boat", pic: "boat" },
      { id: "i1-d-train", pic: "train" },
      { id: "i1-d-house", pic: "house" },
      { id: "i1-d-tree", pic: "tree" },
      { id: "i1-d-flower", pic: "flower" },
      { id: "i1-d-sun", pic: "sun" },
      { id: "i1-d-rain", pic: "rain" },
      { id: "i1-d-snow", pic: "snow" },
      { id: "i1-d-moon", pic: "moon" },
      { id: "i1-d-star", pic: "star" },
      { id: "i1-d-ball", pic: "ball" },
      { id: "i1-d-teddy-bear", pic: "teddy bear" },
      { id: "i1-d-robot", pic: "robot" },
      { id: "i1-d-guitar", pic: "guitar" },
      { id: "i1-d-book", pic: "book" },
      { id: "i1-d-phone", pic: "phone" },
      { id: "i1-d-hat", pic: "hat" },
      { id: "i1-d-umbrella", pic: "umbrella" },
      { id: "i1-d-king", pic: "king" },
      { id: "i1-d-queen", pic: "queen" },
      { id: "i1-d-teacher", pic: "teacher" },
      { id: "i1-d-doctor", pic: "doctor" },
      { id: "i1-d-chef", pic: "chef" },
      { id: "i1-d-pilot", pic: "pilot" },
      { id: "i1-d-police-officer", pic: "police officer" },
      { id: "i1-d-firefighter", pic: "firefighter" },
      { id: "i1-d-farmer", pic: "farmer" },
      { id: "i1-d-singer", pic: "singer" },
      { id: "i1-d-baby", pic: "baby" },
      { id: "i1-d-rocket", pic: "rocket" },
      { id: "i1-d-helicopter", pic: "helicopter" },
      { id: "i1-d-island", pic: "island" },
      { id: "i1-d-mountain", pic: "mountain" },
      { id: "i1-d-beach", pic: "beach" },
      { id: "i1-d-hospital", pic: "hospital" },
      { id: "i1-d-school", pic: "school" },
      { id: "i1-d-shop", pic: "shop" },
      { id: "i1-d-farm", pic: "farm" },
      { id: "i1-d-key", pic: "key" },
      { id: "i1-d-box", pic: "box" },
      { id: "i1-d-present", pic: "present" },
      { id: "i1-d-camera", pic: "camera" },
      { id: "i1-d-kite", pic: "kite" },
      { id: "i1-d-balloon", pic: "balloon" },
      { id: "i1-d-clock", pic: "clock" },
      { id: "i1-d-candle", pic: "candle" },
      { id: "i1-d-computer", pic: "computer" },
      { id: "i1-d-storm", pic: "storm" },
      { id: "i1-d-rainbow", pic: "rainbow" },
      { id: "i1-d-fire", pic: "fire" },
      { id: "i1-d-snowman", pic: "snowman" },
      { id: "i1-d-whale", pic: "whale" },
      { id: "i1-d-octopus", pic: "octopus" },
      { id: "i1-d-snake", pic: "snake" },
      { id: "i1-d-owl", pic: "owl" },
      { id: "i1-d-bee", pic: "bee" },
      { id: "i1-d-glasses", pic: "glasses" },
      { id: "i1-d-bag", pic: "bag" },
      { id: "i1-d-igloo", pic: "igloo" },
      { id: "i1-d-zebra", pic: "zebra" },
      { id: "i1-d-butterfly", pic: "butterfly" },
      { id: "i1-d-lamp", pic: "lamp" },
      { id: "i1-d-door", pic: "door" },
      { id: "i1-d-window", pic: "window" },
      { id: "i1-d-drum", pic: "drum" },
      { id: "i1-d-microphone", pic: "microphone" },
      { id: "i1-d-watch", pic: "watch" },
      { id: "i1-d-scissors", pic: "scissors" }
    ] },
  /* ---------- 5. IELTS 2 (band 6.0) ---------- */
  { pictures: [
      { id: "i2-d-cat", pic: "cat" },
      { id: "i2-d-dog", pic: "dog" },
      { id: "i2-d-fish", pic: "fish" },
      { id: "i2-d-bird", pic: "bird" },
      { id: "i2-d-cow", pic: "cow" },
      { id: "i2-d-pig", pic: "pig" },
      { id: "i2-d-horse", pic: "horse" },
      { id: "i2-d-rabbit", pic: "rabbit" },
      { id: "i2-d-lion", pic: "lion" },
      { id: "i2-d-elephant", pic: "elephant" },
      { id: "i2-d-monkey", pic: "monkey" },
      { id: "i2-d-frog", pic: "frog" },
      { id: "i2-d-bear", pic: "bear" },
      { id: "i2-d-apple", pic: "apple" },
      { id: "i2-d-banana", pic: "banana" },
      { id: "i2-d-pizza", pic: "pizza" },
      { id: "i2-d-cake", pic: "cake" },
      { id: "i2-d-ice-cream", pic: "ice cream" },
      { id: "i2-d-sandwich", pic: "sandwich" },
      { id: "i2-d-car", pic: "car" },
      { id: "i2-d-bus", pic: "bus" },
      { id: "i2-d-bike", pic: "bike" },
      { id: "i2-d-plane", pic: "plane" },
      { id: "i2-d-boat", pic: "boat" },
      { id: "i2-d-train", pic: "train" },
      { id: "i2-d-house", pic: "house" },
      { id: "i2-d-tree", pic: "tree" },
      { id: "i2-d-flower", pic: "flower" },
      { id: "i2-d-sun", pic: "sun" },
      { id: "i2-d-rain", pic: "rain" },
      { id: "i2-d-snow", pic: "snow" },
      { id: "i2-d-moon", pic: "moon" },
      { id: "i2-d-star", pic: "star" },
      { id: "i2-d-ball", pic: "ball" },
      { id: "i2-d-teddy-bear", pic: "teddy bear" },
      { id: "i2-d-robot", pic: "robot" },
      { id: "i2-d-guitar", pic: "guitar" },
      { id: "i2-d-book", pic: "book" },
      { id: "i2-d-phone", pic: "phone" },
      { id: "i2-d-hat", pic: "hat" },
      { id: "i2-d-umbrella", pic: "umbrella" },
      { id: "i2-d-king", pic: "king" },
      { id: "i2-d-queen", pic: "queen" },
      { id: "i2-d-teacher", pic: "teacher" },
      { id: "i2-d-doctor", pic: "doctor" },
      { id: "i2-d-chef", pic: "chef" },
      { id: "i2-d-pilot", pic: "pilot" },
      { id: "i2-d-police-officer", pic: "police officer" },
      { id: "i2-d-firefighter", pic: "firefighter" },
      { id: "i2-d-farmer", pic: "farmer" },
      { id: "i2-d-singer", pic: "singer" },
      { id: "i2-d-baby", pic: "baby" },
      { id: "i2-d-rocket", pic: "rocket" },
      { id: "i2-d-helicopter", pic: "helicopter" },
      { id: "i2-d-island", pic: "island" },
      { id: "i2-d-mountain", pic: "mountain" },
      { id: "i2-d-beach", pic: "beach" },
      { id: "i2-d-hospital", pic: "hospital" },
      { id: "i2-d-school", pic: "school" },
      { id: "i2-d-shop", pic: "shop" },
      { id: "i2-d-farm", pic: "farm" },
      { id: "i2-d-key", pic: "key" },
      { id: "i2-d-box", pic: "box" },
      { id: "i2-d-present", pic: "present" },
      { id: "i2-d-camera", pic: "camera" },
      { id: "i2-d-kite", pic: "kite" },
      { id: "i2-d-balloon", pic: "balloon" },
      { id: "i2-d-clock", pic: "clock" },
      { id: "i2-d-candle", pic: "candle" },
      { id: "i2-d-computer", pic: "computer" },
      { id: "i2-d-storm", pic: "storm" },
      { id: "i2-d-rainbow", pic: "rainbow" },
      { id: "i2-d-fire", pic: "fire" },
      { id: "i2-d-snowman", pic: "snowman" },
      { id: "i2-d-whale", pic: "whale" },
      { id: "i2-d-octopus", pic: "octopus" },
      { id: "i2-d-snake", pic: "snake" },
      { id: "i2-d-owl", pic: "owl" },
      { id: "i2-d-bee", pic: "bee" },
      { id: "i2-d-glasses", pic: "glasses" },
      { id: "i2-d-bag", pic: "bag" },
      { id: "i2-d-igloo", pic: "igloo" },
      { id: "i2-d-zebra", pic: "zebra" },
      { id: "i2-d-butterfly", pic: "butterfly" },
      { id: "i2-d-lamp", pic: "lamp" },
      { id: "i2-d-door", pic: "door" },
      { id: "i2-d-window", pic: "window" },
      { id: "i2-d-drum", pic: "drum" },
      { id: "i2-d-microphone", pic: "microphone" },
      { id: "i2-d-watch", pic: "watch" },
      { id: "i2-d-scissors", pic: "scissors" }
    ] },
  /* ---------- 6. IELTS 3 (band 7.0+) ---------- */
  { pictures: [
      { id: "i3-d-cat", pic: "cat" },
      { id: "i3-d-dog", pic: "dog" },
      { id: "i3-d-fish", pic: "fish" },
      { id: "i3-d-bird", pic: "bird" },
      { id: "i3-d-cow", pic: "cow" },
      { id: "i3-d-pig", pic: "pig" },
      { id: "i3-d-horse", pic: "horse" },
      { id: "i3-d-rabbit", pic: "rabbit" },
      { id: "i3-d-lion", pic: "lion" },
      { id: "i3-d-elephant", pic: "elephant" },
      { id: "i3-d-monkey", pic: "monkey" },
      { id: "i3-d-frog", pic: "frog" },
      { id: "i3-d-bear", pic: "bear" },
      { id: "i3-d-apple", pic: "apple" },
      { id: "i3-d-banana", pic: "banana" },
      { id: "i3-d-pizza", pic: "pizza" },
      { id: "i3-d-cake", pic: "cake" },
      { id: "i3-d-ice-cream", pic: "ice cream" },
      { id: "i3-d-sandwich", pic: "sandwich" },
      { id: "i3-d-car", pic: "car" },
      { id: "i3-d-bus", pic: "bus" },
      { id: "i3-d-bike", pic: "bike" },
      { id: "i3-d-plane", pic: "plane" },
      { id: "i3-d-boat", pic: "boat" },
      { id: "i3-d-train", pic: "train" },
      { id: "i3-d-house", pic: "house" },
      { id: "i3-d-tree", pic: "tree" },
      { id: "i3-d-flower", pic: "flower" },
      { id: "i3-d-sun", pic: "sun" },
      { id: "i3-d-rain", pic: "rain" },
      { id: "i3-d-snow", pic: "snow" },
      { id: "i3-d-moon", pic: "moon" },
      { id: "i3-d-star", pic: "star" },
      { id: "i3-d-ball", pic: "ball" },
      { id: "i3-d-teddy-bear", pic: "teddy bear" },
      { id: "i3-d-robot", pic: "robot" },
      { id: "i3-d-guitar", pic: "guitar" },
      { id: "i3-d-book", pic: "book" },
      { id: "i3-d-phone", pic: "phone" },
      { id: "i3-d-hat", pic: "hat" },
      { id: "i3-d-umbrella", pic: "umbrella" },
      { id: "i3-d-king", pic: "king" },
      { id: "i3-d-queen", pic: "queen" },
      { id: "i3-d-teacher", pic: "teacher" },
      { id: "i3-d-doctor", pic: "doctor" },
      { id: "i3-d-chef", pic: "chef" },
      { id: "i3-d-pilot", pic: "pilot" },
      { id: "i3-d-police-officer", pic: "police officer" },
      { id: "i3-d-firefighter", pic: "firefighter" },
      { id: "i3-d-farmer", pic: "farmer" },
      { id: "i3-d-singer", pic: "singer" },
      { id: "i3-d-baby", pic: "baby" },
      { id: "i3-d-rocket", pic: "rocket" },
      { id: "i3-d-helicopter", pic: "helicopter" },
      { id: "i3-d-island", pic: "island" },
      { id: "i3-d-mountain", pic: "mountain" },
      { id: "i3-d-beach", pic: "beach" },
      { id: "i3-d-hospital", pic: "hospital" },
      { id: "i3-d-school", pic: "school" },
      { id: "i3-d-shop", pic: "shop" },
      { id: "i3-d-farm", pic: "farm" },
      { id: "i3-d-key", pic: "key" },
      { id: "i3-d-box", pic: "box" },
      { id: "i3-d-present", pic: "present" },
      { id: "i3-d-camera", pic: "camera" },
      { id: "i3-d-kite", pic: "kite" },
      { id: "i3-d-balloon", pic: "balloon" },
      { id: "i3-d-clock", pic: "clock" },
      { id: "i3-d-candle", pic: "candle" },
      { id: "i3-d-computer", pic: "computer" },
      { id: "i3-d-storm", pic: "storm" },
      { id: "i3-d-rainbow", pic: "rainbow" },
      { id: "i3-d-fire", pic: "fire" },
      { id: "i3-d-snowman", pic: "snowman" },
      { id: "i3-d-whale", pic: "whale" },
      { id: "i3-d-octopus", pic: "octopus" },
      { id: "i3-d-snake", pic: "snake" },
      { id: "i3-d-owl", pic: "owl" },
      { id: "i3-d-bee", pic: "bee" },
      { id: "i3-d-glasses", pic: "glasses" },
      { id: "i3-d-bag", pic: "bag" },
      { id: "i3-d-igloo", pic: "igloo" },
      { id: "i3-d-zebra", pic: "zebra" },
      { id: "i3-d-butterfly", pic: "butterfly" },
      { id: "i3-d-lamp", pic: "lamp" },
      { id: "i3-d-door", pic: "door" },
      { id: "i3-d-window", pic: "window" },
      { id: "i3-d-drum", pic: "drum" },
      { id: "i3-d-microphone", pic: "microphone" },
      { id: "i3-d-watch", pic: "watch" },
      { id: "i3-d-scissors", pic: "scissors" }
    ] }
];

/* Screen text & rules for Story Dice, per level. Editable in Edit mode. {name}, {n} are filled in.
   dice = number of dice. pairSecs = time for pairs to make their story (0 = skip straight to the class story).
   rule = the grammar rule; ruleAlt (optional) = a second rule: each roll picks one of the two at random. */
WU.content.diceScreen = {
  shared: {
    id: 'dice-screen',
    tag: 'STORY DICE', qMark: '?', dice: 4, pairSecs: 90,
    frame: 'First, ___. Then, ___. In the end, ___.',
    rule: 'Tell the story in the past tense.', ruleAlt: '', ruleShow: true,
    pairTag: 'PAIRS', pairLine: 'Make a story with every picture!',
    classTag: 'CLASS STORY', next: '{name}: add one sentence!', count: 'Sentence {n}',
    end: 'The end! Great story!', endAfter: 0,
    demo: 'TEACHER DEMO: I go first!', demoShow: false, demoWho: 'TEACHER'
  },
  levels: [
    { dice: 3, pairSecs: 0, frame: "It's a ___. It's ___.", rule: 'One sentence about one picture. One word is OK!', next: '{name}: say one sentence about this picture!', endAfter: 3, demoShow: true },
    { dice: 4 },
    { dice: 5 },
    { dice: 5, frame: '' },
    { dice: 6, pairSecs: 120, frame: '', rule: 'End the story with a twist!', ruleAlt: 'Tell the story as a news report!' },
    { dice: 6, pairSecs: 120, frame: '', rule: 'End the story with a twist!', ruleAlt: 'Tell the story as a news report!' },
    { dice: 6, pairSecs: 120, frame: '', rule: 'End the story with a twist!', ruleAlt: 'Tell the story as a news report!' }
  ]
};
