/* Warm Up: content for HOT SEAT. Generated with a permanent id on every item.
   words[level]: { id, text, pic, banned }. Beginner words are library pictures (the word comes from the picture).
   banned = words the class must not say (IELTS levels), separated by commas.
   id is PERMANENT: teacher edits (Edit mode) point at it. Never change or reuse an id. */
window.WU = window.WU || {}; WU.content = WU.content || {};
WU.content.hotseat = [
  /* ---------- 0. Beginner (A1) ---------- */
  { words: [
      { id: "a1-h-cat", pic: "cat" },
      { id: "a1-h-dog", pic: "dog" },
      { id: "a1-h-fish", pic: "fish" },
      { id: "a1-h-bird", pic: "bird" },
      { id: "a1-h-cow", pic: "cow" },
      { id: "a1-h-pig", pic: "pig" },
      { id: "a1-h-horse", pic: "horse" },
      { id: "a1-h-sheep", pic: "sheep" },
      { id: "a1-h-chicken", pic: "chicken" },
      { id: "a1-h-duck", pic: "duck" },
      { id: "a1-h-rabbit", pic: "rabbit" },
      { id: "a1-h-lion", pic: "lion" },
      { id: "a1-h-elephant", pic: "elephant" },
      { id: "a1-h-monkey", pic: "monkey" },
      { id: "a1-h-snake", pic: "snake" },
      { id: "a1-h-frog", pic: "frog" },
      { id: "a1-h-bear", pic: "bear" },
      { id: "a1-h-giraffe", pic: "giraffe" },
      { id: "a1-h-apple", pic: "apple" },
      { id: "a1-h-banana", pic: "banana" },
      { id: "a1-h-orange", pic: "orange" },
      { id: "a1-h-grapes", pic: "grapes" },
      { id: "a1-h-strawberry", pic: "strawberry" },
      { id: "a1-h-watermelon", pic: "watermelon" },
      { id: "a1-h-carrot", pic: "carrot" },
      { id: "a1-h-tomato", pic: "tomato" },
      { id: "a1-h-bread", pic: "bread" },
      { id: "a1-h-cheese", pic: "cheese" },
      { id: "a1-h-egg", pic: "egg" },
      { id: "a1-h-pizza", pic: "pizza" },
      { id: "a1-h-cake", pic: "cake" },
      { id: "a1-h-ice-cream", pic: "ice cream" },
      { id: "a1-h-sandwich", pic: "sandwich" },
      { id: "a1-h-milk", pic: "milk" },
      { id: "a1-h-juice", pic: "juice" },
      { id: "a1-h-teacher", pic: "teacher" },
      { id: "a1-h-doctor", pic: "doctor" },
      { id: "a1-h-baby", pic: "baby" },
      { id: "a1-h-t-shirt", pic: "T-shirt" },
      { id: "a1-h-dress", pic: "dress" },
      { id: "a1-h-shoes", pic: "shoes" },
      { id: "a1-h-hat", pic: "hat" },
      { id: "a1-h-glasses", pic: "glasses" },
      { id: "a1-h-umbrella", pic: "umbrella" },
      { id: "a1-h-sun", pic: "sun" },
      { id: "a1-h-rain", pic: "rain" },
      { id: "a1-h-snow", pic: "snow" },
      { id: "a1-h-moon", pic: "moon" },
      { id: "a1-h-star", pic: "star" },
      { id: "a1-h-car", pic: "car" },
      { id: "a1-h-bus", pic: "bus" },
      { id: "a1-h-bike", pic: "bike" },
      { id: "a1-h-plane", pic: "plane" },
      { id: "a1-h-boat", pic: "boat" },
      { id: "a1-h-train", pic: "train" },
      { id: "a1-h-house", pic: "house" },
      { id: "a1-h-bed", pic: "bed" },
      { id: "a1-h-chair", pic: "chair" },
      { id: "a1-h-tv", pic: "TV" },
      { id: "a1-h-book", pic: "book" },
      { id: "a1-h-pen", pic: "pen" },
      { id: "a1-h-bag", pic: "bag" },
      { id: "a1-h-computer", pic: "computer" },
      { id: "a1-h-phone", pic: "phone" },
      { id: "a1-h-ball", pic: "ball" },
      { id: "a1-h-guitar", pic: "guitar" },
      { id: "a1-h-clock", pic: "clock" },
      { id: "a1-h-key", pic: "key" },
      { id: "a1-h-robot", pic: "robot" },
      { id: "a1-h-snowman", pic: "snowman" }
    ] },
  /* ---------- 1. Elementary (A2) ---------- */
  { words: [
      { id: "a2-h-kitchen", text: "kitchen" },
      { id: "a2-h-bedroom", text: "bedroom" },
      { id: "a2-h-bathroom", text: "bathroom" },
      { id: "a2-h-teacher", text: "teacher", pic: "teacher" },
      { id: "a2-h-doctor", text: "doctor", pic: "doctor" },
      { id: "a2-h-supermarket", text: "supermarket" },
      { id: "a2-h-breakfast", text: "breakfast" },
      { id: "a2-h-weekend", text: "weekend" },
      { id: "a2-h-birthday", text: "birthday" },
      { id: "a2-h-holiday", text: "holiday" },
      { id: "a2-h-bicycle", text: "bicycle" },
      { id: "a2-h-umbrella", text: "umbrella", pic: "umbrella" },
      { id: "a2-h-sandwich", text: "sandwich", pic: "sandwich" },
      { id: "a2-h-homework", text: "homework" },
      { id: "a2-h-library", text: "library" },
      { id: "a2-h-hospital", text: "hospital", pic: "hospital" },
      { id: "a2-h-football", text: "football", pic: "football" },
      { id: "a2-h-swimming", text: "swimming", pic: "swimming" },
      { id: "a2-h-winter", text: "winter" },
      { id: "a2-h-summer", text: "summer" },
      { id: "a2-h-chocolate", text: "chocolate", pic: "chocolate" },
      { id: "a2-h-coffee", text: "coffee", pic: "coffee" },
      { id: "a2-h-grandmother", text: "grandmother", pic: "grandmother" },
      { id: "a2-h-brother", text: "brother", pic: "brother" },
      { id: "a2-h-friend", text: "friend" },
      { id: "a2-h-phone", text: "phone", pic: "phone" },
      { id: "a2-h-computer", text: "computer", pic: "computer" },
      { id: "a2-h-television", text: "television" },
      { id: "a2-h-camera", text: "camera", pic: "camera" },
      { id: "a2-h-guitar", text: "guitar", pic: "guitar" },
      { id: "a2-h-beach", text: "beach", pic: "beach" },
      { id: "a2-h-mountain", text: "mountain", pic: "mountain" },
      { id: "a2-h-river", text: "river" },
      { id: "a2-h-airport", text: "airport" },
      { id: "a2-h-train", text: "train", pic: "train" },
      { id: "a2-h-taxi", text: "taxi", pic: "taxi" },
      { id: "a2-h-restaurant", text: "restaurant" },
      { id: "a2-h-cinema", text: "cinema" },
      { id: "a2-h-park", text: "park", pic: "park" },
      { id: "a2-h-zoo", text: "zoo" },
      { id: "a2-h-elephant", text: "elephant", pic: "elephant" },
      { id: "a2-h-giraffe", text: "giraffe", pic: "giraffe" },
      { id: "a2-h-monkey", text: "monkey", pic: "monkey" },
      { id: "a2-h-spider", text: "spider" },
      { id: "a2-h-banana", text: "banana", pic: "banana" },
      { id: "a2-h-pizza", text: "pizza", pic: "pizza" },
      { id: "a2-h-ice-cream", text: "ice cream", pic: "ice cream" },
      { id: "a2-h-shoes", text: "shoes", pic: "shoes" },
      { id: "a2-h-jacket", text: "jacket", pic: "jacket" },
      { id: "a2-h-glasses", text: "glasses", pic: "glasses" },
      { id: "a2-h-clock", text: "clock", pic: "clock" },
      { id: "a2-h-window", text: "window", pic: "window" },
      { id: "a2-h-garden", text: "garden" },
      { id: "a2-h-farm", text: "farm", pic: "farm" },
      { id: "a2-h-city", text: "city", pic: "city" },
      { id: "a2-h-island", text: "island", pic: "island" },
      { id: "a2-h-rainbow", text: "rainbow", pic: "rainbow" },
      { id: "a2-h-snowman", text: "snowman", pic: "snowman" },
      { id: "a2-h-dentist", text: "dentist" },
      { id: "a2-h-police-officer", text: "police officer", pic: "police officer" },
      { id: "a2-h-hairdresser", text: "hairdresser" },
      { id: "a2-h-toothbrush", text: "toothbrush", pic: "toothbrush" }
    ] },
  /* ---------- 2. Pre-Intermediate (A2+) ---------- */
  { words: [
      { id: "a2p-h-passport", text: "passport" },
      { id: "a2p-h-wallet", text: "wallet" },
      { id: "a2p-h-neighbour", text: "neighbour" },
      { id: "a2p-h-headache", text: "headache" },
      { id: "a2p-h-suitcase", text: "suitcase" },
      { id: "a2p-h-alarm-clock", text: "alarm clock" },
      { id: "a2p-h-traffic-light", text: "traffic light" },
      { id: "a2p-h-shopping-centre", text: "shopping centre" },
      { id: "a2p-h-post-office", text: "post office" },
      { id: "a2p-h-pharmacy", text: "pharmacy" },
      { id: "a2p-h-ticket", text: "ticket" },
      { id: "a2p-h-map", text: "map" },
      { id: "a2p-h-calendar", text: "calendar" },
      { id: "a2p-h-toothpaste", text: "toothpaste" },
      { id: "a2p-h-shampoo", text: "shampoo" },
      { id: "a2p-h-pillow", text: "pillow" },
      { id: "a2p-h-blanket", text: "blanket" },
      { id: "a2p-h-microwave", text: "microwave" },
      { id: "a2p-h-fridge", text: "fridge" },
      { id: "a2p-h-oven", text: "oven" },
      { id: "a2p-h-ladder", text: "ladder" },
      { id: "a2p-h-bridge", text: "bridge" },
      { id: "a2p-h-desert", text: "desert" },
      { id: "a2p-h-forest", text: "forest" },
      { id: "a2p-h-volcano", text: "volcano" },
      { id: "a2p-h-thunder", text: "thunder" },
      { id: "a2p-h-sunglasses", text: "sunglasses" },
      { id: "a2p-h-scarf", text: "scarf" },
      { id: "a2p-h-gloves", text: "gloves" },
      { id: "a2p-h-boots", text: "boots" },
      { id: "a2p-h-necklace", text: "necklace" },
      { id: "a2p-h-watch", text: "watch" },
      { id: "a2p-h-backpack", text: "backpack" },
      { id: "a2p-h-notebook", text: "notebook" },
      { id: "a2p-h-calculator", text: "calculator" },
      { id: "a2p-h-dictionary", text: "dictionary" },
      { id: "a2p-h-email", text: "email" },
      { id: "a2p-h-selfie", text: "selfie" },
      { id: "a2p-h-vegetarian", text: "vegetarian" },
      { id: "a2p-h-pancake", text: "pancake" },
      { id: "a2p-h-popcorn", text: "popcorn" },
      { id: "a2p-h-cereal", text: "cereal" },
      { id: "a2p-h-honey", text: "honey" },
      { id: "a2p-h-pepper", text: "pepper" },
      { id: "a2p-h-salt", text: "salt" },
      { id: "a2p-h-soup", text: "soup" },
      { id: "a2p-h-noodles", text: "noodles" },
      { id: "a2p-h-farmer", text: "farmer" },
      { id: "a2p-h-pilot", text: "pilot" },
      { id: "a2p-h-firefighter", text: "firefighter" },
      { id: "a2p-h-waiter", text: "waiter" },
      { id: "a2p-h-mechanic", text: "mechanic" },
      { id: "a2p-h-journalist", text: "journalist" },
      { id: "a2p-h-hotel", text: "hotel" },
      { id: "a2p-h-museum", text: "museum" },
      { id: "a2p-h-stadium", text: "stadium" },
      { id: "a2p-h-playground", text: "playground" },
      { id: "a2p-h-petrol-station", text: "petrol station" },
      { id: "a2p-h-laundry", text: "laundry" },
      { id: "a2p-h-homework", text: "homework" }
    ] },
  /* ---------- 3. Intermediate (B1) ---------- */
  { words: [
      { id: "b1-h-job-interview", text: "job interview" },
      { id: "b1-h-wedding", text: "wedding" },
      { id: "b1-h-festival", text: "festival" },
      { id: "b1-h-souvenir", text: "souvenir" },
      { id: "b1-h-luggage", text: "luggage" },
      { id: "b1-h-sunrise", text: "sunrise" },
      { id: "b1-h-campfire", text: "campfire" },
      { id: "b1-h-lighthouse", text: "lighthouse" },
      { id: "b1-h-skyscraper", text: "skyscraper" },
      { id: "b1-h-underground", text: "underground" },
      { id: "b1-h-parking-ticket", text: "parking ticket" },
      { id: "b1-h-vending-machine", text: "vending machine" },
      { id: "b1-h-lottery", text: "lottery" },
      { id: "b1-h-fireworks", text: "fireworks" },
      { id: "b1-h-earthquake", text: "earthquake" },
      { id: "b1-h-flood", text: "flood" },
      { id: "b1-h-recycling", text: "recycling" },
      { id: "b1-h-pollution", text: "pollution" },
      { id: "b1-h-headphones", text: "headphones" },
      { id: "b1-h-charger", text: "charger" },
      { id: "b1-h-remote-control", text: "remote control" },
      { id: "b1-h-wifi", text: "wifi" },
      { id: "b1-h-password", text: "password" },
      { id: "b1-h-screenshot", text: "screenshot" },
      { id: "b1-h-influencer", text: "influencer" },
      { id: "b1-h-subscription", text: "subscription" },
      { id: "b1-h-delivery", text: "delivery" },
      { id: "b1-h-refund", text: "refund" },
      { id: "b1-h-discount", text: "discount" },
      { id: "b1-h-bargain", text: "bargain" },
      { id: "b1-h-deadline", text: "deadline" },
      { id: "b1-h-salary", text: "salary" },
      { id: "b1-h-promotion", text: "promotion" },
      { id: "b1-h-colleague", text: "colleague" },
      { id: "b1-h-landlord", text: "landlord" },
      { id: "b1-h-flatmate", text: "flatmate" },
      { id: "b1-h-stranger", text: "stranger" },
      { id: "b1-h-tourist", text: "tourist" },
      { id: "b1-h-celebrity", text: "celebrity" },
      { id: "b1-h-detective", text: "detective" },
      { id: "b1-h-surgeon", text: "surgeon" },
      { id: "b1-h-lawyer", text: "lawyer" },
      { id: "b1-h-architect", text: "architect" },
      { id: "b1-h-plumber", text: "plumber" },
      { id: "b1-h-referee", text: "referee" },
      { id: "b1-h-goalkeeper", text: "goalkeeper" },
      { id: "b1-h-marathon", text: "marathon" },
      { id: "b1-h-yoga", text: "yoga" },
      { id: "b1-h-gym", text: "gym" },
      { id: "b1-h-diet", text: "diet" },
      { id: "b1-h-recipe", text: "recipe" },
      { id: "b1-h-leftovers", text: "leftovers" },
      { id: "b1-h-snack", text: "snack" },
      { id: "b1-h-picnic", text: "picnic" },
      { id: "b1-h-sun-cream", text: "sun cream" },
      { id: "b1-h-mosquito", text: "mosquito" },
      { id: "b1-h-jellyfish", text: "jellyfish" },
      { id: "b1-h-hurricane", text: "hurricane" },
      { id: "b1-h-traffic-jam", text: "traffic jam" },
      { id: "b1-h-homesick", text: "homesick" }
    ] },
  /* ---------- 4. IELTS 1 (B2) ---------- */
  { words: [
      { id: "i1-h-freedom", text: "freedom", banned: "free, prison, liberty" },
      { id: "i1-h-success", text: "success", banned: "win, achieve, fail" },
      { id: "i1-h-happiness", text: "happiness", banned: "happy, smile, joy" },
      { id: "i1-h-trust", text: "trust", banned: "believe, honest, rely" },
      { id: "i1-h-courage", text: "courage", banned: "brave, fear, hero" },
      { id: "i1-h-friendship", text: "friendship", banned: "friend, close, together" },
      { id: "i1-h-honesty", text: "honesty", banned: "truth, lie, honest" },
      { id: "i1-h-patience", text: "patience", banned: "wait, calm, time" },
      { id: "i1-h-ambition", text: "ambition", banned: "goal, dream, want" },
      { id: "i1-h-jealousy", text: "jealousy", banned: "envy, want, green" },
      { id: "i1-h-loneliness", text: "loneliness", banned: "alone, lonely, friends" },
      { id: "i1-h-confidence", text: "confidence", banned: "sure, believe, shy" },
      { id: "i1-h-curiosity", text: "curiosity", banned: "curious, question, know" },
      { id: "i1-h-kindness", text: "kindness", banned: "kind, nice, help" },
      { id: "i1-h-responsibility", text: "responsibility", banned: "duty, blame, job" },
      { id: "i1-h-tradition", text: "tradition", banned: "old, culture, custom" },
      { id: "i1-h-education", text: "education", banned: "school, learn, teach" },
      { id: "i1-h-technology", text: "technology", banned: "computer, phone, machine" },
      { id: "i1-h-pollution", text: "pollution", banned: "dirty, air, environment" },
      { id: "i1-h-tourism", text: "tourism", banned: "tourist, travel, holiday" },
      { id: "i1-h-advertising", text: "advertising", banned: "advert, sell, buy" },
      { id: "i1-h-competition", text: "competition", banned: "compete, win, race" },
      { id: "i1-h-nostalgia", text: "nostalgia", banned: "past, memory, miss" },
      { id: "i1-h-boredom", text: "boredom", banned: "bored, nothing, dull" },
      { id: "i1-h-luck", text: "luck", banned: "lucky, chance, random" },
      { id: "i1-h-stress", text: "stress", banned: "worry, pressure, tired" },
      { id: "i1-h-failure", text: "failure", banned: "fail, lose, mistake" },
      { id: "i1-h-childhood", text: "childhood", banned: "child, young, kid" },
      { id: "i1-h-retirement", text: "retirement", banned: "old, work, stop" },
      { id: "i1-h-leadership", text: "leadership", banned: "leader, boss, follow" },
      { id: "i1-h-fashion", text: "fashion", banned: "clothes, style, trend" },
      { id: "i1-h-fame", text: "fame", banned: "famous, celebrity, star" },
      { id: "i1-h-privacy", text: "privacy", banned: "private, secret, alone" },
      { id: "i1-h-guilt", text: "guilt", banned: "guilty, sorry, wrong" },
      { id: "i1-h-pride", text: "pride", banned: "proud, feel, achievement" },
      { id: "i1-h-generosity", text: "generosity", banned: "give, share, generous" },
      { id: "i1-h-laziness", text: "laziness", banned: "lazy, work, sofa" },
      { id: "i1-h-motivation", text: "motivation", banned: "reason, energy, want" },
      { id: "i1-h-imagination", text: "imagination", banned: "imagine, creative, think" },
      { id: "i1-h-adventure", text: "adventure", banned: "exciting, travel, explore" },
      { id: "i1-h-wisdom", text: "wisdom", banned: "wise, old, know" },
      { id: "i1-h-revenge", text: "revenge", banned: "back, hurt, angry" },
      { id: "i1-h-peace", text: "peace", banned: "war, quiet, calm" },
      { id: "i1-h-debt", text: "debt", banned: "money, owe, bank" },
      { id: "i1-h-habit", text: "habit", banned: "always, routine, do" },
      { id: "i1-h-gossip", text: "gossip", banned: "talk, secret, rumour" },
      { id: "i1-h-homesickness", text: "homesickness", banned: "home, miss, family" },
      { id: "i1-h-regret", text: "regret", banned: "sorry, wish, past" },
      { id: "i1-h-risk", text: "risk", banned: "danger, chance, safe" },
      { id: "i1-h-security", text: "security", banned: "safe, protect, guard" },
      { id: "i1-h-charity", text: "charity", banned: "give, money, help" },
      { id: "i1-h-volunteer", text: "volunteer", banned: "help, free, work" },
      { id: "i1-h-inflation", text: "inflation", banned: "price, money, rise" },
      { id: "i1-h-migration", text: "migration", banned: "move, country, birds" },
      { id: "i1-h-deforestation", text: "deforestation", banned: "trees, cut, forest" },
      { id: "i1-h-unemployment", text: "unemployment", banned: "job, work, lose" },
      { id: "i1-h-fear", text: "fear", banned: "afraid, scared, dark" },
      { id: "i1-h-hope", text: "hope", banned: "wish, future, positive" },
      { id: "i1-h-anger", text: "anger", banned: "angry, mad, shout" },
      { id: "i1-h-surprise", text: "surprise", banned: "surprised, unexpected, shock" }
    ] },
  /* ---------- 5. IELTS 2 (band 6.0) ---------- */
  { words: [
      { id: "i2-h-integrity", text: "integrity", banned: "honest, moral, principles" },
      { id: "i2-h-empathy", text: "empathy", banned: "feel, understand, shoes" },
      { id: "i2-h-resilience", text: "resilience", banned: "strong, recover, back" },
      { id: "i2-h-compromise", text: "compromise", banned: "agree, both, middle" },
      { id: "i2-h-prejudice", text: "prejudice", banned: "judge, opinion, unfair" },
      { id: "i2-h-bureaucracy", text: "bureaucracy", banned: "paper, forms, government" },
      { id: "i2-h-consumerism", text: "consumerism", banned: "buy, shopping, products" },
      { id: "i2-h-globalisation", text: "globalisation", banned: "world, international, countries" },
      { id: "i2-h-sustainability", text: "sustainability", banned: "environment, future, green" },
      { id: "i2-h-censorship", text: "censorship", banned: "ban, media, control" },
      { id: "i2-h-democracy", text: "democracy", banned: "vote, election, people" },
      { id: "i2-h-diversity", text: "diversity", banned: "different, variety, culture" },
      { id: "i2-h-equality", text: "equality", banned: "equal, same, rights" },
      { id: "i2-h-poverty", text: "poverty", banned: "poor, money, rich" },
      { id: "i2-h-corruption", text: "corruption", banned: "bribe, money, politician" },
      { id: "i2-h-propaganda", text: "propaganda", banned: "government, lies, message" },
      { id: "i2-h-innovation", text: "innovation", banned: "new, idea, invent" },
      { id: "i2-h-procrastination", text: "procrastination", banned: "later, delay, tomorrow" },
      { id: "i2-h-perfectionism", text: "perfectionism", banned: "perfect, mistake, best" },
      { id: "i2-h-optimism", text: "optimism", banned: "positive, hope, glass" },
      { id: "i2-h-pessimism", text: "pessimism", banned: "negative, worst, glass" },
      { id: "i2-h-sarcasm", text: "sarcasm", banned: "mean, joke, opposite" },
      { id: "i2-h-hypocrisy", text: "hypocrisy", banned: "say, do, double" },
      { id: "i2-h-loyalty", text: "loyalty", banned: "faithful, friend, betray" },
      { id: "i2-h-betrayal", text: "betrayal", banned: "trust, friend, back" },
      { id: "i2-h-dignity", text: "dignity", banned: "respect, self, pride" },
      { id: "i2-h-humility", text: "humility", banned: "humble, modest, proud" },
      { id: "i2-h-arrogance", text: "arrogance", banned: "proud, better, superior" },
      { id: "i2-h-discipline", text: "discipline", banned: "rules, control, strict" },
      { id: "i2-h-independence", text: "independence", banned: "alone, free, own" },
      { id: "i2-h-tolerance", text: "tolerance", banned: "accept, different, patient" },
      { id: "i2-h-justice", text: "justice", banned: "fair, law, court" },
      { id: "i2-h-authority", text: "authority", banned: "power, control, boss" },
      { id: "i2-h-rebellion", text: "rebellion", banned: "fight, rules, against" },
      { id: "i2-h-conformity", text: "conformity", banned: "same, rules, follow" },
      { id: "i2-h-identity", text: "identity", banned: "who, self, personal" },
      { id: "i2-h-heritage", text: "heritage", banned: "history, past, family" },
      { id: "i2-h-urbanisation", text: "urbanisation", banned: "city, move, countryside" },
      { id: "i2-h-automation", text: "automation", banned: "machine, robot, jobs" },
      { id: "i2-h-surveillance", text: "surveillance", banned: "camera, watch, spy" },
      { id: "i2-h-misinformation", text: "misinformation", banned: "false, news, fake" },
      { id: "i2-h-addiction", text: "addiction", banned: "habit, stop, need" },
      { id: "i2-h-burnout", text: "burnout", banned: "tired, work, stress" },
      { id: "i2-h-well-being", text: "well-being", banned: "health, happy, feel" },
      { id: "i2-h-productivity", text: "productivity", banned: "work, efficient, output" },
      { id: "i2-h-networking", text: "networking", banned: "contacts, people, business" },
      { id: "i2-h-entrepreneurship", text: "entrepreneurship", banned: "business, start, company" },
      { id: "i2-h-minimalism", text: "minimalism", banned: "less, simple, possessions" },
      { id: "i2-h-materialism", text: "materialism", banned: "things, money, buy" },
      { id: "i2-h-patriotism", text: "patriotism", banned: "country, love, flag" },
      { id: "i2-h-stereotype", text: "stereotype", banned: "typical, judge, group" },
      { id: "i2-h-discrimination", text: "discrimination", banned: "unfair, treat, different" },
      { id: "i2-h-inequality", text: "inequality", banned: "equal, gap, rich" },
      { id: "i2-h-commute", text: "commute", banned: "travel, work, train" },
      { id: "i2-h-nostalgia", text: "nostalgia", banned: "past, memory, remember" },
      { id: "i2-h-generosity", text: "generosity", banned: "give, share, kind" },
      { id: "i2-h-ambition", text: "ambition", banned: "goal, success, dream" },
      { id: "i2-h-charisma", text: "charisma", banned: "attractive, personality, leader" },
      { id: "i2-h-curiosity", text: "curiosity", banned: "question, know, interest" },
      { id: "i2-h-superstition", text: "superstition", banned: "luck, belief, black cat" }
    ] },
  /* ---------- 6. IELTS 3 (band 7.0+) ---------- */
  { words: [
      { id: "i3-h-serendipity", text: "serendipity", banned: "luck, chance, accident" },
      { id: "i3-h-paradox", text: "paradox", banned: "contradiction, opposite, logic" },
      { id: "i3-h-dilemma", text: "dilemma", banned: "choice, difficult, two" },
      { id: "i3-h-ambiguity", text: "ambiguity", banned: "unclear, meaning, two" },
      { id: "i3-h-nuance", text: "nuance", banned: "detail, subtle, small" },
      { id: "i3-h-cynicism", text: "cynicism", banned: "doubt, negative, trust" },
      { id: "i3-h-idealism", text: "idealism", banned: "perfect, ideal, dream" },
      { id: "i3-h-pragmatism", text: "pragmatism", banned: "practical, realistic, work" },
      { id: "i3-h-altruism", text: "altruism", banned: "selfless, help, others" },
      { id: "i3-h-nihilism", text: "nihilism", banned: "meaning, nothing, life" },
      { id: "i3-h-utopia", text: "utopia", banned: "perfect, society, world" },
      { id: "i3-h-dystopia", text: "dystopia", banned: "future, bad, society" },
      { id: "i3-h-meritocracy", text: "meritocracy", banned: "talent, reward, effort" },
      { id: "i3-h-accountability", text: "accountability", banned: "responsible, blame, explain" },
      { id: "i3-h-transparency", text: "transparency", banned: "open, clear, hide" },
      { id: "i3-h-legitimacy", text: "legitimacy", banned: "legal, right, accepted" },
      { id: "i3-h-sovereignty", text: "sovereignty", banned: "country, power, independent" },
      { id: "i3-h-secularism", text: "secularism", banned: "religion, state, separate" },
      { id: "i3-h-relativism", text: "relativism", banned: "truth, depends, culture" },
      { id: "i3-h-catharsis", text: "catharsis", banned: "release, emotion, relief" },
      { id: "i3-h-complacency", text: "complacency", banned: "satisfied, lazy, comfortable" },
      { id: "i3-h-apathy", text: "apathy", banned: "care, interest, indifferent" },
      { id: "i3-h-zeitgeist", text: "zeitgeist", banned: "spirit, time, age" },
      { id: "i3-h-gaslighting", text: "gaslighting", banned: "manipulate, doubt, crazy" },
      { id: "i3-h-echo-chamber", text: "echo chamber", banned: "opinion, same, social media" },
      { id: "i3-h-confirmation-bias", text: "confirmation bias", banned: "believe, evidence, ignore" },
      { id: "i3-h-groupthink", text: "groupthink", banned: "group, agree, decision" },
      { id: "i3-h-cognitive-dissonance", text: "cognitive dissonance", banned: "belief, conflict, uncomfortable" },
      { id: "i3-h-placebo", text: "placebo", banned: "medicine, fake, effect" },
      { id: "i3-h-scapegoat", text: "scapegoat", banned: "blame, innocent, someone" },
      { id: "i3-h-whistleblower", text: "whistleblower", banned: "secret, company, report" },
      { id: "i3-h-bystander-effect", text: "bystander effect", banned: "help, crowd, watch" },
      { id: "i3-h-tipping-point", text: "tipping point", banned: "moment, change, sudden" },
      { id: "i3-h-paradigm-shift", text: "paradigm shift", banned: "change, thinking, model" },
      { id: "i3-h-status-quo", text: "status quo", banned: "current, change, situation" },
      { id: "i3-h-double-standard", text: "double standard", banned: "rules, different, unfair" },
      { id: "i3-h-glass-ceiling", text: "glass ceiling", banned: "women, promotion, top" },
      { id: "i3-h-brain-drain", text: "brain drain", banned: "leave, country, talent" },
      { id: "i3-h-soft-power", text: "soft power", banned: "influence, culture, country" },
      { id: "i3-h-social-mobility", text: "social mobility", banned: "class, move, rich" },
      { id: "i3-h-planned-obsolescence", text: "planned obsolescence", banned: "break, product, buy" },
      { id: "i3-h-digital-footprint", text: "digital footprint", banned: "online, data, trace" },
      { id: "i3-h-filter-bubble", text: "filter bubble", banned: "algorithm, see, opinion" },
      { id: "i3-h-impostor-syndrome", text: "impostor syndrome", banned: "fake, doubt, success" },
      { id: "i3-h-moral-hazard", text: "moral hazard", banned: "risk, protect, consequences" },
      { id: "i3-h-opportunity-cost", text: "opportunity cost", banned: "choose, lose, alternative" },
      { id: "i3-h-self-fulfilling-prophecy", text: "self-fulfilling prophecy", banned: "expect, happen, belief" },
      { id: "i3-h-rite-of-passage", text: "rite of passage", banned: "adult, ceremony, stage" },
      { id: "i3-h-stoicism", text: "stoicism", banned: "calm, emotion, accept" },
      { id: "i3-h-mindfulness", text: "mindfulness", banned: "present, meditate, aware" },
      { id: "i3-h-vulnerability", text: "vulnerability", banned: "weak, open, hurt" },
      { id: "i3-h-escapism", text: "escapism", banned: "escape, reality, fantasy" },
      { id: "i3-h-hedonism", text: "hedonism", banned: "pleasure, enjoy, life" },
      { id: "i3-h-snobbery", text: "snobbery", banned: "superior, class, look down" },
      { id: "i3-h-eloquence", text: "eloquence", banned: "speak, words, fluent" },
      { id: "i3-h-charisma", text: "charisma", banned: "charm, personality, attract" },
      { id: "i3-h-hindsight", text: "hindsight", banned: "past, look back, know" },
      { id: "i3-h-compassion", text: "compassion", banned: "kind, suffering, care" },
      { id: "i3-h-integrity", text: "integrity", banned: "honest, moral, principles" },
      { id: "i3-h-irony", text: "irony", banned: "opposite, expect, funny" }
    ] }
];

/* Screen text & timing for Hot Seat, per level. Editable in Edit mode. {name}, {n} are filled in. */
WU.content.hotseatScreen = {
  shared: {
    id: 'hotseat-screen',
    tag: 'HOT SEAT', secs: 60, who: "Who's in the hot seat?", qMark: '?',
    rule: 'Back to the board! The class describes, you guess.', ruleShow: true,
    rule2: 'Describe it in full sentences. No pointing!', rule2Show: true,
    banned: "Don't say:", score: 'Score', high: 'High score: {n}', beat: 'Beat {n}!',
    result: '{name} scored {n}!', newHigh: 'NEW HIGH SCORE!', award: 'Which team? Press 1-4', points: '+{n} points!',
    demo: 'TEACHER DEMO: I sit first!', demoShow: false, demoWho: 'TEACHER'
  },
  levels: [
    { secs: 90, rule2: 'One word is OK! Gestures are OK!', demoShow: true },
    {}, {}, {},
    { rule2: 'Full sentences. Do not say the banned words!' },
    { rule2: 'Full sentences. Do not say the banned words!' },
    { rule2: 'Full sentences. Do not say the banned words!' }
  ]
};
