/* Warm Up: content for LIE DETECTOR. Generated with a permanent id on every item.
   questions / first (First lesson mode): { id, text, pic, frame }. frame = this question's answer frame; none = the level frame.
   Never about family problems, money, religion, politics, health or relationships.
   id is PERMANENT: teacher edits (Edit mode) point at it. Never change or reuse an id. */
window.WU = window.WU || {}; WU.content = WU.content || {};
WU.content.lie = [
  /* ---------- 0. Beginner (A1) ---------- */
  {
    questions: [
      { id: "a1-q-do-you-have-a-cat", text: "Do you have a cat?", pic: "cat" },
      { id: "a1-q-do-you-have-a-dog", text: "Do you have a dog?", pic: "dog" },
      { id: "a1-q-do-you-have-a-bike", text: "Do you have a bike?", pic: "bike" },
      { id: "a1-q-do-you-have-a-guitar", text: "Do you have a guitar?", pic: "guitar" },
      { id: "a1-q-do-you-have-a-robot", text: "Do you have a robot?", pic: "robot" },
      { id: "a1-q-do-you-have-a-teddy-bear", text: "Do you have a teddy bear?", pic: "teddy bear" },
      { id: "a1-q-do-you-have-a-kite", text: "Do you have a kite?", pic: "kite" },
      { id: "a1-q-do-you-have-a-watch", text: "Do you have a watch?", pic: "watch" },
      { id: "a1-q-do-you-have-a-camera", text: "Do you have a camera?", pic: "camera" },
      { id: "a1-q-do-you-have-an-umbrella", text: "Do you have an umbrella?", pic: "umbrella" },
      { id: "a1-q-do-you-like-pizza", text: "Do you like pizza?", pic: "pizza" },
      { id: "a1-q-do-you-like-ice-cream", text: "Do you like ice cream?", pic: "ice cream" },
      { id: "a1-q-do-you-like-bananas", text: "Do you like bananas?", pic: "banana" },
      { id: "a1-q-do-you-like-cheese", text: "Do you like cheese?", pic: "cheese" },
      { id: "a1-q-do-you-like-tea", text: "Do you like tea?", pic: "tea" },
      { id: "a1-q-do-you-like-milk", text: "Do you like milk?", pic: "milk" },
      { id: "a1-q-do-you-like-chocolate", text: "Do you like chocolate?", pic: "chocolate" },
      { id: "a1-q-do-you-like-football", text: "Do you like football?", pic: "football" },
      { id: "a1-q-do-you-like-snow", text: "Do you like snow?", pic: "snow" },
      { id: "a1-q-do-you-like-rain", text: "Do you like rain?", pic: "rain" },
      { id: "a1-q-do-you-like-snakes", text: "Do you like snakes?", pic: "snake" },
      { id: "a1-q-do-you-like-frogs", text: "Do you like frogs?", pic: "frog" },
      { id: "a1-q-can-you-swim", text: "Can you swim?", pic: "swimming", frame: "Yes, I can. / No, I can't." },
      { id: "a1-q-can-you-play-the-piano", text: "Can you play the piano?", pic: "piano", frame: "Yes, I can. / No, I can't." },
      { id: "a1-q-can-you-ride-a-bike", text: "Can you ride a bike?", pic: "bike", frame: "Yes, I can. / No, I can't." },
      { id: "a1-q-can-you-play-tennis", text: "Can you play tennis?", pic: "tennis", frame: "Yes, I can. / No, I can't." },
      { id: "a1-q-can-you-cook-eggs", text: "Can you cook eggs?", pic: "egg", frame: "Yes, I can. / No, I can't." },
      { id: "a1-q-can-you-draw-a-cat", text: "Can you draw a cat?", pic: "pencil", frame: "Yes, I can. / No, I can't." },
      { id: "a1-q-is-your-bag-black", text: "Is your bag black?", pic: "bag", frame: "Yes, it is. / No, it isn't." },
      { id: "a1-q-is-your-phone-new", text: "Is your phone new?", pic: "phone", frame: "Yes, it is. / No, it isn't." },
      { id: "a1-q-do-you-have-a-tv-in", text: "Do you have a TV in your bedroom?", pic: "TV" },
      { id: "a1-q-do-you-like-the-sun", text: "Do you like the sun?", pic: "sun" }
    ],
    first: [
      { id: "a1-f-do-you-like-pizza", text: "Do you like pizza?", pic: "pizza" },
      { id: "a1-f-do-you-like-dogs", text: "Do you like dogs?", pic: "dog" },
      { id: "a1-f-do-you-like-cats", text: "Do you like cats?", pic: "cat" },
      { id: "a1-f-do-you-like-football", text: "Do you like football?", pic: "football" },
      { id: "a1-f-can-you-swim", text: "Can you swim?", pic: "swimming", frame: "Yes, I can. / No, I can't." },
      { id: "a1-f-do-you-like-music", text: "Do you like music?", pic: "guitar" },
      { id: "a1-f-do-you-have-a-phone", text: "Do you have a phone?", pic: "phone" },
      { id: "a1-f-do-you-like-ice-cream", text: "Do you like ice cream?", pic: "ice cream" },
      { id: "a1-f-do-you-like-snow", text: "Do you like snow?", pic: "snow" },
      { id: "a1-f-can-you-play-the-piano", text: "Can you play the piano?", pic: "piano", frame: "Yes, I can. / No, I can't." },
      { id: "a1-f-do-you-like-tea", text: "Do you like tea?", pic: "tea" },
      { id: "a1-f-do-you-like-coffee", text: "Do you like coffee?", pic: "coffee" },
      { id: "a1-f-do-you-have-a-bike", text: "Do you have a bike?", pic: "bike" },
      { id: "a1-f-do-you-like-books", text: "Do you like books?", pic: "book" },
      { id: "a1-f-do-you-like-rain", text: "Do you like rain?", pic: "rain" }
    ]
  },
  /* ---------- 1. Elementary (A2) ---------- */
  {
    questions: [
      { id: "a2-q-did-you-eat-breakfast-today", text: "Did you eat breakfast today?", pic: "bread" },
      { id: "a2-q-did-you-watch-tv-last-night", text: "Did you watch TV last night?", pic: "TV" },
      { id: "a2-q-did-you-walk-to-school-today", text: "Did you walk to school today?", pic: "shoes" },
      { id: "a2-q-did-you-play-a-game-yesterday", text: "Did you play a game yesterday?", pic: "ball" },
      { id: "a2-q-did-you-drink-coffee-this-morning", text: "Did you drink coffee this morning?", pic: "coffee" },
      { id: "a2-q-did-you-go-to-bed-after", text: "Did you go to bed after 11 last night?", pic: "bed" },
      { id: "a2-q-did-you-cook-dinner-yesterday", text: "Did you cook dinner yesterday?", pic: "pan" },
      { id: "a2-q-did-you-read-a-book-last", text: "Did you read a book last week?", pic: "book" },
      { id: "a2-q-did-you-go-to-the-cinema", text: "Did you go to the cinema last month?", pic: "camera" },
      { id: "a2-q-did-you-sing-in-the-shower", text: "Did you sing in the shower today?", pic: "microphone" },
      { id: "a2-q-did-you-eat-pizza-last-weekend", text: "Did you eat pizza last weekend?", pic: "pizza" },
      { id: "a2-q-did-you-take-a-photo-yesterday", text: "Did you take a photo yesterday?", pic: "camera" },
      { id: "a2-q-did-you-see-a-dog-today", text: "Did you see a dog today?", pic: "dog" },
      { id: "a2-q-did-you-go-shopping-last-weekend", text: "Did you go shopping last weekend?", pic: "shop" },
      { id: "a2-q-did-you-play-football-last-week", text: "Did you play football last week?", pic: "football" },
      { id: "a2-q-did-you-listen-to-music-this", text: "Did you listen to music this morning?", pic: "guitar" },
      { id: "a2-q-did-you-get-up-before-7", text: "Did you get up before 7 today?", pic: "clock" },
      { id: "a2-q-did-you-send-a-message-today", text: "Did you send a message today?", pic: "phone" },
      { id: "a2-q-did-you-visit-a-new-place", text: "Did you visit a new place last summer?", pic: "plane" },
      { id: "a2-q-did-you-swim-in-the-sea", text: "Did you swim in the sea last year?", pic: "swimming" },
      { id: "a2-q-did-you-ride-a-bike-last", text: "Did you ride a bike last week?", pic: "bike" },
      { id: "a2-q-did-you-eat-an-apple-yesterday", text: "Did you eat an apple yesterday?", pic: "apple" },
      { id: "a2-q-did-you-forget-your-keys-this", text: "Did you forget your keys this week?", pic: "key" },
      { id: "a2-q-did-you-lose-an-umbrella-last", text: "Did you lose an umbrella last year?", pic: "umbrella" },
      { id: "a2-q-did-you-draw-a-picture-last", text: "Did you draw a picture last week?", pic: "pencil" },
      { id: "a2-q-did-you-make-a-cake-last", text: "Did you make a cake last year?", pic: "cake" },
      { id: "a2-q-did-you-see-a-rainbow-this", text: "Did you see a rainbow this year?", pic: "rainbow" },
      { id: "a2-q-did-you-go-to-the-park", text: "Did you go to the park yesterday?", pic: "park" },
      { id: "a2-q-did-you-drink-tea-yesterday", text: "Did you drink tea yesterday?", pic: "tea" },
      { id: "a2-q-did-you-play-a-video-game", text: "Did you play a video game today?", pic: "computer" },
      { id: "a2-q-did-you-watch-a-football-match", text: "Did you watch a football match last week?", pic: "football" },
      { id: "a2-q-did-you-eat-ice-cream-this", text: "Did you eat ice cream this week?", pic: "ice cream" }
    ],
    first: [
      { id: "a2-f-did-you-have-breakfast-today", text: "Did you have breakfast today?", pic: "bread" },
      { id: "a2-f-did-you-come-here-by-bus", text: "Did you come here by bus?", pic: "bus" },
      { id: "a2-f-did-you-watch-a-film-last", text: "Did you watch a film last weekend?", pic: "TV" },
      { id: "a2-f-did-you-listen-to-music-today", text: "Did you listen to music today?", pic: "guitar" },
      { id: "a2-f-did-you-walk-here-today", text: "Did you walk here today?", pic: "shoes" },
      { id: "a2-f-did-you-play-a-sport-last", text: "Did you play a sport last week?", pic: "ball" },
      { id: "a2-f-did-you-read-anything-yesterday", text: "Did you read anything yesterday?", pic: "book" },
      { id: "a2-f-did-you-drink-coffee-today", text: "Did you drink coffee today?", pic: "coffee" },
      { id: "a2-f-did-you-take-a-photo-today", text: "Did you take a photo today?", pic: "camera" },
      { id: "a2-f-did-you-go-shopping-last-weekend", text: "Did you go shopping last weekend?", pic: "shop" },
      { id: "a2-f-did-you-cook-yesterday", text: "Did you cook yesterday?", pic: "pan" },
      { id: "a2-f-did-you-sleep-well-last-night", text: "Did you sleep well last night?", pic: "bed" },
      { id: "a2-f-did-you-learn-english-at-school", text: "Did you learn English at school?", pic: "school" },
      { id: "a2-f-did-you-travel-last-summer", text: "Did you travel last summer?", pic: "plane" },
      { id: "a2-f-did-you-eat-something-sweet-today", text: "Did you eat something sweet today?", pic: "chocolate" }
    ]
  },
  /* ---------- 2. Pre-Intermediate (A2+) ---------- */
  {
    questions: [
      { id: "a2p-q-have-you-ever-been-on-a", text: "Have you ever been on a plane?", pic: "plane" },
      { id: "a2p-q-have-you-ever-seen-snow", text: "Have you ever seen snow?", pic: "snow" },
      { id: "a2p-q-have-you-ever-eaten-sushi", text: "Have you ever eaten sushi?", pic: "fish" },
      { id: "a2p-q-have-you-ever-met-a-famous", text: "Have you ever met a famous person?", pic: "star" },
      { id: "a2p-q-have-you-ever-been-on-tv", text: "Have you ever been on TV?", pic: "TV" },
      { id: "a2p-q-have-you-ever-climbed-a-mountain", text: "Have you ever climbed a mountain?", pic: "mountain" },
      { id: "a2p-q-have-you-ever-lost-your-phone", text: "Have you ever lost your phone?", pic: "phone" },
      { id: "a2p-q-have-you-ever-won-a-prize", text: "Have you ever won a prize?", pic: "present" },
      { id: "a2p-q-have-you-ever-slept-in-a", text: "Have you ever slept in a tent?", pic: "moon" },
      { id: "a2p-q-have-you-ever-cooked-for-ten", text: "Have you ever cooked for ten people?", pic: "pan" },
      { id: "a2p-q-have-you-ever-seen-a-whale", text: "Have you ever seen a whale?", pic: "whale" },
      { id: "a2p-q-have-you-ever-ridden-a-horse", text: "Have you ever ridden a horse?", pic: "horse" },
      { id: "a2p-q-have-you-ever-sung-karaoke", text: "Have you ever sung karaoke?", pic: "microphone" },
      { id: "a2p-q-have-you-ever-been-to-another", text: "Have you ever been to another country?", pic: "plane" },
      { id: "a2p-q-have-you-ever-broken-a-phone", text: "Have you ever broken a phone screen?", pic: "phone" },
      { id: "a2p-q-have-you-ever-fallen-asleep-in", text: "Have you ever fallen asleep in class?", pic: "bed" },
      { id: "a2p-q-have-you-ever-eaten-a-whole", text: "Have you ever eaten a whole pizza alone?", pic: "pizza" },
      { id: "a2p-q-have-you-ever-swum-in-a", text: "Have you ever swum in a lake?", pic: "swimming" },
      { id: "a2p-q-have-you-ever-written-a-poem", text: "Have you ever written a poem?", pic: "pen" },
      { id: "a2p-q-have-you-ever-been-in-a", text: "Have you ever been in a newspaper?", pic: "book" },
      { id: "a2p-q-have-you-ever-played-chess", text: "Have you ever played chess?", pic: "box" },
      { id: "a2p-q-have-you-ever-made-a-video", text: "Have you ever made a video?", pic: "camera" },
      { id: "a2p-q-have-you-ever-grown-a-plant", text: "Have you ever grown a plant?", pic: "flower" },
      { id: "a2p-q-have-you-ever-seen-a-shooting", text: "Have you ever seen a shooting star?", pic: "star" },
      { id: "a2p-q-have-you-ever-been-on-a-2", text: "Have you ever been on a boat?", pic: "boat" },
      { id: "a2p-q-have-you-ever-touched-a-snake", text: "Have you ever touched a snake?", pic: "snake" },
      { id: "a2p-q-have-you-ever-forgotten-a-friends", text: "Have you ever forgotten a friend's birthday?", pic: "cake" },
      { id: "a2p-q-have-you-ever-stayed-up-all", text: "Have you ever stayed up all night?", pic: "moon" },
      { id: "a2p-q-have-you-ever-eaten-an-insect", text: "Have you ever eaten an insect?", pic: "ant" },
      { id: "a2p-q-have-you-ever-built-a-snowman", text: "Have you ever built a snowman?", pic: "snowman" },
      { id: "a2p-q-have-you-ever-flown-a-kite", text: "Have you ever flown a kite?", pic: "kite" }
    ],
    first: [
      { id: "a2p-f-have-you-ever-been-to-the", text: "Have you ever been to the sea?", pic: "beach" },
      { id: "a2p-f-have-you-ever-seen-a-famous", text: "Have you ever seen a famous place?", pic: "camera" },
      { id: "a2p-f-have-you-ever-played-in-a", text: "Have you ever played in a band?", pic: "drum" },
      { id: "a2p-f-have-you-ever-tried-a-new", text: "Have you ever tried a new sport this year?", pic: "ball" },
      { id: "a2p-f-have-you-ever-eaten-food-from", text: "Have you ever eaten food from another country?", pic: "noodles" },
      { id: "a2p-f-have-you-ever-read-a-book", text: "Have you ever read a book in English?", pic: "book" },
      { id: "a2p-f-have-you-ever-watched-a-film", text: "Have you ever watched a film in English?", pic: "TV" },
      { id: "a2p-f-have-you-ever-been-to-a", text: "Have you ever been to a concert?", pic: "singer" },
      { id: "a2p-f-have-you-ever-travelled-by-train", text: "Have you ever travelled by train?", pic: "train" },
      { id: "a2p-f-have-you-ever-made-a-cake", text: "Have you ever made a cake?", pic: "cake" },
      { id: "a2p-f-have-you-ever-won-a-game", text: "Have you ever won a game?", pic: "star" },
      { id: "a2p-f-have-you-ever-been-on-a", text: "Have you ever been on a boat?", pic: "boat" },
      { id: "a2p-f-have-you-ever-seen-snow", text: "Have you ever seen snow?", pic: "snow" },
      { id: "a2p-f-have-you-ever-sung-in-public", text: "Have you ever sung in public?", pic: "microphone" },
      { id: "a2p-f-have-you-ever-had-a-pet", text: "Have you ever had a pet?", pic: "cat" }
    ]
  },
  /* ---------- 3. Intermediate (B1) ---------- */
  {
    questions: [
      { id: "b1-q-have-you-ever-got-lost-in", text: "Have you ever got lost in a city?" },
      { id: "b1-q-did-you-want-to-be-a", text: "Did you want to be a teacher when you were a child?" },
      { id: "b1-q-have-you-ever-cooked-something-that", text: "Have you ever cooked something that went badly wrong?" },
      { id: "b1-q-have-you-ever-stayed-awake-for", text: "Have you ever stayed awake for more than 24 hours?" },
      { id: "b1-q-have-you-ever-met-someone-with", text: "Have you ever met someone with the same name as you?" },
      { id: "b1-q-have-you-ever-missed-a-plane", text: "Have you ever missed a plane or a train?" },
      { id: "b1-q-did-you-learn-to-swim-before", text: "Did you learn to swim before you were six?" },
      { id: "b1-q-have-you-ever-found-something-interesting", text: "Have you ever found something interesting on the street?" },
      { id: "b1-q-have-you-ever-been-in-a", text: "Have you ever been in a TV audience?" },
      { id: "b1-q-have-you-ever-taken-part-in", text: "Have you ever taken part in a competition?" },
      { id: "b1-q-have-you-ever-read-a-book", text: "Have you ever read a book in one day?" },
      { id: "b1-q-did-you-have-a-strange-hobby", text: "Did you have a strange hobby as a child?" },
      { id: "b1-q-have-you-ever-eaten-something-really", text: "Have you ever eaten something really strange?" },
      { id: "b1-q-have-you-ever-walked-more-than", text: "Have you ever walked more than 20 kilometres in one day?" },
      { id: "b1-q-have-you-ever-been-stuck-in", text: "Have you ever been stuck in a lift?" },
      { id: "b1-q-have-you-ever-given-a-speech", text: "Have you ever given a speech to a big audience?" },
      { id: "b1-q-did-you-ever-break-a-window", text: "Did you ever break a window as a child?" },
      { id: "b1-q-have-you-ever-seen-a-famous", text: "Have you ever seen a famous band live?" },
      { id: "b1-q-have-you-ever-tried-an-extreme", text: "Have you ever tried an extreme sport?" },
      { id: "b1-q-have-you-ever-been-to-a", text: "Have you ever been to a festival in another country?" },
      { id: "b1-q-have-you-ever-made-a-mistake", text: "Have you ever made a mistake in a presentation?" },
      { id: "b1-q-have-you-ever-slept-outside-under", text: "Have you ever slept outside under the stars?" },
      { id: "b1-q-did-you-ever-win-a-prize", text: "Did you ever win a prize at school?" },
      { id: "b1-q-have-you-ever-had-a-conversation", text: "Have you ever had a conversation with a celebrity?" },
      { id: "b1-q-have-you-ever-spent-a-whole", text: "Have you ever spent a whole day without your phone?" },
      { id: "b1-q-have-you-ever-learned-to-play", text: "Have you ever learned to play an instrument?" },
      { id: "b1-q-have-you-ever-been-on-the", text: "Have you ever been on the radio?" },
      { id: "b1-q-have-you-ever-cooked-a-meal", text: "Have you ever cooked a meal for more than ten people?" },
      { id: "b1-q-have-you-ever-seen-the-northern", text: "Have you ever seen the northern lights?" },
      { id: "b1-q-have-you-ever-overslept-on-the", text: "Have you ever overslept on the day of an exam?" },
      { id: "b1-q-have-you-ever-driven-a-car", text: "Have you ever driven a car?" }
    ],
    first: [
      { id: "b1-f-have-you-ever-lived-in-another", text: "Have you ever lived in another city?" },
      { id: "b1-f-have-you-ever-learned-another-language", text: "Have you ever learned another language apart from English?" },
      { id: "b1-f-did-you-enjoy-school-when-you", text: "Did you enjoy school when you were a child?" },
      { id: "b1-f-have-you-ever-been-to-a", text: "Have you ever been to a big concert?" },
      { id: "b1-f-have-you-ever-cooked-a-dish", text: "Have you ever cooked a dish from another country?" },
      { id: "b1-f-did-you-have-a-favourite-cartoon", text: "Did you have a favourite cartoon as a child?" },
      { id: "b1-f-have-you-ever-travelled-alone", text: "Have you ever travelled alone?" },
      { id: "b1-f-have-you-ever-run-a-race", text: "Have you ever run a race?" },
      { id: "b1-f-have-you-ever-met-someone-famous", text: "Have you ever met someone famous?" },
      { id: "b1-f-have-you-ever-read-a-book", text: "Have you ever read a book twice?" },
      { id: "b1-f-did-you-play-a-musical-instrument", text: "Did you play a musical instrument as a child?" },
      { id: "b1-f-have-you-ever-stayed-up-to", text: "Have you ever stayed up to watch the sunrise?" },
      { id: "b1-f-have-you-ever-visited-a-museum", text: "Have you ever visited a museum abroad?" },
      { id: "b1-f-have-you-ever-made-something-with", text: "Have you ever made something with your hands that you're proud of?" },
      { id: "b1-f-have-you-ever-been-on-a", text: "Have you ever been on a long train journey?" }
    ]
  },
  /* ---------- 4. IELTS 1 (B2) ---------- */
  {
    questions: [
      { id: "i1-q-do-you-think-you-could-live", text: "Do you think you could live without your phone for a week?" },
      { id: "i1-q-would-you-rather-live-in-a", text: "Would you rather live in a big city than a small town?" },
      { id: "i1-q-have-you-ever-changed-your-opinion", text: "Have you ever changed your opinion about a film after watching it twice?" },
      { id: "i1-q-do-you-prefer-reading-books-to", text: "Do you prefer reading books to watching films?" },
      { id: "i1-q-have-you-ever-taught-yourself-a", text: "Have you ever taught yourself a skill from online videos?" },
      { id: "i1-q-do-you-think-you-are-a", text: "Do you think you are a good cook?" },
      { id: "i1-q-have-you-ever-volunteered-for-something", text: "Have you ever volunteered for something?" },
      { id: "i1-q-would-you-enjoy-living-abroad-for", text: "Would you enjoy living abroad for a year?" },
      { id: "i1-q-do-you-think-homework-is-useful", text: "Do you think homework is useful?" },
      { id: "i1-q-have-you-ever-given-a-presentation", text: "Have you ever given a presentation in English?" },
      { id: "i1-q-do-you-think-you-are-better", text: "Do you think you are better at speaking than writing?" },
      { id: "i1-q-have-you-ever-been-interviewed-for", text: "Have you ever been interviewed for something?" },
      { id: "i1-q-would-you-choose-a-quiet-holiday", text: "Would you choose a quiet holiday over an exciting one?" },
      { id: "i1-q-do-you-think-video-games-can", text: "Do you think video games can be educational?" },
      { id: "i1-q-have-you-ever-organised-a-big", text: "Have you ever organised a big event?" },
      { id: "i1-q-do-you-prefer-working-alone-to", text: "Do you prefer working alone to working in a team?" },
      { id: "i1-q-have-you-ever-started-learning-an", text: "Have you ever started learning an instrument and given up?" },
      { id: "i1-q-do-you-think-you-would-be", text: "Do you think you would be a good teacher?" },
      { id: "i1-q-have-you-ever-eaten-a-dish", text: "Have you ever eaten a dish you couldn't pronounce?" },
      { id: "i1-q-would-you-like-to-be-famous", text: "Would you like to be famous?" },
      { id: "i1-q-have-you-ever-tried-to-break", text: "Have you ever tried to break a world record?" },
      { id: "i1-q-do-you-think-people-read-less", text: "Do you think people read less than they used to?" },
      { id: "i1-q-have-you-ever-planted-a-tree", text: "Have you ever planted a tree?" },
      { id: "i1-q-are-you-more-of-an-early", text: "Are you more of an early bird than a night owl?" },
      { id: "i1-q-have-you-ever-travelled-somewhere-just", text: "Have you ever travelled somewhere just to see one thing?" },
      { id: "i1-q-would-you-prefer-to-work-from", text: "Would you prefer to work from home?" },
      { id: "i1-q-do-you-think-you-could-survive", text: "Do you think you could survive a week in the wilderness?" },
      { id: "i1-q-have-you-ever-written-a-review", text: "Have you ever written a review online?" },
      { id: "i1-q-do-you-believe-first-impressions-are", text: "Do you believe first impressions are usually right?" },
      { id: "i1-q-have-you-ever-had-a-job", text: "Have you ever had a job you really enjoyed?" },
      { id: "i1-q-do-you-enjoy-public-speaking", text: "Do you enjoy public speaking?" }
    ],
    first: [
      { id: "i1-f-do-you-enjoy-learning-languages", text: "Do you enjoy learning languages?" },
      { id: "i1-f-would-you-rather-visit-a-museum", text: "Would you rather visit a museum than a beach?" },
      { id: "i1-f-do-you-prefer-mornings-to-evenings", text: "Do you prefer mornings to evenings?" },
      { id: "i1-f-have-you-ever-travelled-somewhere-just", text: "Have you ever travelled somewhere just for the food?" },
      { id: "i1-f-do-you-think-you-are-a", text: "Do you think you are a creative person?" },
      { id: "i1-f-would-you-like-to-live-in", text: "Would you like to live in another country one day?" },
      { id: "i1-f-do-you-enjoy-cooking", text: "Do you enjoy cooking?" },
      { id: "i1-f-have-you-ever-taken-an-online", text: "Have you ever taken an online course?" },
      { id: "i1-f-do-you-prefer-films-to-series", text: "Do you prefer films to series?" },
      { id: "i1-f-do-you-think-you-are-a-2", text: "Do you think you are a patient person?" },
      { id: "i1-f-have-you-tried-a-new-hobby", text: "Have you tried a new hobby this year?" },
      { id: "i1-f-would-you-rather-read-the-book", text: "Would you rather read the book than watch the film?" },
      { id: "i1-f-do-you-like-working-in-groups", text: "Do you like working in groups?" },
      { id: "i1-f-have-you-ever-learned-a-skill", text: "Have you ever learned a skill from a video?" },
      { id: "i1-f-do-you-usually-plan-your-weekends", text: "Do you usually plan your weekends?" }
    ]
  },
  /* ---------- 5. IELTS 2 (band 6.0) ---------- */
  {
    questions: [
      { id: "i2-q-do-you-believe-technology-has-made", text: "Do you believe technology has made you more productive?" },
      { id: "i2-q-have-you-ever-changed-your-mind", text: "Have you ever changed your mind about what you wanted to study?" },
      { id: "i2-q-would-you-give-up-social-media", text: "Would you give up social media for a year if it helped your studies?" },
      { id: "i2-q-do-you-think-you-learn-more", text: "Do you think you learn more from failure than from success?" },
      { id: "i2-q-have-you-ever-persuaded-someone-to", text: "Have you ever persuaded someone to change an important decision?" },
      { id: "i2-q-do-you-think-tourism-does-more", text: "Do you think tourism does more good than harm to your city?" },
      { id: "i2-q-have-you-ever-been-part-of", text: "Have you ever been part of a team that failed but learned a lot?" },
      { id: "i2-q-would-you-rather-have-a-job", text: "Would you rather have a job with more free time or more responsibility?" },
      { id: "i2-q-do-you-think-schools-should-teach", text: "Do you think schools should teach cooking?" },
      { id: "i2-q-have-you-ever-had-to-adapt", text: "Have you ever had to adapt quickly to a completely new situation?" },
      { id: "i2-q-do-you-think-advertising-influences-what", text: "Do you think advertising influences what you choose?" },
      { id: "i2-q-have-you-ever-learned-something-important", text: "Have you ever learned something important from a much younger person?" },
      { id: "i2-q-would-you-prefer-to-study-online", text: "Would you prefer to study online rather than in a classroom?" },
      { id: "i2-q-do-you-think-public-transport-in", text: "Do you think public transport in your city is good enough?" },
      { id: "i2-q-have-you-ever-disagreed-with-a", text: "Have you ever disagreed with a teacher and been proved right?" },
      { id: "i2-q-do-you-think-people-are-more", text: "Do you think people are more creative in the morning?" },
      { id: "i2-q-have-you-ever-taken-a-risk", text: "Have you ever taken a risk that really paid off?" },
      { id: "i2-q-would-you-be-happy-without-a", text: "Would you be happy without a car for the rest of your life?" },
      { id: "i2-q-do-you-think-famous-athletes-are", text: "Do you think famous athletes are good role models?" },
      { id: "i2-q-have-you-ever-read-a-book", text: "Have you ever read a book that changed the way you think?" },
      { id: "i2-q-do-you-think-young-people-read", text: "Do you think young people read more than older generations did?" },
      { id: "i2-q-have-you-ever-started-a-project", text: "Have you ever started a project you never finished?" },
      { id: "i2-q-would-you-choose-an-interesting-job", text: "Would you choose an interesting job over an easy one?" },
      { id: "i2-q-do-you-think-handwriting-is-still", text: "Do you think handwriting is still important?" },
      { id: "i2-q-have-you-ever-organised-a-trip", text: "Have you ever organised a trip for a group?" },
      { id: "i2-q-do-you-believe-you-are-good", text: "Do you believe you are good at managing your time?" },
      { id: "i2-q-have-you-ever-been-surprised-by", text: "Have you ever been surprised by a place you didn't expect to like?" },
      { id: "i2-q-do-you-think-space-exploration-is", text: "Do you think space exploration is worth the effort?" },
      { id: "i2-q-have-you-ever-tried-to-reduce", text: "Have you ever tried to reduce the waste you produce?" },
      { id: "i2-q-do-you-think-its-better-to", text: "Do you think it's better to be a specialist than a generalist?" },
      { id: "i2-q-would-you-enjoy-being-a-tour", text: "Would you enjoy being a tour guide in your city?" }
    ],
    first: [
      { id: "i2-f-do-you-enjoy-trying-new-things", text: "Do you enjoy trying new things more than repeating old favourites?" },
      { id: "i2-f-would-you-rather-learn-a-new", text: "Would you rather learn a new language than a musical instrument?" },
      { id: "i2-f-have-you-ever-given-someone-advice", text: "Have you ever given someone advice that really helped them?" },
      { id: "i2-f-do-you-think-you-are-good", text: "Do you think you are good at remembering names?" },
      { id: "i2-f-have-you-ever-travelled-to-a", text: "Have you ever travelled to a place that surprised you?" },
      { id: "i2-f-do-you-prefer-planning-to-improvising", text: "Do you prefer planning to improvising?" },
      { id: "i2-f-would-you-like-to-work-for", text: "Would you like to work for an international company?" },
      { id: "i2-f-have-you-ever-learned-a-skill", text: "Have you ever learned a skill completely on your own?" },
      { id: "i2-f-are-you-more-of-a-listener", text: "Are you more of a listener than a talker?" },
      { id: "i2-f-have-you-ever-changed-a-habit", text: "Have you ever changed a habit successfully?" },
      { id: "i2-f-do-you-prefer-city-holidays-to", text: "Do you prefer city holidays to nature holidays?" },
      { id: "i2-f-would-you-enjoy-teaching-your-own", text: "Would you enjoy teaching your own language to foreigners?" },
      { id: "i2-f-have-you-ever-read-the-same", text: "Have you ever read the same book in two languages?" },
      { id: "i2-f-do-you-think-you-are-a", text: "Do you think you are a competitive person?" },
      { id: "i2-f-have-you-ever-taken-part-in", text: "Have you ever taken part in a debate?" }
    ]
  },
  /* ---------- 6. IELTS 3 (band 7.0+) ---------- */
  {
    questions: [
      { id: "i3-q-do-you-think-convenience-has-made", text: "Do you think convenience has made people less patient?" },
      { id: "i3-q-have-you-ever-defended-an-opinion", text: "Have you ever defended an opinion you didn't actually hold, just for the argument?" },
      { id: "i3-q-would-you-give-up-some-privacy", text: "Would you give up some privacy for a more efficient city?" },
      { id: "i3-q-do-you-believe-talent-matters-less", text: "Do you believe talent matters less than persistence?" },
      { id: "i3-q-have-you-ever-stepped-outside-your", text: "Have you ever stepped outside your comfort zone for a whole month?" },
      { id: "i3-q-do-you-think-art-should-be", text: "Do you think art should be judged by its intention rather than its effect?" },
      { id: "i3-q-have-you-ever-realised-that-a", text: "Have you ever realised that a strongly held belief of yours was wrong?" },
      { id: "i3-q-would-you-accept-a-brilliant-job", text: "Would you accept a brilliant job in a country whose language you don't speak?" },
      { id: "i3-q-do-you-think-traditions-should-be", text: "Do you think traditions should be kept even when they become impractical?" },
      { id: "i3-q-have-you-ever-changed-someones-mind", text: "Have you ever changed someone's mind using only evidence?" },
      { id: "i3-q-do-you-think-the-internet-has", text: "Do you think the internet has made people more curious?" },
      { id: "i3-q-have-you-ever-made-a-decision", text: "Have you ever made a decision purely on intuition that turned out well?" },
      { id: "i3-q-would-you-be-willing-to-live", text: "Would you be willing to live without any screens for a month?" },
      { id: "i3-q-do-you-believe-that-most-success", text: "Do you believe that most success is due to luck?" },
      { id: "i3-q-have-you-ever-mentored-someone", text: "Have you ever mentored someone?" },
      { id: "i3-q-do-you-think-cities-should-ban", text: "Do you think cities should ban cars from their centres?" },
      { id: "i3-q-have-you-ever-taken-on-a", text: "Have you ever taken on a responsibility you felt unready for?" },
      { id: "i3-q-do-you-think-its-possible-to", text: "Do you think it's possible to be truly objective?" },
      { id: "i3-q-have-you-ever-learned-more-from", text: "Have you ever learned more from a book than from a course?" },
      { id: "i3-q-would-you-prefer-to-be-remembered", text: "Would you prefer to be remembered for kindness rather than achievement?" },
      { id: "i3-q-do-you-think-machines-will-ever", text: "Do you think machines will ever write better novels than humans?" },
      { id: "i3-q-have-you-ever-deliberately-avoided-the", text: "Have you ever deliberately avoided the news for a long time?" },
      { id: "i3-q-do-you-think-competition-brings-out", text: "Do you think competition brings out the best in people?" },
      { id: "i3-q-have-you-ever-had-to-give", text: "Have you ever had to give critical feedback to someone you admire?" },
      { id: "i3-q-would-you-want-to-know-the", text: "Would you want to know the future if you could?" },
      { id: "i3-q-do-you-think-learning-a-language", text: "Do you think learning a language changes the way you think?" },
      { id: "i3-q-have-you-ever-walked-away-from", text: "Have you ever walked away from something you'd worked hard for?" },
      { id: "i3-q-do-you-believe-that-boredom-can", text: "Do you believe that boredom can be useful?" },
      { id: "i3-q-have-you-ever-been-the-only", text: "Have you ever been the only person in a group to disagree?" },
      { id: "i3-q-do-you-think-fame-is-more", text: "Do you think fame is more of a burden than a privilege?" },
      { id: "i3-q-would-you-rather-be-an-expert", text: "Would you rather be an expert in one field than good at many things?" }
    ],
    first: [
      { id: "i3-f-are-you-more-rational-than-emotional", text: "Are you more rational than emotional when you make decisions?" },
      { id: "i3-f-have-you-ever-had-an-idea", text: "Have you ever had an idea you were sure was original but wasn't?" },
      { id: "i3-f-would-you-rather-explore-the-deep", text: "Would you rather explore the deep sea than outer space?" },
      { id: "i3-f-do-you-believe-you-could-master", text: "Do you believe you could master a new language in a year?" },
      { id: "i3-f-have-you-ever-changed-your-mind", text: "Have you ever changed your mind about a book after rereading it?" },
      { id: "i3-f-do-you-work-better-under-pressure", text: "Do you work better under pressure?" },
      { id: "i3-f-would-you-choose-a-quiet-life", text: "Would you choose a quiet life over an adventurous one?" },
      { id: "i3-f-have-you-ever-taught-yourself-something", text: "Have you ever taught yourself something really difficult?" },
      { id: "i3-f-do-you-believe-first-impressions-are", text: "Do you believe first impressions are reliable?" },
      { id: "i3-f-have-you-ever-travelled-somewhere-purely", text: "Have you ever travelled somewhere purely out of curiosity?" },
      { id: "i3-f-do-you-enjoy-arguing-for-the", text: "Do you enjoy arguing for the sake of it?" },
      { id: "i3-f-would-you-like-to-live-in", text: "Would you like to live in a different century?" },
      { id: "i3-f-have-you-ever-started-a-conversation", text: "Have you ever started a conversation with a complete stranger abroad?" },
      { id: "i3-f-do-you-think-you-are-a", text: "Do you think you are a good judge of character?" },
      { id: "i3-f-have-you-ever-turned-a-hobby", text: "Have you ever turned a hobby into something more serious?" }
    ]
  }
];

/* Screen text for Lie Detector, per level. Editable in Edit mode. Empty text hides a line. {name}, {a}, {b}, {n} are filled in.
   followers = classmates who ask a follow-up question; explainers = students who say why they think it's a lie. */
WU.content.lieScreen = {
  shared: {
    id: 'lie-screen',
    tag: 'LIE DETECTOR', who: "Who's in the chair?", qMark: '?',
    signal: 'Show the teacher secretly: TRUTH or LIE?', signalShow: true,
    frame: '', rule: 'Answer the question. True or not?', ruleShow: true,
    followers: 1, followTag: 'FOLLOW-UP', follow: '{a}: ask {name} one more question!',
    explainers: 0, explain: '{a} and {b}: why do you think it is a lie?',
    vote: 'Vote! Stand up = LIE. Stay seated = TRUTH.', votes: 'Lie votes: {n}',
    scanning: 'ANALYSING...', truth: 'TRUTH', lie: 'LIE!', right: 'The class was right!', wrong: 'The class was fooled!',
    demo: 'TEACHER DEMO: I answer first!', demoShow: false, demoWho: 'TEACHER'
  },
  levels: [
    { frame: "Yes, I do. / No, I don't.", rule: 'Answer: yes or no.', vote: 'Class, say: "True!" or "Lie!"', followers: 0, demoShow: true },
    { frame: "Yes, I did. / No, I didn't." },
    { frame: "Yes, I have. / No, I haven't." },
    {},
    { followers: 0, explainers: 2, rule: 'Answer and give details. Make it believable!' },
    { followers: 0, explainers: 2, rule: 'Answer and give details. Make it believable!' },
    { followers: 0, explainers: 2, rule: 'Answer and give details. Make it believable!' }
  ]
};
