/* Warm Up: content for SLOT MACHINE OF CHAOS. Generated with a permanent id on every item.
   One entry per level: A1, A2, A2+, B1, IELTS 1 (B2), IELTS 2 (6.0), IELTS 3 (7.0+).
   topics / first : TOPIC reel (first = First lesson mode, get-to-know-you). { id, text, pic, frame }
                    frame = this topic's own sentence frame; none = the level frame (slotScreen).
   styles         : HOW reel. They change only HOW you speak. { id, text, sub, pic }
   twists         : TWIST reel (on from Intermediate). { id, text, sub }
   id is PERMANENT: teacher edits (Edit mode) point at it. Never change or reuse an id. */
window.WU = window.WU || {}; WU.content = WU.content || {};
WU.content.slot = [
  /* ---------- 0. Beginner (A1) ---------- */
  {
    topics: [
      { id: "a1-t-food-i-like", text: "Food I like", pic: "pizza" },
      { id: "a1-t-animals-i-like", text: "Animals I like", pic: "cat" },
      { id: "a1-t-my-family", text: "My family", pic: "family", frame: "I have ___. My ___ is nice." },
      { id: "a1-t-my-bag", text: "My bag", pic: "bag", frame: "I have ___ in my bag." },
      { id: "a1-t-my-home", text: "My home", pic: "house", frame: "I have ___ in my home." },
      { id: "a1-t-my-room", text: "My room", pic: "bed", frame: "I have ___ in my room." },
      { id: "a1-t-colours-i-like", text: "Colours I like", pic: "c-blue" },
      { id: "a1-t-sports-i-like", text: "Sports I like", pic: "football" },
      { id: "a1-t-drinks-i-like", text: "Drinks I like", pic: "juice" },
      { id: "a1-t-fruit-i-like", text: "Fruit I like", pic: "apple" },
      { id: "a1-t-my-clothes", text: "My clothes", pic: "T-shirt", frame: "I have ___." },
      { id: "a1-t-my-school", text: "My school", pic: "school", frame: "I have ___ at school." },
      { id: "a1-t-my-friends", text: "My friends", pic: "family", frame: "My friend is ___. He / She likes ___." },
      { id: "a1-t-my-teacher", text: "My teacher", pic: "teacher", frame: "My teacher is ___." },
      { id: "a1-t-my-city", text: "My city", pic: "city", frame: "I live in ___. I like ___." },
      { id: "a1-t-breakfast", text: "Breakfast", pic: "egg" },
      { id: "a1-t-toys", text: "Toys", pic: "teddy bear" },
      { id: "a1-t-music", text: "Music", pic: "guitar" },
      { id: "a1-t-the-weather-today", text: "The weather today", pic: "sun", frame: "It's ___ today." },
      { id: "a1-t-my-pet", text: "My pet", pic: "dog", frame: "I have ___. It is ___." },
      { id: "a1-t-transport", text: "Transport", pic: "bus", frame: "I go to school by ___." },
      { id: "a1-t-my-phone", text: "My phone", pic: "phone", frame: "My phone is ___." },
      { id: "a1-t-the-park", text: "The park", pic: "park", frame: "In the park I see ___." },
      { id: "a1-t-the-beach", text: "The beach", pic: "beach", frame: "At the beach I like ___." },
      { id: "a1-t-birthdays", text: "Birthdays", pic: "cake", frame: "On my birthday I like ___." },
      { id: "a1-t-jobs", text: "Jobs", pic: "doctor", frame: "I want to be ___." },
      { id: "a1-t-my-face", text: "My face", pic: "face", frame: "I have ___ eyes." },
      { id: "a1-t-vegetables", text: "Vegetables", pic: "carrot" },
      { id: "a1-t-sweets", text: "Sweets", pic: "sweets" },
      { id: "a1-t-my-weekend", text: "My weekend", pic: "ball", frame: "At the weekend I like ___." },
      { id: "a1-t-winter", text: "Winter", pic: "snowman", frame: "In winter I like ___." },
      { id: "a1-t-summer", text: "Summer", pic: "sun", frame: "In summer I like ___." },
      { id: "a1-t-zoo-animals", text: "Zoo animals", pic: "lion" },
      { id: "a1-t-farm-animals", text: "Farm animals", pic: "cow" },
      { id: "a1-t-the-sea", text: "The sea", pic: "fish", frame: "In the sea I see ___." },
      { id: "a1-t-books", text: "Books", pic: "book" },
      { id: "a1-t-tv", text: "TV", pic: "TV", frame: "I like ___ on TV." },
      { id: "a1-t-computers", text: "Computers", pic: "computer", frame: "I have ___. I like ___." },
      { id: "a1-t-cars", text: "Cars", pic: "car", frame: "I like ___ cars." },
      { id: "a1-t-shoes", text: "Shoes", pic: "shoes", frame: "I have ___ shoes." },
      { id: "a1-t-hot-food", text: "Hot food", pic: "soup" },
      { id: "a1-t-cold-food", text: "Cold food", pic: "ice cream" },
      { id: "a1-t-my-desk", text: "My desk", pic: "desk", frame: "I have ___ on my desk." },
      { id: "a1-t-holidays", text: "Holidays", pic: "plane", frame: "On holiday I like ___." }
    ],
    first: [
      { id: "a1-f-my-name", text: "My name", pic: "face", frame: "My name is ___." },
      { id: "a1-f-my-age", text: "My age", pic: "cake", frame: "I'm ___." },
      { id: "a1-f-my-family", text: "My family", pic: "family", frame: "I have ___." },
      { id: "a1-f-food-i-like", text: "Food I like", pic: "pizza" },
      { id: "a1-f-colours-i-like", text: "Colours I like", pic: "c-red" },
      { id: "a1-f-animals-i-like", text: "Animals I like", pic: "dog" },
      { id: "a1-f-my-bag", text: "My bag", pic: "bag", frame: "I have ___ in my bag." },
      { id: "a1-f-sports-i-like", text: "Sports I like", pic: "football" },
      { id: "a1-f-drinks-i-like", text: "Drinks I like", pic: "juice" },
      { id: "a1-f-my-city", text: "My city", pic: "city", frame: "I live in ___." },
      { id: "a1-f-music-i-like", text: "Music I like", pic: "guitar" },
      { id: "a1-f-my-favourite-toy", text: "My favourite toy", pic: "teddy bear", frame: "My favourite toy is ___." }
    ],
    styles: [
      { id: "a1-s-normal", text: "Normal", sub: "Talk normally.", pic: "face" },
      { id: "a1-s-slowly", text: "Slowly", sub: "Talk slowly.", pic: "turtle" },
      { id: "a1-s-very-slowly", text: "Very slowly", sub: "Very... very... slowly.", pic: "turtle" },
      { id: "a1-s-fast", text: "Fast", sub: "Talk fast.", pic: "rocket" },
      { id: "a1-s-very-fast", text: "Very fast", sub: "Very, very fast!", pic: "rocket" },
      { id: "a1-s-whisper", text: "Whisper", sub: "Talk very quietly.", pic: "ear" },
      { id: "a1-s-quietly", text: "Quietly", sub: "A quiet voice.", pic: "ear" },
      { id: "a1-s-loud-voice", text: "Loud voice", sub: "A big voice!", pic: "microphone" },
      { id: "a1-s-happy-voice", text: "Happy voice", sub: "Happy!", pic: "face" },
      { id: "a1-s-sad-voice", text: "Sad voice", sub: "Sad...", pic: "face" },
      { id: "a1-s-surprised-voice", text: "Surprised voice", sub: "Wow!", pic: "face" },
      { id: "a1-s-bored-voice", text: "Bored voice", sub: "Boring...", pic: "face" },
      { id: "a1-s-sleepy-voice", text: "Sleepy voice", sub: "So sleepy...", pic: "bed" },
      { id: "a1-s-angry-voice", text: "Angry voice", sub: "Grrr!", pic: "face" },
      { id: "a1-s-like-a-teacher", text: "Like a teacher", sub: "OK, class!", pic: "teacher" },
      { id: "a1-s-with-please", text: "With \"please\"", sub: "Say \"please\".", pic: "heart" },
      { id: "a1-s-with-and", text: "With \"and\"", sub: "Say \"and... and...\"", pic: "star" },
      { id: "a1-s-question-at-the-end", text: "Question at the end", sub: "\"...do you like it?\"", pic: "face" },
      { id: "a1-s-like-on-the-phone", text: "Like on the phone", sub: "\"Hello?\"", pic: "phone" },
      { id: "a1-s-like-a-secret", text: "Like a secret", sub: "Shh... a secret.", pic: "ear" }
    ],
    twists: [
      { id: "a1-w-use-unfortunately", text: "Use \"unfortunately\"", sub: "Say it at least once." },
      { id: "a1-w-include-a-number", text: "Include a number", sub: "Any number." },
      { id: "a1-w-use-a-conditional", text: "Use a conditional", sub: "\"If ..., I would ...\"" },
      { id: "a1-w-ask-the-class-a-question", text: "Ask the class a question", sub: "Wait for one answer." },
      { id: "a1-w-use-however", text: "Use \"however\"", sub: "Say it at least once." },
      { id: "a1-w-mention-a-colour", text: "Mention a colour", sub: "Any colour." },
      { id: "a1-w-include-a-time-or-a-date", text: "Include a time or a date", sub: "\"At 7 o'clock...\"" },
      { id: "a1-w-past-tense-only", text: "Past tense only", sub: "Everything happened yesterday." },
      { id: "a1-w-mention-a-famous-person", text: "Mention a famous person", sub: "Anyone famous." },
      { id: "a1-w-use-three-adjectives", text: "Use three adjectives", sub: "Count them!" },
      { id: "a1-w-end-with-a-surprise", text: "End with a surprise", sub: "Something nobody expects." },
      { id: "a1-w-use-never", text: "Use \"never\"", sub: "Say it at least once." },
      { id: "a1-w-compare-two-things", text: "Compare two things", sub: "\"... is better than ...\"" },
      { id: "a1-w-include-a-feeling", text: "Include a feeling", sub: "\"I felt...\"" },
      { id: "a1-w-use-because-twice", text: "Use \"because\" twice", sub: "Give two reasons." }
    ]
  },
  /* ---------- 1. Elementary (A2) ---------- */
  {
    topics: [
      { id: "a2-t-my-last-holiday", text: "My last holiday" },
      { id: "a2-t-my-best-friend", text: "My best friend" },
      { id: "a2-t-what-i-did-yesterday", text: "What I did yesterday" },
      { id: "a2-t-my-plans-for-the-weekend", text: "My plans for the weekend" },
      { id: "a2-t-my-favourite-food", text: "My favourite food" },
      { id: "a2-t-my-hometown", text: "My hometown" },
      { id: "a2-t-my-morning-routine", text: "My morning routine" },
      { id: "a2-t-a-good-film", text: "A good film" },
      { id: "a2-t-my-favourite-place", text: "My favourite place" },
      { id: "a2-t-my-family", text: "My family" },
      { id: "a2-t-my-house", text: "My house" },
      { id: "a2-t-a-famous-person-i-like", text: "A famous person I like" },
      { id: "a2-t-my-favourite-day-of-the-week", text: "My favourite day of the week" },
      { id: "a2-t-animals-i-like", text: "Animals I like" },
      { id: "a2-t-my-school", text: "My school" },
      { id: "a2-t-sports", text: "Sports" },
      { id: "a2-t-music-i-like", text: "Music I like" },
      { id: "a2-t-my-phone", text: "My phone" },
      { id: "a2-t-my-favourite-season", text: "My favourite season" },
      { id: "a2-t-shopping", text: "Shopping" },
      { id: "a2-t-a-birthday-i-remember", text: "A birthday I remember" },
      { id: "a2-t-my-dream-job", text: "My dream job" },
      { id: "a2-t-things-in-my-bag", text: "Things in my bag" },
      { id: "a2-t-cooking", text: "Cooking" },
      { id: "a2-t-my-neighbourhood", text: "My neighbourhood" },
      { id: "a2-t-games", text: "Games" },
      { id: "a2-t-clothes-i-like", text: "Clothes I like" },
      { id: "a2-t-transport-in-my-city", text: "Transport in my city" },
      { id: "a2-t-breakfast", text: "Breakfast" },
      { id: "a2-t-my-dream-pet", text: "My dream pet" },
      { id: "a2-t-weekends", text: "Weekends" },
      { id: "a2-t-my-favourite-teacher", text: "My favourite teacher" },
      { id: "a2-t-tv-shows", text: "TV shows" },
      { id: "a2-t-books", text: "Books" },
      { id: "a2-t-holidays-in-my-country", text: "Holidays in my country" },
      { id: "a2-t-winter", text: "Winter" },
      { id: "a2-t-summer", text: "Summer" },
      { id: "a2-t-my-room", text: "My room" },
      { id: "a2-t-my-street", text: "My street" },
      { id: "a2-t-food-from-my-country", text: "Food from my country" }
    ],
    first: [
      { id: "a2-f-about-me", text: "About me" },
      { id: "a2-f-my-hometown", text: "My hometown" },
      { id: "a2-f-my-hobbies", text: "My hobbies" },
      { id: "a2-f-my-family", text: "My family" },
      { id: "a2-f-my-favourite-food", text: "My favourite food" },
      { id: "a2-f-my-weekend", text: "My weekend" },
      { id: "a2-f-my-job-or-my-school", text: "My job or my school" },
      { id: "a2-f-places-i-like", text: "Places I like" },
      { id: "a2-f-music-i-like", text: "Music I like" },
      { id: "a2-f-my-best-friend", text: "My best friend" },
      { id: "a2-f-why-im-learning-english", text: "Why I'm learning English" },
      { id: "a2-f-my-perfect-day", text: "My perfect day" }
    ],
    styles: [
      { id: "a2-s-normal", text: "Normal", sub: "Just talk normally." },
      { id: "a2-s-very-slowly", text: "Very slowly", sub: "Every... word... slowly." },
      { id: "a2-s-very-fast", text: "Very fast", sub: "As fast as you can." },
      { id: "a2-s-whispering", text: "Whispering", sub: "Everyone must listen!" },
      { id: "a2-s-telling-a-secret", text: "Telling a secret", sub: "Quietly, as if it is a big secret." },
      { id: "a2-s-news-reporter", text: "News reporter", sub: "Good evening. Breaking news..." },
      { id: "a2-s-tour-guide", text: "Tour guide", sub: "On your left, you can see..." },
      { id: "a2-s-question-at-the-end", text: "Question at the end", sub: "Finish with a question for the class." },
      { id: "a2-s-sports-commentator", text: "Sports commentator", sub: "And here we go...!" },
      { id: "a2-s-very-happy-voice", text: "Very happy voice", sub: "Everything is wonderful!" },
      { id: "a2-s-very-sad-voice", text: "Very sad voice", sub: "Oh no..." },
      { id: "a2-s-very-surprised", text: "Very surprised", sub: "Really?! Wow!" },
      { id: "a2-s-very-bored", text: "Very bored", sub: "Soooo boring..." },
      { id: "a2-s-like-a-teacher", text: "Like a teacher", sub: "OK class, listen..." },
      { id: "a2-s-weather-forecaster", text: "Weather forecaster", sub: "Today it will be..." },
      { id: "a2-s-radio-dj", text: "Radio DJ", sub: "You're listening to..." },
      { id: "a2-s-like-an-advert", text: "Like an advert", sub: "Buy it now!" },
      { id: "a2-s-very-politely", text: "Very politely", sub: "If I may say..." },
      { id: "a2-s-storyteller", text: "Storyteller", sub: "Once upon a time..." },
      { id: "a2-s-exactly-3-sentences", text: "Exactly 3 sentences", sub: "Count them!" }
    ],
    twists: [
      { id: "a2-w-use-unfortunately", text: "Use \"unfortunately\"", sub: "Say it at least once." },
      { id: "a2-w-include-a-number", text: "Include a number", sub: "Any number." },
      { id: "a2-w-use-a-conditional", text: "Use a conditional", sub: "\"If ..., I would ...\"" },
      { id: "a2-w-ask-the-class-a-question", text: "Ask the class a question", sub: "Wait for one answer." },
      { id: "a2-w-use-however", text: "Use \"however\"", sub: "Say it at least once." },
      { id: "a2-w-mention-a-colour", text: "Mention a colour", sub: "Any colour." },
      { id: "a2-w-include-a-time-or-a-date", text: "Include a time or a date", sub: "\"At 7 o'clock...\"" },
      { id: "a2-w-past-tense-only", text: "Past tense only", sub: "Everything happened yesterday." },
      { id: "a2-w-mention-a-famous-person", text: "Mention a famous person", sub: "Anyone famous." },
      { id: "a2-w-use-three-adjectives", text: "Use three adjectives", sub: "Count them!" },
      { id: "a2-w-end-with-a-surprise", text: "End with a surprise", sub: "Something nobody expects." },
      { id: "a2-w-use-never", text: "Use \"never\"", sub: "Say it at least once." },
      { id: "a2-w-compare-two-things", text: "Compare two things", sub: "\"... is better than ...\"" },
      { id: "a2-w-include-a-feeling", text: "Include a feeling", sub: "\"I felt...\"" },
      { id: "a2-w-use-because-twice", text: "Use \"because\" twice", sub: "Give two reasons." }
    ]
  },
  /* ---------- 2. Pre-Intermediate (A2+) ---------- */
  {
    topics: [
      { id: "a2p-t-a-time-i-was-late", text: "A time I was late" },
      { id: "a2p-t-something-i-have-never-done", text: "Something I have never done" },
      { id: "a2p-t-the-best-present-i-have-received", text: "The best present I have received" },
      { id: "a2p-t-a-place-i-have-visited", text: "A place I have visited" },
      { id: "a2p-t-something-that-made-me-laugh", text: "Something that made me laugh" },
      { id: "a2p-t-my-plans-for-next-year", text: "My plans for next year" },
      { id: "a2p-t-if-i-had-a-free-day", text: "If I had a free day" },
      { id: "a2p-t-a-difficult-day", text: "A difficult day" },
      { id: "a2p-t-a-skill-i-want-to-learn", text: "A skill I want to learn" },
      { id: "a2p-t-an-interesting-person-i-know", text: "An interesting person I know" },
      { id: "a2p-t-a-mistake-i-made", text: "A mistake I made" },
      { id: "a2p-t-my-favourite-app", text: "My favourite app" },
      { id: "a2p-t-the-best-meal-ive-had", text: "The best meal I've had" },
      { id: "a2p-t-a-festival-in-my-country", text: "A festival in my country" },
      { id: "a2p-t-a-job-i-would-like", text: "A job I would like" },
      { id: "a2p-t-something-im-good-at", text: "Something I'm good at" },
      { id: "a2p-t-healthy-habits", text: "Healthy habits" },
      { id: "a2p-t-a-film-everyone-should-see", text: "A film everyone should see" },
      { id: "a2p-t-a-trip-i-want-to-take", text: "A trip I want to take" },
      { id: "a2p-t-my-first-memory", text: "My first memory" },
      { id: "a2p-t-social-media", text: "Social media" },
      { id: "a2p-t-money", text: "Money" },
      { id: "a2p-t-pets", text: "Pets" },
      { id: "a2p-t-city-or-countryside", text: "City or countryside?" },
      { id: "a2p-t-a-rule-at-home", text: "A rule at home" },
      { id: "a2p-t-a-hobby-i-started", text: "A hobby I started" },
      { id: "a2p-t-something-i-lost", text: "Something I lost" },
      { id: "a2p-t-things-that-make-me-happy", text: "Things that make me happy" },
      { id: "a2p-t-a-game-i-loved-as-a", text: "A game I loved as a child" },
      { id: "a2p-t-my-dream-house", text: "My dream house" },
      { id: "a2p-t-fast-food", text: "Fast food" },
      { id: "a2p-t-learning-english", text: "Learning English" },
      { id: "a2p-t-a-famous-place-in-my-city", text: "A famous place in my city" },
      { id: "a2p-t-a-sport-id-like-to-try", text: "A sport I'd like to try" },
      { id: "a2p-t-music-when-i-study", text: "Music when I study" },
      { id: "a2p-t-the-weather-this-week", text: "The weather this week" },
      { id: "a2p-t-shopping-online", text: "Shopping online" },
      { id: "a2p-t-a-funny-story", text: "A funny story" },
      { id: "a2p-t-my-favourite-shop", text: "My favourite shop" },
      { id: "a2p-t-a-good-weekend", text: "A good weekend" }
    ],
    first: [
      { id: "a2p-f-places-i-have-visited", text: "Places I have visited" },
      { id: "a2p-f-things-i-have-never-tried", text: "Things I have never tried" },
      { id: "a2p-f-things-that-make-me-happy", text: "Things that make me happy" },
      { id: "a2p-f-my-favourite-films", text: "My favourite films" },
      { id: "a2p-f-things-im-good-at", text: "Things I'm good at" },
      { id: "a2p-f-something-i-want-to-learn", text: "Something I want to learn" },
      { id: "a2p-f-my-hometown", text: "My hometown" },
      { id: "a2p-f-my-plans-for-the-weekend", text: "My plans for the weekend" },
      { id: "a2p-f-my-hobbies", text: "My hobbies" },
      { id: "a2p-f-my-family", text: "My family" },
      { id: "a2p-f-my-dream-holiday", text: "My dream holiday" },
      { id: "a2p-f-why-im-here-today", text: "Why I'm here today" }
    ],
    styles: [
      { id: "a2p-s-normal", text: "Normal", sub: "Just talk normally." },
      { id: "a2p-s-very-slowly", text: "Very slowly", sub: "Every... word... slowly." },
      { id: "a2p-s-very-fast", text: "Very fast", sub: "As fast as you can." },
      { id: "a2p-s-whispering", text: "Whispering", sub: "Everyone must listen!" },
      { id: "a2p-s-telling-a-secret", text: "Telling a secret", sub: "Quietly, as if it is a big secret." },
      { id: "a2p-s-news-reporter", text: "News reporter", sub: "Good evening. Breaking news..." },
      { id: "a2p-s-tour-guide", text: "Tour guide", sub: "On your left, you can see..." },
      { id: "a2p-s-question-at-the-end", text: "Question at the end", sub: "Finish with a question for the class." },
      { id: "a2p-s-sports-commentator", text: "Sports commentator", sub: "And here we go...!" },
      { id: "a2p-s-very-happy-voice", text: "Very happy voice", sub: "Everything is wonderful!" },
      { id: "a2p-s-very-sad-voice", text: "Very sad voice", sub: "Oh no..." },
      { id: "a2p-s-very-surprised", text: "Very surprised", sub: "Really?! Wow!" },
      { id: "a2p-s-very-bored", text: "Very bored", sub: "Soooo boring..." },
      { id: "a2p-s-like-a-teacher", text: "Like a teacher", sub: "OK class, listen..." },
      { id: "a2p-s-weather-forecaster", text: "Weather forecaster", sub: "Today it will be..." },
      { id: "a2p-s-radio-dj", text: "Radio DJ", sub: "You're listening to..." },
      { id: "a2p-s-like-an-advert", text: "Like an advert", sub: "Buy it now!" },
      { id: "a2p-s-very-politely", text: "Very politely", sub: "If I may say..." },
      { id: "a2p-s-storyteller", text: "Storyteller", sub: "Once upon a time..." },
      { id: "a2p-s-exactly-3-sentences", text: "Exactly 3 sentences", sub: "Count them!" }
    ],
    twists: [
      { id: "a2p-w-use-unfortunately", text: "Use \"unfortunately\"", sub: "Say it at least once." },
      { id: "a2p-w-include-a-number", text: "Include a number", sub: "Any number." },
      { id: "a2p-w-use-a-conditional", text: "Use a conditional", sub: "\"If ..., I would ...\"" },
      { id: "a2p-w-ask-the-class-a-question", text: "Ask the class a question", sub: "Wait for one answer." },
      { id: "a2p-w-use-however", text: "Use \"however\"", sub: "Say it at least once." },
      { id: "a2p-w-mention-a-colour", text: "Mention a colour", sub: "Any colour." },
      { id: "a2p-w-include-a-time-or-a-date", text: "Include a time or a date", sub: "\"At 7 o'clock...\"" },
      { id: "a2p-w-past-tense-only", text: "Past tense only", sub: "Everything happened yesterday." },
      { id: "a2p-w-mention-a-famous-person", text: "Mention a famous person", sub: "Anyone famous." },
      { id: "a2p-w-use-three-adjectives", text: "Use three adjectives", sub: "Count them!" },
      { id: "a2p-w-end-with-a-surprise", text: "End with a surprise", sub: "Something nobody expects." },
      { id: "a2p-w-use-never", text: "Use \"never\"", sub: "Say it at least once." },
      { id: "a2p-w-compare-two-things", text: "Compare two things", sub: "\"... is better than ...\"" },
      { id: "a2p-w-include-a-feeling", text: "Include a feeling", sub: "\"I felt...\"" },
      { id: "a2p-w-use-because-twice", text: "Use \"because\" twice", sub: "Give two reasons." }
    ]
  },
  /* ---------- 3. Intermediate (B1) ---------- */
  {
    topics: [
      { id: "b1-t-if-i-could-live-anywhere", text: "If I could live anywhere" },
      { id: "b1-t-something-i-used-to-do-as", text: "Something I used to do as a child" },
      { id: "b1-t-advice-for-a-new-student", text: "Advice for a new student" },
      { id: "b1-t-the-best-decision-ive-made", text: "The best decision I've made" },
      { id: "b1-t-how-technology-has-changed-my-life", text: "How technology has changed my life" },
      { id: "b1-t-a-person-who-inspires-me", text: "A person who inspires me" },
      { id: "b1-t-what-id-do-with-a-million", text: "What I'd do with a million dollars" },
      { id: "b1-t-a-problem-in-my-city", text: "A problem in my city" },
      { id: "b1-t-an-unforgettable-trip", text: "An unforgettable trip" },
      { id: "b1-t-my-ideal-job", text: "My ideal job" },
      { id: "b1-t-a-rule-id-change-at-school", text: "A rule I'd change at school" },
      { id: "b1-t-why-im-learning-english", text: "Why I'm learning English" },
      { id: "b1-t-the-best-way-to-relax", text: "The best way to relax" },
      { id: "b1-t-a-tradition-in-my-family", text: "A tradition in my family" },
      { id: "b1-t-living-alone-or-with-family", text: "Living alone or with family?" },
      { id: "b1-t-a-film-that-changed-my-mind", text: "A film that changed my mind" },
      { id: "b1-t-something-id-like-to-invent", text: "Something I'd like to invent" },
      { id: "b1-t-how-to-make-friends", text: "How to make friends" },
      { id: "b1-t-phones-at-school", text: "Phones at school" },
      { id: "b1-t-my-perfect-weekend", text: "My perfect weekend" },
      { id: "b1-t-a-place-id-never-go-back", text: "A place I'd never go back to" },
      { id: "b1-t-the-future-of-transport", text: "The future of transport" },
      { id: "b1-t-healthy-eating", text: "Healthy eating" },
      { id: "b1-t-a-goal-for-this-year", text: "A goal for this year" },
      { id: "b1-t-good-and-bad-habits", text: "Good and bad habits" },
      { id: "b1-t-the-best-age-to-be", text: "The best age to be" },
      { id: "b1-t-would-you-like-to-be-famous", text: "Would you like to be famous?" },
      { id: "b1-t-working-from-home", text: "Working from home" },
      { id: "b1-t-a-skill-everyone-should-learn", text: "A skill everyone should learn" },
      { id: "b1-t-something-im-proud-of", text: "Something I'm proud of" },
      { id: "b1-t-tourism-in-my-country", text: "Tourism in my country" },
      { id: "b1-t-an-embarrassing-moment", text: "An embarrassing moment" },
      { id: "b1-t-if-i-had-a-superpower", text: "If I had a superpower" },
      { id: "b1-t-online-friendships", text: "Online friendships" },
      { id: "b1-t-a-risk-i-took", text: "A risk I took" },
      { id: "b1-t-weather-and-mood", text: "Weather and mood" },
      { id: "b1-t-fast-fashion", text: "Fast fashion" },
      { id: "b1-t-a-great-teacher", text: "A great teacher" },
      { id: "b1-t-taking-a-gap-year", text: "Taking a gap year" },
      { id: "b1-t-life-in-2050", text: "Life in 2050" }
    ],
    first: [
      { id: "b1-f-things-i-used-to-love-as", text: "Things I used to love as a child" },
      { id: "b1-f-something-id-change-about-my-city", text: "Something I'd change about my city" },
      { id: "b1-f-why-im-learning-english", text: "Why I'm learning English" },
      { id: "b1-f-my-hidden-talent", text: "My hidden talent" },
      { id: "b1-f-my-dream-job", text: "My dream job" },
      { id: "b1-f-what-id-do-with-a-free", text: "What I'd do with a free day" },
      { id: "b1-f-the-best-advice-ive-had", text: "The best advice I've had" },
      { id: "b1-f-what-makes-a-good-class", text: "What makes a good class" },
      { id: "b1-f-a-place-id-love-to-visit", text: "A place I'd love to visit" },
      { id: "b1-f-something-people-dont-know-about-me", text: "Something people don't know about me" },
      { id: "b1-f-my-favourite-way-to-relax", text: "My favourite way to relax" },
      { id: "b1-f-a-goal-for-this-year", text: "A goal for this year" }
    ],
    styles: [
      { id: "b1-s-normal", text: "Normal", sub: "Just talk normally." },
      { id: "b1-s-very-slowly", text: "Very slowly", sub: "Every... word... slowly." },
      { id: "b1-s-very-fast", text: "Very fast", sub: "As fast as you can." },
      { id: "b1-s-whispering", text: "Whispering", sub: "Everyone must listen!" },
      { id: "b1-s-telling-a-secret", text: "Telling a secret", sub: "Quietly, as if it is a big secret." },
      { id: "b1-s-news-reporter", text: "News reporter", sub: "Good evening. Breaking news..." },
      { id: "b1-s-tour-guide", text: "Tour guide", sub: "On your left, you can see..." },
      { id: "b1-s-question-at-the-end", text: "Question at the end", sub: "Finish with a question for the class." },
      { id: "b1-s-sports-commentator", text: "Sports commentator", sub: "And here we go...!" },
      { id: "b1-s-very-happy-voice", text: "Very happy voice", sub: "Everything is wonderful!" },
      { id: "b1-s-very-sad-voice", text: "Very sad voice", sub: "Oh no..." },
      { id: "b1-s-very-surprised", text: "Very surprised", sub: "Really?! Wow!" },
      { id: "b1-s-very-bored", text: "Very bored", sub: "Soooo boring..." },
      { id: "b1-s-like-a-teacher", text: "Like a teacher", sub: "OK class, listen..." },
      { id: "b1-s-weather-forecaster", text: "Weather forecaster", sub: "Today it will be..." },
      { id: "b1-s-radio-dj", text: "Radio DJ", sub: "You're listening to..." },
      { id: "b1-s-like-an-advert", text: "Like an advert", sub: "Buy it now!" },
      { id: "b1-s-very-politely", text: "Very politely", sub: "If I may say..." },
      { id: "b1-s-storyteller", text: "Storyteller", sub: "Once upon a time..." },
      { id: "b1-s-exactly-3-sentences", text: "Exactly 3 sentences", sub: "Count them!" }
    ],
    twists: [
      { id: "b1-w-use-unfortunately", text: "Use \"unfortunately\"", sub: "Say it at least once." },
      { id: "b1-w-include-a-number", text: "Include a number", sub: "Any number." },
      { id: "b1-w-use-a-conditional", text: "Use a conditional", sub: "\"If ..., I would ...\"" },
      { id: "b1-w-ask-the-class-a-question", text: "Ask the class a question", sub: "Wait for one answer." },
      { id: "b1-w-use-however", text: "Use \"however\"", sub: "Say it at least once." },
      { id: "b1-w-mention-a-colour", text: "Mention a colour", sub: "Any colour." },
      { id: "b1-w-include-a-time-or-a-date", text: "Include a time or a date", sub: "\"At 7 o'clock...\"" },
      { id: "b1-w-past-tense-only", text: "Past tense only", sub: "Everything happened yesterday." },
      { id: "b1-w-mention-a-famous-person", text: "Mention a famous person", sub: "Anyone famous." },
      { id: "b1-w-use-three-adjectives", text: "Use three adjectives", sub: "Count them!" },
      { id: "b1-w-end-with-a-surprise", text: "End with a surprise", sub: "Something nobody expects." },
      { id: "b1-w-use-never", text: "Use \"never\"", sub: "Say it at least once." },
      { id: "b1-w-compare-two-things", text: "Compare two things", sub: "\"... is better than ...\"" },
      { id: "b1-w-include-a-feeling", text: "Include a feeling", sub: "\"I felt...\"" },
      { id: "b1-w-use-because-twice", text: "Use \"because\" twice", sub: "Give two reasons." }
    ]
  },
  /* ---------- 4. IELTS 1 (B2) ---------- */
  {
    topics: [
      { id: "i1-t-is-social-media-good-for-us", text: "Is social media good for us?" },
      { id: "i1-t-the-value-of-failure", text: "The value of failure" },
      { id: "i1-t-should-homework-be-banned", text: "Should homework be banned?" },
      { id: "i1-t-what-makes-a-good-leader", text: "What makes a good leader" },
      { id: "i1-t-working-abroad", text: "Working abroad" },
      { id: "i1-t-the-best-way-to-learn-a", text: "The best way to learn a language" },
      { id: "i1-t-remote-work", text: "Remote work" },
      { id: "i1-t-celebrities-as-role-models", text: "Celebrities as role models" },
      { id: "i1-t-is-university-necessary", text: "Is university necessary?" },
      { id: "i1-t-protecting-the-environment", text: "Protecting the environment" },
      { id: "i1-t-city-life-or-country-life", text: "City life or country life?" },
      { id: "i1-t-the-role-of-luck-in-success", text: "The role of luck in success" },
      { id: "i1-t-should-school-start-later", text: "Should school start later?" },
      { id: "i1-t-advertising-and-children", text: "Advertising and children" },
      { id: "i1-t-money-and-happiness", text: "Money and happiness" },
      { id: "i1-t-online-or-face-to-face-learning", text: "Online or face-to-face learning?" },
      { id: "i1-t-traditions-in-the-modern-world", text: "Traditions in the modern world" },
      { id: "i1-t-reality-tv", text: "Reality TV" },
      { id: "i1-t-should-zoos-exist", text: "Should zoos exist?" },
      { id: "i1-t-tourism-good-or-bad", text: "Tourism: good or bad?" },
      { id: "i1-t-why-people-change-careers", text: "Why people change careers" },
      { id: "i1-t-renting-or-buying-a-home", text: "Renting or buying a home" },
      { id: "i1-t-sport-and-national-pride", text: "Sport and national pride" },
      { id: "i1-t-should-voting-be-compulsory", text: "Should voting be compulsory?" },
      { id: "i1-t-the-four-day-week", text: "The four-day week" },
      { id: "i1-t-banning-plastic-bags", text: "Banning plastic bags" },
      { id: "i1-t-video-games-and-learning", text: "Video games and learning" },
      { id: "i1-t-is-privacy-dead", text: "Is privacy dead?" },
      { id: "i1-t-friendship-in-the-digital-age", text: "Friendship in the digital age" },
      { id: "i1-t-an-ageing-population", text: "An ageing population" },
      { id: "i1-t-free-public-transport", text: "Free public transport" },
      { id: "i1-t-is-space-exploration-worth-it", text: "Is space exploration worth it?" },
      { id: "i1-t-ai-in-schools", text: "AI in schools" },
      { id: "i1-t-the-generation-gap", text: "The generation gap" },
      { id: "i1-t-healthy-lifestyle-myths", text: "Healthy lifestyle myths" },
      { id: "i1-t-school-uniforms", text: "School uniforms" },
      { id: "i1-t-street-food-culture", text: "Street food culture" },
      { id: "i1-t-the-power-of-music", text: "The power of music" },
      { id: "i1-t-should-news-be-free", text: "Should news be free?" },
      { id: "i1-t-living-with-parents-as-an-adult", text: "Living with parents as an adult" }
    ],
    first: [
      { id: "i1-f-what-im-passionate-about", text: "What I'm passionate about" },
      { id: "i1-f-my-goals-for-this-year", text: "My goals for this year" },
      { id: "i1-f-a-skill-i-want-to-improve", text: "A skill I want to improve" },
      { id: "i1-f-a-place-that-feels-like-home", text: "A place that feels like home" },
      { id: "i1-f-a-habit-im-proud-of", text: "A habit I'm proud of" },
      { id: "i1-f-an-achievement-im-proud-of", text: "An achievement I'm proud of" },
      { id: "i1-f-a-person-who-influenced-me", text: "A person who influenced me" },
      { id: "i1-f-what-i-expect-from-this-course", text: "What I expect from this course" },
      { id: "i1-f-how-i-like-to-learn", text: "How I like to learn" },
      { id: "i1-f-the-best-decision-ive-made", text: "The best decision I've made" },
      { id: "i1-f-a-challenge-ive-overcome", text: "A challenge I've overcome" },
      { id: "i1-f-something-id-like-to-know-about", text: "Something I'd like to know about this class" }
    ],
    styles: [
      { id: "i1-s-normal", text: "Normal", sub: "Just talk normally." },
      { id: "i1-s-very-slowly", text: "Very slowly", sub: "Every... word... slowly." },
      { id: "i1-s-very-fast", text: "Very fast", sub: "As fast as you can." },
      { id: "i1-s-whispering", text: "Whispering", sub: "Everyone must listen!" },
      { id: "i1-s-telling-a-secret", text: "Telling a secret", sub: "Quietly, as if it is a big secret." },
      { id: "i1-s-news-reporter", text: "News reporter", sub: "Good evening. Breaking news..." },
      { id: "i1-s-tour-guide", text: "Tour guide", sub: "On your left, you can see..." },
      { id: "i1-s-question-at-the-end", text: "Question at the end", sub: "Finish with a question for the class." },
      { id: "i1-s-sports-commentator", text: "Sports commentator", sub: "And here we go...!" },
      { id: "i1-s-very-happy-voice", text: "Very happy voice", sub: "Everything is wonderful!" },
      { id: "i1-s-very-sad-voice", text: "Very sad voice", sub: "Oh no..." },
      { id: "i1-s-very-surprised", text: "Very surprised", sub: "Really?! Wow!" },
      { id: "i1-s-very-bored", text: "Very bored", sub: "Soooo boring..." },
      { id: "i1-s-like-a-teacher", text: "Like a teacher", sub: "OK class, listen..." },
      { id: "i1-s-weather-forecaster", text: "Weather forecaster", sub: "Today it will be..." },
      { id: "i1-s-radio-dj", text: "Radio DJ", sub: "You're listening to..." },
      { id: "i1-s-like-an-advert", text: "Like an advert", sub: "Buy it now!" },
      { id: "i1-s-very-politely", text: "Very politely", sub: "If I may say..." },
      { id: "i1-s-storyteller", text: "Storyteller", sub: "Once upon a time..." },
      { id: "i1-s-exactly-3-sentences", text: "Exactly 3 sentences", sub: "Count them!" }
    ],
    twists: [
      { id: "i1-w-use-unfortunately", text: "Use \"unfortunately\"", sub: "Say it at least once." },
      { id: "i1-w-include-a-number", text: "Include a number", sub: "Any number." },
      { id: "i1-w-use-a-conditional", text: "Use a conditional", sub: "\"If ..., I would ...\"" },
      { id: "i1-w-ask-the-class-a-question", text: "Ask the class a question", sub: "Wait for one answer." },
      { id: "i1-w-use-however", text: "Use \"however\"", sub: "Say it at least once." },
      { id: "i1-w-mention-a-colour", text: "Mention a colour", sub: "Any colour." },
      { id: "i1-w-include-a-time-or-a-date", text: "Include a time or a date", sub: "\"At 7 o'clock...\"" },
      { id: "i1-w-past-tense-only", text: "Past tense only", sub: "Everything happened yesterday." },
      { id: "i1-w-mention-a-famous-person", text: "Mention a famous person", sub: "Anyone famous." },
      { id: "i1-w-use-three-adjectives", text: "Use three adjectives", sub: "Count them!" },
      { id: "i1-w-end-with-a-surprise", text: "End with a surprise", sub: "Something nobody expects." },
      { id: "i1-w-use-never", text: "Use \"never\"", sub: "Say it at least once." },
      { id: "i1-w-compare-two-things", text: "Compare two things", sub: "\"... is better than ...\"" },
      { id: "i1-w-include-a-feeling", text: "Include a feeling", sub: "\"I felt...\"" },
      { id: "i1-w-use-because-twice", text: "Use \"because\" twice", sub: "Give two reasons." }
    ]
  },
  /* ---------- 5. IELTS 2 (band 6.0) ---------- */
  {
    topics: [
      { id: "i2-t-describe-a-person-who-helped-you", text: "Describe a person who helped you" },
      { id: "i2-t-describe-a-place-you-would-like", text: "Describe a place you would like to visit" },
      { id: "i2-t-describe-a-book-you-enjoyed", text: "Describe a book you enjoyed" },
      { id: "i2-t-describe-a-time-you-were-very", text: "Describe a time you were very busy" },
      { id: "i2-t-describe-a-skill-you-learned", text: "Describe a skill you learned" },
      { id: "i2-t-describe-an-important-decision-you-made", text: "Describe an important decision you made" },
      { id: "i2-t-describe-a-festival-you-enjoyed", text: "Describe a festival you enjoyed" },
      { id: "i2-t-describe-a-gift-you-gave-someone", text: "Describe a gift you gave someone" },
      { id: "i2-t-describe-a-teacher-you-remember", text: "Describe a teacher you remember" },
      { id: "i2-t-describe-a-journey-that-went-wrong", text: "Describe a journey that went wrong" },
      { id: "i2-t-describe-an-app-you-use-every", text: "Describe an app you use every day" },
      { id: "i2-t-describe-a-sports-event-you-watched", text: "Describe a sports event you watched" },
      { id: "i2-t-describe-a-building-you-like", text: "Describe a building you like" },
      { id: "i2-t-describe-a-time-you-helped-someone", text: "Describe a time you helped someone" },
      { id: "i2-t-describe-a-piece-of-good-advice", text: "Describe a piece of good advice" },
      { id: "i2-t-describe-a-photo-you-like", text: "Describe a photo you like" },
      { id: "i2-t-describe-a-family-celebration", text: "Describe a family celebration" },
      { id: "i2-t-describe-a-goal-you-have", text: "Describe a goal you have" },
      { id: "i2-t-describe-a-meal-you-remember", text: "Describe a meal you remember" },
      { id: "i2-t-describe-a-film-that-moved-you", text: "Describe a film that moved you" },
      { id: "i2-t-describe-a-time-you-changed-your", text: "Describe a time you changed your mind" },
      { id: "i2-t-describe-a-website-you-use", text: "Describe a website you use" },
      { id: "i2-t-describe-a-quiet-place-you-like", text: "Describe a quiet place you like" },
      { id: "i2-t-describe-a-person-who-is-good", text: "Describe a person who is good at their job" },
      { id: "i2-t-describe-an-old-object-in-your", text: "Describe an old object in your home" },
      { id: "i2-t-describe-a-time-you-were-late", text: "Describe a time you were late" },
      { id: "i2-t-describe-a-crowded-place", text: "Describe a crowded place" },
      { id: "i2-t-describe-a-law-you-would-change", text: "Describe a law you would change" },
      { id: "i2-t-describe-a-piece-of-music-you", text: "Describe a piece of music you love" },
      { id: "i2-t-describe-a-time-you-felt-proud", text: "Describe a time you felt proud" },
      { id: "i2-t-describe-an-interesting-conversation", text: "Describe an interesting conversation" },
      { id: "i2-t-describe-a-new-rule-you-would", text: "Describe a new rule you would like" },
      { id: "i2-t-describe-a-time-you-learned-from", text: "Describe a time you learned from a mistake" },
      { id: "i2-t-describe-a-public-park", text: "Describe a public park" },
      { id: "i2-t-describe-a-toy-from-your-childhood", text: "Describe a toy from your childhood" },
      { id: "i2-t-describe-a-time-you-had-to", text: "Describe a time you had to wait" },
      { id: "i2-t-describe-a-talented-friend", text: "Describe a talented friend" },
      { id: "i2-t-describe-a-trip-by-public-transport", text: "Describe a trip by public transport" },
      { id: "i2-t-describe-an-event-you-planned", text: "Describe an event you planned" },
      { id: "i2-t-describe-a-time-you-had-to-2", text: "Describe a time you had to be patient" }
    ],
    first: [
      { id: "i2-f-describe-your-hometown", text: "Describe your hometown" },
      { id: "i2-f-describe-a-person-you-admire", text: "Describe a person you admire" },
      { id: "i2-f-describe-a-hobby-you-enjoy", text: "Describe a hobby you enjoy" },
      { id: "i2-f-describe-a-place-you-often-go", text: "Describe a place you often go" },
      { id: "i2-f-describe-a-goal-you-have", text: "Describe a goal you have" },
      { id: "i2-f-describe-your-favourite-season", text: "Describe your favourite season" },
      { id: "i2-f-describe-a-trip-you-enjoyed", text: "Describe a trip you enjoyed" },
      { id: "i2-f-describe-a-skill-you-are-proud", text: "Describe a skill you are proud of" },
      { id: "i2-f-describe-your-typical-weekend", text: "Describe your typical weekend" },
      { id: "i2-f-describe-a-book-or-film-you", text: "Describe a book or film you like" },
      { id: "i2-f-describe-a-memorable-day", text: "Describe a memorable day" },
      { id: "i2-f-describe-why-you-are-learning-english", text: "Describe why you are learning English" }
    ],
    styles: [
      { id: "i2-s-normal", text: "Normal", sub: "Just talk normally." },
      { id: "i2-s-very-slowly", text: "Very slowly", sub: "Every... word... slowly." },
      { id: "i2-s-very-fast", text: "Very fast", sub: "As fast as you can." },
      { id: "i2-s-whispering", text: "Whispering", sub: "Everyone must listen!" },
      { id: "i2-s-telling-a-secret", text: "Telling a secret", sub: "Quietly, as if it is a big secret." },
      { id: "i2-s-news-reporter", text: "News reporter", sub: "Good evening. Breaking news..." },
      { id: "i2-s-tour-guide", text: "Tour guide", sub: "On your left, you can see..." },
      { id: "i2-s-question-at-the-end", text: "Question at the end", sub: "Finish with a question for the class." },
      { id: "i2-s-sports-commentator", text: "Sports commentator", sub: "And here we go...!" },
      { id: "i2-s-very-happy-voice", text: "Very happy voice", sub: "Everything is wonderful!" },
      { id: "i2-s-very-sad-voice", text: "Very sad voice", sub: "Oh no..." },
      { id: "i2-s-very-surprised", text: "Very surprised", sub: "Really?! Wow!" },
      { id: "i2-s-very-bored", text: "Very bored", sub: "Soooo boring..." },
      { id: "i2-s-like-a-teacher", text: "Like a teacher", sub: "OK class, listen..." },
      { id: "i2-s-weather-forecaster", text: "Weather forecaster", sub: "Today it will be..." },
      { id: "i2-s-radio-dj", text: "Radio DJ", sub: "You're listening to..." },
      { id: "i2-s-like-an-advert", text: "Like an advert", sub: "Buy it now!" },
      { id: "i2-s-very-politely", text: "Very politely", sub: "If I may say..." },
      { id: "i2-s-storyteller", text: "Storyteller", sub: "Once upon a time..." },
      { id: "i2-s-exactly-3-sentences", text: "Exactly 3 sentences", sub: "Count them!" }
    ],
    twists: [
      { id: "i2-w-use-unfortunately", text: "Use \"unfortunately\"", sub: "Say it at least once." },
      { id: "i2-w-include-a-number", text: "Include a number", sub: "Any number." },
      { id: "i2-w-use-a-conditional", text: "Use a conditional", sub: "\"If ..., I would ...\"" },
      { id: "i2-w-ask-the-class-a-question", text: "Ask the class a question", sub: "Wait for one answer." },
      { id: "i2-w-use-however", text: "Use \"however\"", sub: "Say it at least once." },
      { id: "i2-w-mention-a-colour", text: "Mention a colour", sub: "Any colour." },
      { id: "i2-w-include-a-time-or-a-date", text: "Include a time or a date", sub: "\"At 7 o'clock...\"" },
      { id: "i2-w-past-tense-only", text: "Past tense only", sub: "Everything happened yesterday." },
      { id: "i2-w-mention-a-famous-person", text: "Mention a famous person", sub: "Anyone famous." },
      { id: "i2-w-use-three-adjectives", text: "Use three adjectives", sub: "Count them!" },
      { id: "i2-w-end-with-a-surprise", text: "End with a surprise", sub: "Something nobody expects." },
      { id: "i2-w-use-never", text: "Use \"never\"", sub: "Say it at least once." },
      { id: "i2-w-compare-two-things", text: "Compare two things", sub: "\"... is better than ...\"" },
      { id: "i2-w-include-a-feeling", text: "Include a feeling", sub: "\"I felt...\"" },
      { id: "i2-w-use-because-twice", text: "Use \"because\" twice", sub: "Give two reasons." }
    ]
  },
  /* ---------- 6. IELTS 3 (band 7.0+) ---------- */
  {
    topics: [
      { id: "i3-t-is-it-ethical-to-eat-meat", text: "Is it ethical to eat meat?" },
      { id: "i3-t-the-limits-of-free-speech", text: "The limits of free speech" },
      { id: "i3-t-should-art-be-publicly-funded", text: "Should art be publicly funded?" },
      { id: "i3-t-can-technology-solve-climate-change", text: "Can technology solve climate change?" },
      { id: "i3-t-meritocracy-myth-or-reality", text: "Meritocracy: myth or reality?" },
      { id: "i3-t-the-value-of-boredom", text: "The value of boredom" },
      { id: "i3-t-should-billionaires-exist", text: "Should billionaires exist?" },
      { id: "i3-t-is-globalisation-fair", text: "Is globalisation fair?" },
      { id: "i3-t-are-we-too-dependent-on-experts", text: "Are we too dependent on experts?" },
      { id: "i3-t-the-right-to-be-forgotten", text: "The right to be forgotten" },
      { id: "i3-t-should-prisons-punish-or-rehabilitate", text: "Should prisons punish or rehabilitate?" },
      { id: "i3-t-does-history-repeat-itself", text: "Does history repeat itself?" },
      { id: "i3-t-is-nationalism-dangerous", text: "Is nationalism dangerous?" },
      { id: "i3-t-the-ethics-of-ai-art", text: "The ethics of AI art" },
      { id: "i3-t-should-the-voting-age-be-16", text: "Should the voting age be 16?" },
      { id: "i3-t-is-progress-always-good", text: "Is progress always good?" },
      { id: "i3-t-universal-basic-income", text: "Universal basic income" },
      { id: "i3-t-space-colonisation", text: "Space colonisation" },
      { id: "i3-t-cancel-culture", text: "Cancel culture" },
      { id: "i3-t-the-future-of-work", text: "The future of work" },
      { id: "i3-t-editing-human-genes", text: "Editing human genes" },
      { id: "i3-t-is-tourism-killing-culture", text: "Is tourism killing culture?" },
      { id: "i3-t-should-languages-be-protected", text: "Should languages be protected?" },
      { id: "i3-t-taxing-wealth", text: "Taxing wealth" },
      { id: "i3-t-the-attention-economy", text: "The attention economy" },
      { id: "i3-t-is-patriotism-a-virtue", text: "Is patriotism a virtue?" },
      { id: "i3-t-should-cars-be-banned-from-cities", text: "Should cars be banned from cities?" },
      { id: "i3-t-animal-testing", text: "Animal testing" },
      { id: "i3-t-the-value-of-tradition", text: "The value of tradition" },
      { id: "i3-t-can-we-trust-statistics", text: "Can we trust statistics?" },
      { id: "i3-t-is-competition-healthy", text: "Is competition healthy?" },
      { id: "i3-t-surveillance-and-safety", text: "Surveillance and safety" },
      { id: "i3-t-is-a-digital-detox-necessary", text: "Is a digital detox necessary?" },
      { id: "i3-t-should-museums-return-artefacts", text: "Should museums return artefacts?" },
      { id: "i3-t-the-purpose-of-education", text: "The purpose of education" },
      { id: "i3-t-is-happiness-a-choice", text: "Is happiness a choice?" },
      { id: "i3-t-online-anonymity", text: "Online anonymity" },
      { id: "i3-t-megacities", text: "Megacities" },
      { id: "i3-t-the-ethics-of-fast-fashion", text: "The ethics of fast fashion" },
      { id: "i3-t-does-money-corrupt-sport", text: "Does money corrupt sport?" }
    ],
    first: [
      { id: "i3-f-values-i-live-by", text: "Values I live by" },
      { id: "i3-f-something-ive-changed-my-mind-about", text: "Something I've changed my mind about" },
      { id: "i3-f-a-contradiction-in-my-personality", text: "A contradiction in my personality" },
      { id: "i3-f-what-success-means-to-me", text: "What success means to me" },
      { id: "i3-f-a-risk-worth-taking", text: "A risk worth taking" },
      { id: "i3-f-a-lesson-from-failure", text: "A lesson from failure" },
      { id: "i3-f-a-question-id-ask-a-stranger", text: "A question I'd ask a stranger" },
      { id: "i3-f-what-id-tell-my-younger-self", text: "What I'd tell my younger self" },
      { id: "i3-f-an-idea-that-changed-how-i", text: "An idea that changed how I think" },
      { id: "i3-f-a-book-that-shaped-my-views", text: "A book that shaped my views" },
      { id: "i3-f-what-i-value-in-a-teacher", text: "What I value in a teacher" },
      { id: "i3-f-why-language-learning-matters-to-me", text: "Why language learning matters to me" }
    ],
    styles: [
      { id: "i3-s-normal", text: "Normal", sub: "Just talk normally." },
      { id: "i3-s-very-slowly", text: "Very slowly", sub: "Every... word... slowly." },
      { id: "i3-s-very-fast", text: "Very fast", sub: "As fast as you can." },
      { id: "i3-s-whispering", text: "Whispering", sub: "Everyone must listen!" },
      { id: "i3-s-telling-a-secret", text: "Telling a secret", sub: "Quietly, as if it is a big secret." },
      { id: "i3-s-news-reporter", text: "News reporter", sub: "Good evening. Breaking news..." },
      { id: "i3-s-tour-guide", text: "Tour guide", sub: "On your left, you can see..." },
      { id: "i3-s-question-at-the-end", text: "Question at the end", sub: "Finish with a question for the class." },
      { id: "i3-s-sports-commentator", text: "Sports commentator", sub: "And here we go...!" },
      { id: "i3-s-very-happy-voice", text: "Very happy voice", sub: "Everything is wonderful!" },
      { id: "i3-s-very-sad-voice", text: "Very sad voice", sub: "Oh no..." },
      { id: "i3-s-very-surprised", text: "Very surprised", sub: "Really?! Wow!" },
      { id: "i3-s-very-bored", text: "Very bored", sub: "Soooo boring..." },
      { id: "i3-s-like-a-teacher", text: "Like a teacher", sub: "OK class, listen..." },
      { id: "i3-s-weather-forecaster", text: "Weather forecaster", sub: "Today it will be..." },
      { id: "i3-s-radio-dj", text: "Radio DJ", sub: "You're listening to..." },
      { id: "i3-s-like-an-advert", text: "Like an advert", sub: "Buy it now!" },
      { id: "i3-s-very-politely", text: "Very politely", sub: "If I may say..." },
      { id: "i3-s-storyteller", text: "Storyteller", sub: "Once upon a time..." },
      { id: "i3-s-exactly-3-sentences", text: "Exactly 3 sentences", sub: "Count them!" }
    ],
    twists: [
      { id: "i3-w-use-unfortunately", text: "Use \"unfortunately\"", sub: "Say it at least once." },
      { id: "i3-w-include-a-number", text: "Include a number", sub: "Any number." },
      { id: "i3-w-use-a-conditional", text: "Use a conditional", sub: "\"If ..., I would ...\"" },
      { id: "i3-w-ask-the-class-a-question", text: "Ask the class a question", sub: "Wait for one answer." },
      { id: "i3-w-use-however", text: "Use \"however\"", sub: "Say it at least once." },
      { id: "i3-w-mention-a-colour", text: "Mention a colour", sub: "Any colour." },
      { id: "i3-w-include-a-time-or-a-date", text: "Include a time or a date", sub: "\"At 7 o'clock...\"" },
      { id: "i3-w-past-tense-only", text: "Past tense only", sub: "Everything happened yesterday." },
      { id: "i3-w-mention-a-famous-person", text: "Mention a famous person", sub: "Anyone famous." },
      { id: "i3-w-use-three-adjectives", text: "Use three adjectives", sub: "Count them!" },
      { id: "i3-w-end-with-a-surprise", text: "End with a surprise", sub: "Something nobody expects." },
      { id: "i3-w-use-never", text: "Use \"never\"", sub: "Say it at least once." },
      { id: "i3-w-compare-two-things", text: "Compare two things", sub: "\"... is better than ...\"" },
      { id: "i3-w-include-a-feeling", text: "Include a feeling", sub: "\"I felt...\"" },
      { id: "i3-w-use-because-twice", text: "Use \"because\" twice", sub: "Give two reasons." }
    ]
  }
];

/* Screen text & timing for the Slot Machine, per level. Editable in Edit mode. Empty text hides a line.
   talkSecs = timer after the last reel stops. askers = students picked to ask the speaker a question. */
WU.content.slotScreen = {
  shared: {
    id: 'slot-screen',
    whoLabel: 'WHO', topicLabel: 'TOPIC', howLabel: 'HOW', twistLabel: 'TWIST',
    howOn: true, twistOn: false, talkSecs: 60, askers: 2, qMark: '?',
    frame: '', rule: 'Talk until the timer stops!', ruleShow: true,
    demo: 'TEACHER DEMO: you go first!', demoShow: false, demoWho: 'TEACHER',
    askTag: 'QUESTIONS', askLine: 'Ask {name} one question each.', askFrame: ''
  },
  levels: [
    { talkSecs: 20, frame: 'I like ___. I have ___.', rule: 'Words are OK! Pointing is OK!', demoShow: true, askers: 2, askLine: 'Ask {name}:', askFrame: 'Do you like ___?' },
    { talkSecs: 30, rule: 'Talk until the timer stops!', askFrame: 'Do you ...? / What ...?' },
    { talkSecs: 45 },
    { talkSecs: 60, twistOn: true },
    { talkSecs: 90, twistOn: true },
    { talkSecs: 100, twistOn: true, frame: 'Say what, when, who with, and why it matters.' },
    { talkSecs: 120, twistOn: true }
  ]
};
