/* Warm Up: content for SPEED SWAP. Generated with a permanent id on every item.
   questions / first (First lesson mode): { id, text, sub, pic, frame }. sub = small tag (IELTS part). frame = answer frame; none = the level frame.
   id is PERMANENT: teacher edits (Edit mode) point at it. Never change or reuse an id. */
window.WU = window.WU || {}; WU.content = WU.content || {};
WU.content.swap = [
  /* ---------- 0. Beginner (A1) ---------- */
  {
    questions: [
      { id: "a1-q-whats-your-favourite-food", text: "What's your favourite food?", pic: "pizza", frame: "My favourite food is ___." },
      { id: "a1-q-whats-your-favourite-animal", text: "What's your favourite animal?", pic: "cat", frame: "My favourite animal is ___." },
      { id: "a1-q-whats-your-favourite-colour", text: "What's your favourite colour?", pic: "c-blue", frame: "My favourite colour is ___." },
      { id: "a1-q-whats-your-favourite-drink", text: "What's your favourite drink?", pic: "juice", frame: "My favourite drink is ___." },
      { id: "a1-q-whats-your-favourite-fruit", text: "What's your favourite fruit?", pic: "apple", frame: "My favourite fruit is ___." },
      { id: "a1-q-whats-your-favourite-sport", text: "What's your favourite sport?", pic: "football", frame: "My favourite sport is ___." },
      { id: "a1-q-whats-your-favourite-toy", text: "What's your favourite toy?", pic: "teddy bear", frame: "My favourite toy is ___." },
      { id: "a1-q-whats-your-favourite-song", text: "What's your favourite song?", pic: "guitar", frame: "My favourite song is ___." },
      { id: "a1-q-whats-your-favourite-book", text: "What's your favourite book?", pic: "book", frame: "My favourite book is ___." },
      { id: "a1-q-whats-your-favourite-tv-show", text: "What's your favourite TV show?", pic: "TV", frame: "My favourite TV show is ___." },
      { id: "a1-q-whats-your-favourite-game", text: "What's your favourite game?", pic: "ball", frame: "My favourite game is ___." },
      { id: "a1-q-whats-your-favourite-season", text: "What's your favourite season?", pic: "snow", frame: "My favourite season is ___." },
      { id: "a1-q-whats-your-favourite-vegetable", text: "What's your favourite vegetable?", pic: "carrot", frame: "My favourite vegetable is ___." },
      { id: "a1-q-whats-your-favourite-ice-cream", text: "What's your favourite ice cream?", pic: "ice cream", frame: "My favourite ice cream is ___." },
      { id: "a1-q-whats-your-favourite-place", text: "What's your favourite place?", pic: "park", frame: "My favourite place is ___." },
      { id: "a1-q-whats-your-favourite-day", text: "What's your favourite day?", pic: "sun", frame: "My favourite day is ___." },
      { id: "a1-q-whats-in-your-bag", text: "What's in your bag?", pic: "bag", frame: "I have ___ in my bag." },
      { id: "a1-q-whats-on-your-desk", text: "What's on your desk?", pic: "desk", frame: "I have ___ on my desk." },
      { id: "a1-q-what-can-you-see-in-the", text: "What can you see in the classroom?", pic: "eye", frame: "I can see ___." },
      { id: "a1-q-what-do-you-have-at-home", text: "What do you have at home?", pic: "house", frame: "I have ___ at home." },
      { id: "a1-q-what-do-you-eat-for-breakfast", text: "What do you eat for breakfast?", pic: "bread", frame: "I eat ___." },
      { id: "a1-q-what-do-you-drink-in-the", text: "What do you drink in the morning?", pic: "milk", frame: "I drink ___." },
      { id: "a1-q-what-pets-do-you-like", text: "What pets do you like?", pic: "dog", frame: "I like ___." },
      { id: "a1-q-what-sports-can-you-play", text: "What sports can you play?", pic: "tennis", frame: "I can play ___." },
      { id: "a1-q-what-clothes-do-you-like", text: "What clothes do you like?", pic: "T-shirt", frame: "I like ___." },
      { id: "a1-q-what-animals-do-you-like", text: "What animals do you like?", pic: "elephant", frame: "I like ___." },
      { id: "a1-q-whats-the-weather-like-today", text: "What's the weather like today?", pic: "sun", frame: "It's ___ today." },
      { id: "a1-q-how-do-you-go-to-school", text: "How do you go to school?", pic: "bus", frame: "I go to school by ___." },
      { id: "a1-q-what-do-you-like-to-do", text: "What do you like to do at the weekend?", pic: "ball", frame: "I like ___." },
      { id: "a1-q-who-is-your-favourite-singer", text: "Who is your favourite singer?", pic: "singer", frame: "My favourite singer is ___." },
      { id: "a1-q-what-fruit-do-you-like", text: "What fruit do you like?", pic: "banana", frame: "I like ___." }
    ],
    first: [
      { id: "a1-f-whats-your-name", text: "What's your name?", pic: "face", frame: "My name is ___." },
      { id: "a1-f-how-old-are-you", text: "How old are you?", pic: "cake", frame: "I'm ___." },
      { id: "a1-f-where-are-you-from", text: "Where are you from?", pic: "city", frame: "I'm from ___." },
      { id: "a1-f-whats-your-favourite-food", text: "What's your favourite food?", pic: "pizza", frame: "My favourite food is ___." },
      { id: "a1-f-whats-your-favourite-colour", text: "What's your favourite colour?", pic: "c-red", frame: "My favourite colour is ___." },
      { id: "a1-f-whats-your-favourite-animal", text: "What's your favourite animal?", pic: "dog", frame: "My favourite animal is ___." },
      { id: "a1-f-what-sports-do-you-like", text: "What sports do you like?", pic: "football", frame: "I like ___." },
      { id: "a1-f-what-music-do-you-like", text: "What music do you like?", pic: "guitar", frame: "I like ___." },
      { id: "a1-f-do-you-have-a-pet", text: "Do you have a pet?", pic: "cat", frame: "Yes, I have a ___. / No, I don't." },
      { id: "a1-f-whats-your-favourite-drink", text: "What's your favourite drink?", pic: "juice", frame: "My favourite drink is ___." },
      { id: "a1-f-where-do-you-live", text: "Where do you live?", pic: "house", frame: "I live in ___." },
      { id: "a1-f-whats-your-favourite-season", text: "What's your favourite season?", pic: "snow", frame: "My favourite season is ___." },
      { id: "a1-f-whats-your-favourite-fruit", text: "What's your favourite fruit?", pic: "banana", frame: "My favourite fruit is ___." },
      { id: "a1-f-what-do-you-like-to-eat", text: "What do you like to eat?", pic: "sandwich", frame: "I like ___." },
      { id: "a1-f-what-can-you-play", text: "What can you play?", pic: "piano", frame: "I can play ___." }
    ]
  },
  /* ---------- 1. Elementary (A2) ---------- */
  {
    questions: [
      { id: "a2-q-what-do-you-usually-do-after", text: "What do you usually do after class?" },
      { id: "a2-q-what-did-you-do-last-weekend", text: "What did you do last weekend?" },
      { id: "a2-q-what-time-do-you-usually-get", text: "What time do you usually get up?" },
      { id: "a2-q-whats-your-favourite-meal-of-the", text: "What's your favourite meal of the day? Why?" },
      { id: "a2-q-what-do-you-usually-eat-for", text: "What do you usually eat for breakfast?" },
      { id: "a2-q-how-do-you-usually-spend-your", text: "How do you usually spend your evenings?" },
      { id: "a2-q-where-did-you-go-on-your", text: "Where did you go on your last holiday?" },
      { id: "a2-q-whats-the-best-film-you-saw", text: "What's the best film you saw this year?" },
      { id: "a2-q-what-do-you-usually-do-on", text: "What do you usually do on your birthday?" },
      { id: "a2-q-what-sports-do-you-play-or", text: "What sports do you play or watch?" },
      { id: "a2-q-whats-your-favourite-place-in-your", text: "What's your favourite place in your town?" },
      { id: "a2-q-what-did-you-have-for-dinner", text: "What did you have for dinner yesterday?" },
      { id: "a2-q-what-kind-of-music-do-you", text: "What kind of music do you listen to?" },
      { id: "a2-q-how-often-do-you-go-to", text: "How often do you go to the cinema?" },
      { id: "a2-q-what-games-did-you-play-as", text: "What games did you play as a child?" },
      { id: "a2-q-whats-your-favourite-day-of-the", text: "What's your favourite day of the week? Why?" },
      { id: "a2-q-what-do-you-do-when-it", text: "What do you do when it rains?" },
      { id: "a2-q-what-do-you-usually-do-in", text: "What do you usually do in summer?" },
      { id: "a2-q-what-was-your-favourite-toy-as", text: "What was your favourite toy as a child?" },
      { id: "a2-q-where-do-you-like-to-go", text: "Where do you like to go shopping?" },
      { id: "a2-q-whats-something-you-do-every-day", text: "What's something you do every day?" },
      { id: "a2-q-whats-the-last-photo-you-took", text: "What's the last photo you took?" },
      { id: "a2-q-whats-your-favourite-app-what-do", text: "What's your favourite app? What do you use it for?" },
      { id: "a2-q-who-is-your-favourite-singer-or", text: "Who is your favourite singer or band?" },
      { id: "a2-q-what-do-you-like-about-your", text: "What do you like about your city?" },
      { id: "a2-q-what-did-you-do-yesterday-evening", text: "What did you do yesterday evening?" },
      { id: "a2-q-how-do-you-usually-get-to", text: "How do you usually get to class?" },
      { id: "a2-q-whats-your-favourite-season-why", text: "What's your favourite season? Why?" },
      { id: "a2-q-what-food-can-you-cook", text: "What food can you cook?" },
      { id: "a2-q-what-do-you-usually-do-on-2", text: "What do you usually do on Sundays?" }
    ],
    first: [
      { id: "a2-f-where-are-you-from", text: "Where are you from?" },
      { id: "a2-f-do-you-work-or-study", text: "Do you work or study?" },
      { id: "a2-f-what-do-you-do-in-your", text: "What do you do in your free time?" },
      { id: "a2-f-whats-your-favourite-food", text: "What's your favourite food?" },
      { id: "a2-f-what-kind-of-music-do-you", text: "What kind of music do you like?" },
      { id: "a2-f-what-did-you-do-last-weekend", text: "What did you do last weekend?" },
      { id: "a2-f-whats-your-favourite-place-in-this", text: "What's your favourite place in this city?" },
      { id: "a2-f-what-sports-do-you-like", text: "What sports do you like?" },
      { id: "a2-f-where-did-you-go-on-your", text: "Where did you go on your last holiday?" },
      { id: "a2-f-whats-your-favourite-film", text: "What's your favourite film?" },
      { id: "a2-f-what-do-you-usually-do-on", text: "What do you usually do on Sundays?" },
      { id: "a2-f-how-do-you-get-here", text: "How do you get here?" },
      { id: "a2-f-what-languages-do-you-speak", text: "What languages do you speak?" },
      { id: "a2-f-why-are-you-learning-english", text: "Why are you learning English?" },
      { id: "a2-f-whats-your-favourite-day-of-the", text: "What's your favourite day of the week?" }
    ]
  },
  /* ---------- 2. Pre-Intermediate (A2+) ---------- */
  {
    questions: [
      { id: "a2p-q-whats-the-most-interesting-place-you", text: "What's the most interesting place you have ever visited?" },
      { id: "a2p-q-have-you-ever-tried-a-really", text: "Have you ever tried a really unusual food? What was it?" },
      { id: "a2p-q-whats-something-new-youve-learned-this", text: "What's something new you've learned this year?" },
      { id: "a2p-q-what-do-you-usually-do-to", text: "What do you usually do to relax?" },
      { id: "a2p-q-what-was-the-last-book-or", text: "What was the last book or series you finished?" },
      { id: "a2p-q-have-you-ever-met-someone-interesting", text: "Have you ever met someone interesting on a trip?" },
      { id: "a2p-q-whats-your-morning-routine-like", text: "What's your morning routine like?" },
      { id: "a2p-q-whats-the-best-present-you-have", text: "What's the best present you have ever received?" },
      { id: "a2p-q-whats-a-hobby-youd-like-to", text: "What's a hobby you'd like to try?" },
      { id: "a2p-q-what-was-your-favourite-subject-at", text: "What was your favourite subject at school? Why?" },
      { id: "a2p-q-whats-the-best-concert-or-show", text: "What's the best concert or show you have been to?" },
      { id: "a2p-q-how-do-you-usually-celebrate-new", text: "How do you usually celebrate New Year?" },
      { id: "a2p-q-whats-something-youre-good-at", text: "What's something you're good at?" },
      { id: "a2p-q-what-do-you-do-when-you", text: "What do you do when you can't sleep?" },
      { id: "a2p-q-have-you-ever-had-a-funny", text: "Have you ever had a funny accident?" },
      { id: "a2p-q-whats-your-favourite-way-to-travel", text: "What's your favourite way to travel?" },
      { id: "a2p-q-whats-a-skill-you-have-that", text: "What's a skill you have that others might not know about?" },
      { id: "a2p-q-how-has-your-town-changed-in", text: "How has your town changed in the last few years?" },
      { id: "a2p-q-what-do-you-like-to-cook", text: "What do you like to cook for friends?" },
      { id: "a2p-q-whats-the-most-beautiful-place-in", text: "What's the most beautiful place in your country?" },
      { id: "a2p-q-have-you-ever-lost-something-important", text: "Have you ever lost something important? What happened?" },
      { id: "a2p-q-what-app-do-you-use-the", text: "What app do you use the most?" },
      { id: "a2p-q-what-did-you-enjoy-doing-as", text: "What did you enjoy doing as a child?" },
      { id: "a2p-q-whats-your-ideal-weekend", text: "What's your ideal weekend?" },
      { id: "a2p-q-whats-the-best-advice-youve-ever", text: "What's the best advice you've ever had?" },
      { id: "a2p-q-have-you-ever-been-really-surprised", text: "Have you ever been really surprised?" },
      { id: "a2p-q-whats-a-tradition-you-enjoy", text: "What's a tradition you enjoy?" },
      { id: "a2p-q-whats-something-you-want-to-do", text: "What's something you want to do this year?" },
      { id: "a2p-q-what-makes-a-good-friend", text: "What makes a good friend?" },
      { id: "a2p-q-what-would-you-like-to-learn", text: "What would you like to learn to cook?" }
    ],
    first: [
      { id: "a2p-f-whats-something-interesting-about-your-hometown", text: "What's something interesting about your hometown?" },
      { id: "a2p-f-whats-a-hobby-you-really-enjoy", text: "What's a hobby you really enjoy?" },
      { id: "a2p-f-whats-the-best-trip-youve-had", text: "What's the best trip you've had?" },
      { id: "a2p-f-whats-your-favourite-way-to-spend", text: "What's your favourite way to spend a free evening?" },
      { id: "a2p-f-what-have-you-learned-recently", text: "What have you learned recently?" },
      { id: "a2p-f-whats-your-favourite-food-from-another", text: "What's your favourite food from another country?" },
      { id: "a2p-f-what-kind-of-films-do-you", text: "What kind of films do you enjoy?" },
      { id: "a2p-f-whats-a-place-youd-like-to", text: "What's a place you'd like to visit?" },
      { id: "a2p-f-whats-something-youre-proud-of", text: "What's something you're proud of?" },
      { id: "a2p-f-what-do-you-like-about-learning", text: "What do you like about learning English?" },
      { id: "a2p-f-whats-your-favourite-season-and-why", text: "What's your favourite season and why?" },
      { id: "a2p-f-what-music-do-you-listen-to", text: "What music do you listen to when you study?" },
      { id: "a2p-f-have-you-ever-tried-an-unusual", text: "Have you ever tried an unusual sport?" },
      { id: "a2p-f-whats-your-dream-job", text: "What's your dream job?" },
      { id: "a2p-f-whats-a-good-book-or-series", text: "What's a good book or series you'd recommend?" }
    ]
  },
  /* ---------- 3. Intermediate (B1) ---------- */
  {
    questions: [
      { id: "b1-q-if-you-could-live-anywhere-where", text: "If you could live anywhere, where would you live?" },
      { id: "b1-q-whats-the-best-decision-youve-made", text: "What's the best decision you've made?" },
      { id: "b1-q-how-do-you-usually-relax-after", text: "How do you usually relax after a busy day?" },
      { id: "b1-q-whats-a-skill-youd-like-to", text: "What's a skill you'd like to be really good at?" },
      { id: "b1-q-what-was-the-most-memorable-day", text: "What was the most memorable day of your life so far?" },
      { id: "b1-q-how-has-technology-changed-the-way", text: "How has technology changed the way you study?" },
      { id: "b1-q-whats-something-you-used-to-do", text: "What's something you used to do but don't do anymore?" },
      { id: "b1-q-would-you-prefer-to-live-in", text: "Would you prefer to live in the city or the countryside? Why?" },
      { id: "b1-q-whats-the-best-way-to-learn", text: "What's the best way to learn a language?" },
      { id: "b1-q-if-you-could-meet-anyone-famous", text: "If you could meet anyone famous, who would it be?" },
      { id: "b1-q-whats-a-film-that-everyone-should", text: "What's a film that everyone should watch?" },
      { id: "b1-q-whats-the-most-useful-app-on", text: "What's the most useful app on your phone?" },
      { id: "b1-q-describe-your-perfect-holiday", text: "Describe your perfect holiday." },
      { id: "b1-q-whats-something-that-always-makes-you", text: "What's something that always makes you laugh?" },
      { id: "b1-q-what-would-you-do-with-a", text: "What would you do with a free week?" },
      { id: "b1-q-whats-a-goal-youve-achieved-recently", text: "What's a goal you've achieved recently?" },
      { id: "b1-q-which-is-better-planning-a-trip", text: "Which is better: planning a trip or being spontaneous?" },
      { id: "b1-q-whats-a-tradition-from-your-country", text: "What's a tradition from your country you'd teach a visitor?" },
      { id: "b1-q-what-do-you-think-makes-a", text: "What do you think makes a good teacher?" },
      { id: "b1-q-have-you-ever-changed-your-opinion", text: "Have you ever changed your opinion about something?" },
      { id: "b1-q-whats-the-most-interesting-job-you", text: "What's the most interesting job you can imagine?" },
      { id: "b1-q-what-do-you-do-to-stay", text: "What do you do to stay motivated?" },
      { id: "b1-q-how-do-you-like-to-spend", text: "How do you like to spend time with friends?" },
      { id: "b1-q-whats-something-youd-like-to-invent", text: "What's something you'd like to invent?" },
      { id: "b1-q-what-would-you-change-about-your", text: "What would you change about your daily routine?" },
      { id: "b1-q-whats-the-best-thing-about-your", text: "What's the best thing about your age?" },
      { id: "b1-q-do-you-prefer-books-or-films", text: "Do you prefer books or films? Why?" },
      { id: "b1-q-whats-a-place-youd-never-go", text: "What's a place you'd never go back to?" },
      { id: "b1-q-whats-the-most-difficult-thing-about", text: "What's the most difficult thing about learning English?" },
      { id: "b1-q-if-you-had-a-superpower-what", text: "If you had a superpower, what would it be?" }
    ],
    first: [
      { id: "b1-f-whats-something-most-people-dont-know", text: "What's something most people don't know about you?" },
      { id: "b1-f-why-are-you-learning-english", text: "Why are you learning English?" },
      { id: "b1-f-whats-a-place-that-is-special", text: "What's a place that is special to you?" },
      { id: "b1-f-whats-your-favourite-way-to-spend", text: "What's your favourite way to spend a weekend?" },
      { id: "b1-f-if-you-could-travel-anywhere-next", text: "If you could travel anywhere next month, where would you go?" },
      { id: "b1-f-whats-a-skill-youre-proud-of", text: "What's a skill you're proud of?" },
      { id: "b1-f-whats-the-best-film-youve-seen", text: "What's the best film you've seen recently?" },
      { id: "b1-f-what-kind-of-music-do-you", text: "What kind of music do you like and why?" },
      { id: "b1-f-whats-your-dream-job", text: "What's your dream job?" },
      { id: "b1-f-whats-a-food-you-could-eat", text: "What's a food you could eat every day?" },
      { id: "b1-f-whats-something-youd-like-to-learn", text: "What's something you'd like to learn this year?" },
      { id: "b1-f-are-you-a-morning-person-or", text: "Are you a morning person or a night person?" },
      { id: "b1-f-whats-the-best-advice-youve-received", text: "What's the best advice you've received?" },
      { id: "b1-f-whats-your-favourite-thing-about-your", text: "What's your favourite thing about your city?" },
      { id: "b1-f-what-would-your-perfect-day-look", text: "What would your perfect day look like?" }
    ]
  },
  /* ---------- 4. IELTS 1 (B2) ---------- */
  {
    questions: [
      { id: "i1-q-do-you-work-or-are-you", text: "Do you work or are you a student?", sub: "PART 1" },
      { id: "i1-q-what-do-you-like-about-your", text: "What do you like about your hometown?", sub: "PART 1" },
      { id: "i1-q-do-you-prefer-to-spend-your", text: "Do you prefer to spend your free time indoors or outdoors?", sub: "PART 1" },
      { id: "i1-q-how-often-do-you-read-books", text: "How often do you read books?", sub: "PART 1" },
      { id: "i1-q-do-you-like-cooking", text: "Do you like cooking?", sub: "PART 1" },
      { id: "i1-q-what-kind-of-music-do-you", text: "What kind of music do you like?", sub: "PART 1" },
      { id: "i1-q-how-do-you-usually-travel-around", text: "How do you usually travel around your city?", sub: "PART 1" },
      { id: "i1-q-do-you-enjoy-shopping", text: "Do you enjoy shopping?", sub: "PART 1" },
      { id: "i1-q-do-you-prefer-mornings-or-evenings", text: "Do you prefer mornings or evenings?", sub: "PART 1" },
      { id: "i1-q-what-did-you-enjoy-doing-as", text: "What did you enjoy doing as a child?", sub: "PART 1" },
      { id: "i1-q-do-you-use-social-media-a", text: "Do you use social media a lot?", sub: "PART 1" },
      { id: "i1-q-do-you-like-rainy-days", text: "Do you like rainy days?", sub: "PART 1" },
      { id: "i1-q-how-do-you-usually-celebrate-your", text: "How do you usually celebrate your birthday?", sub: "PART 1" },
      { id: "i1-q-do-you-prefer-texting-or-calling", text: "Do you prefer texting or calling?", sub: "PART 1" },
      { id: "i1-q-what-is-your-favourite-season", text: "What is your favourite season?", sub: "PART 1" },
      { id: "i1-q-why-do-people-enjoy-travelling-to", text: "Why do people enjoy travelling to other countries?", sub: "PART 3" },
      { id: "i1-q-how-has-shopping-changed-in-recent", text: "How has shopping changed in recent years?", sub: "PART 3" },
      { id: "i1-q-should-children-learn-to-cook-at", text: "Should children learn to cook at school?", sub: "PART 3" },
      { id: "i1-q-why-do-some-people-prefer-living", text: "Why do some people prefer living in cities?", sub: "PART 3" },
      { id: "i1-q-how-can-people-be-encouraged-to", text: "How can people be encouraged to read more?", sub: "PART 3" },
      { id: "i1-q-what-are-the-advantages-of-learning", text: "What are the advantages of learning a foreign language?", sub: "PART 3" },
      { id: "i1-q-do-you-think-technology-makes-people", text: "Do you think technology makes people less social?", sub: "PART 3" },
      { id: "i1-q-why-do-people-like-to-celebrate", text: "Why do people like to celebrate special events?", sub: "PART 3" },
      { id: "i1-q-how-important-is-it-to-have", text: "How important is it to have hobbies?", sub: "PART 3" },
      { id: "i1-q-what-makes-a-good-neighbour", text: "What makes a good neighbour?", sub: "PART 3" },
      { id: "i1-q-should-public-transport-be-free", text: "Should public transport be free?", sub: "PART 3" },
      { id: "i1-q-how-do-festivals-help-a-culture", text: "How do festivals help a culture?", sub: "PART 3" },
      { id: "i1-q-what-jobs-will-be-popular-in", text: "What jobs will be popular in the future?", sub: "PART 3" },
      { id: "i1-q-is-it-better-to-work-for", text: "Is it better to work for a small or a large company?", sub: "PART 3" },
      { id: "i1-q-how-can-cities-become-greener", text: "How can cities become greener?", sub: "PART 3" }
    ],
    first: [
      { id: "i1-f-where-are-you-from", text: "Where are you from?", sub: "PART 1" },
      { id: "i1-f-do-you-work-or-study", text: "Do you work or study?", sub: "PART 1" },
      { id: "i1-f-what-do-you-enjoy-about-learning", text: "What do you enjoy about learning English?", sub: "PART 1" },
      { id: "i1-f-what-do-you-usually-do-at", text: "What do you usually do at weekends?", sub: "PART 1" },
      { id: "i1-f-what-kind-of-films-do-you", text: "What kind of films do you like?", sub: "PART 1" },
      { id: "i1-f-do-you-like-travelling", text: "Do you like travelling?", sub: "PART 1" },
      { id: "i1-f-whats-your-favourite-place-in-your", text: "What's your favourite place in your city?", sub: "PART 1" },
      { id: "i1-f-whats-a-hobby-you-enjoy", text: "What's a hobby you enjoy?", sub: "PART 1" },
      { id: "i1-f-what-kind-of-food-do-you", text: "What kind of food do you like?", sub: "PART 1" },
      { id: "i1-f-do-you-prefer-the-city-or", text: "Do you prefer the city or the countryside?", sub: "PART 1" },
      { id: "i1-f-what-music-do-you-listen-to", text: "What music do you listen to?", sub: "PART 1" },
      { id: "i1-f-what-are-you-reading-at-the", text: "What are you reading at the moment?", sub: "PART 1" },
      { id: "i1-f-what-sport-do-you-like", text: "What sport do you like?", sub: "PART 1" },
      { id: "i1-f-whats-your-dream-holiday", text: "What's your dream holiday?", sub: "PART 1" },
      { id: "i1-f-why-are-you-taking-ielts", text: "Why are you taking IELTS?", sub: "PART 1" }
    ]
  },
  /* ---------- 5. IELTS 2 (band 6.0) ---------- */
  {
    questions: [
      { id: "i2-q-do-you-like-your-job-or", text: "Do you like your job or studies? Why?", sub: "PART 1" },
      { id: "i2-q-what-do-you-usually-do-at", text: "What do you usually do at weekends?", sub: "PART 1" },
      { id: "i2-q-how-often-do-you-go-out", text: "How often do you go out with friends?", sub: "PART 1" },
      { id: "i2-q-do-you-enjoy-going-to-museums", text: "Do you enjoy going to museums?", sub: "PART 1" },
      { id: "i2-q-do-you-like-to-keep-things", text: "Do you like to keep things tidy?", sub: "PART 1" },
      { id: "i2-q-how-do-you-remember-important-things", text: "How do you remember important things?", sub: "PART 1" },
      { id: "i2-q-do-you-like-to-plan-your", text: "Do you like to plan your day?", sub: "PART 1" },
      { id: "i2-q-whats-your-favourite-type-of-weather", text: "What's your favourite type of weather?", sub: "PART 1" },
      { id: "i2-q-do-you-prefer-to-learn-alone", text: "Do you prefer to learn alone or with others?", sub: "PART 1" },
      { id: "i2-q-do-you-often-buy-things-online", text: "Do you often buy things online?", sub: "PART 1" },
      { id: "i2-q-do-you-like-watching-sports", text: "Do you like watching sports?", sub: "PART 1" },
      { id: "i2-q-how-do-you-relax-after-a", text: "How do you relax after a long day?", sub: "PART 1" },
      { id: "i2-q-do-you-like-taking-photos", text: "Do you like taking photos?", sub: "PART 1" },
      { id: "i2-q-did-you-enjoy-school", text: "Did you enjoy school?", sub: "PART 1" },
      { id: "i2-q-do-you-often-use-maps", text: "Do you often use maps?", sub: "PART 1" },
      { id: "i2-q-why-do-some-people-prefer-to", text: "Why do some people prefer to work from home?", sub: "PART 3" },
      { id: "i2-q-how-has-technology-changed-the-way", text: "How has technology changed the way friends keep in touch?", sub: "PART 3" },
      { id: "i2-q-why-are-parks-important-in-cities", text: "Why are parks important in cities?", sub: "PART 3" },
      { id: "i2-q-what-are-the-effects-of-tourism", text: "What are the effects of tourism on local communities?", sub: "PART 3" },
      { id: "i2-q-is-it-more-important-to-be", text: "Is it more important to be happy or successful at work?", sub: "PART 3" },
      { id: "i2-q-how-can-schools-prepare-students-for", text: "How can schools prepare students for the future?", sub: "PART 3" },
      { id: "i2-q-why-do-some-traditions-disappear", text: "Why do some traditions disappear?", sub: "PART 3" },
      { id: "i2-q-do-advertisements-affect-the-choices-people", text: "Do advertisements affect the choices people make?", sub: "PART 3" },
      { id: "i2-q-what-makes-a-city-a-good", text: "What makes a city a good place to live?", sub: "PART 3" },
      { id: "i2-q-is-it-better-to-have-one", text: "Is it better to have one career or several?", sub: "PART 3" },
      { id: "i2-q-how-will-transport-change-in-the", text: "How will transport change in the next 20 years?", sub: "PART 3" },
      { id: "i2-q-why-do-people-collect-things", text: "Why do people collect things?", sub: "PART 3" },
      { id: "i2-q-what-are-the-benefits-of-team", text: "What are the benefits of team sports?", sub: "PART 3" },
      { id: "i2-q-do-people-today-have-less-free", text: "Do people today have less free time than in the past?", sub: "PART 3" },
      { id: "i2-q-how-important-is-it-to-protect", text: "How important is it to protect old buildings?", sub: "PART 3" }
    ],
    first: [
      { id: "i2-f-describe-your-hometown-in-three-words", text: "Describe your hometown in three words.", sub: "PART 1" },
      { id: "i2-f-what-do-you-do-and-why", text: "What do you do, and why did you choose it?", sub: "PART 1" },
      { id: "i2-f-whats-a-hobby-youd-recommend", text: "What's a hobby you'd recommend?", sub: "PART 1" },
      { id: "i2-f-whats-the-most-interesting-place-youve", text: "What's the most interesting place you've visited?", sub: "PART 1" },
      { id: "i2-f-how-do-you-usually-spend-your", text: "How do you usually spend your evenings?", sub: "PART 1" },
      { id: "i2-f-whats-a-skill-youd-like-to", text: "What's a skill you'd like to improve?", sub: "PART 1" },
      { id: "i2-f-what-kind-of-books-or-series", text: "What kind of books or series do you enjoy?", sub: "PART 1" },
      { id: "i2-f-what-does-a-perfect-weekend-look", text: "What does a perfect weekend look like for you?", sub: "PART 1" },
      { id: "i2-f-whats-your-favourite-dish-from-your", text: "What's your favourite dish from your country?", sub: "PART 1" },
      { id: "i2-f-how-do-you-like-to-learn", text: "How do you like to learn new things?", sub: "PART 1" },
      { id: "i2-f-whats-a-goal-you-have-this", text: "What's a goal you have this year?", sub: "PART 1" },
      { id: "i2-f-which-country-would-you-like-to", text: "Which country would you like to live in?", sub: "PART 1" },
      { id: "i2-f-what-do-you-like-most-about", text: "What do you like most about your city?", sub: "PART 1" },
      { id: "i2-f-what-kind-of-music-helps-you", text: "What kind of music helps you relax?", sub: "PART 1" },
      { id: "i2-f-why-do-you-need-ielts", text: "Why do you need IELTS?", sub: "PART 1" }
    ]
  },
  /* ---------- 6. IELTS 3 (band 7.0+) ---------- */
  {
    questions: [
      { id: "i3-q-is-there-anything-youd-like-to", text: "Is there anything you'd like to change about where you live?", sub: "PART 1" },
      { id: "i3-q-how-do-you-decide-what-to", text: "How do you decide what to read?", sub: "PART 1" },
      { id: "i3-q-do-you-think-you-spend-too", text: "Do you think you spend too much time online?", sub: "PART 1" },
      { id: "i3-q-what-kind-of-place-helps-you", text: "What kind of place helps you concentrate?", sub: "PART 1" },
      { id: "i3-q-do-you-prefer-to-plan-holidays", text: "Do you prefer to plan holidays in detail?", sub: "PART 1" },
      { id: "i3-q-are-you-someone-who-enjoys-routines", text: "Are you someone who enjoys routines?", sub: "PART 1" },
      { id: "i3-q-how-has-your-taste-in-music", text: "How has your taste in music changed?", sub: "PART 1" },
      { id: "i3-q-do-you-like-learning-about-history", text: "Do you like learning about history?", sub: "PART 1" },
      { id: "i3-q-does-handwriting-still-matter-to-you", text: "Does handwriting still matter to you?", sub: "PART 1" },
      { id: "i3-q-what-do-you-do-when-you", text: "What do you do when you need to make a difficult decision?", sub: "PART 1" },
      { id: "i3-q-do-you-enjoy-long-conversations", text: "Do you enjoy long conversations?", sub: "PART 1" },
      { id: "i3-q-do-you-prefer-to-give-or", text: "Do you prefer to give or receive advice?", sub: "PART 1" },
      { id: "i3-q-are-you-good-at-keeping-in", text: "Are you good at keeping in touch with people?", sub: "PART 1" },
      { id: "i3-q-whats-a-skill-youd-like-to", text: "What's a skill you'd like to master?", sub: "PART 1" },
      { id: "i3-q-do-you-like-surprises", text: "Do you like surprises?", sub: "PART 1" },
      { id: "i3-q-to-what-extent-does-technology-shape", text: "To what extent does technology shape our identity?", sub: "PART 3" },
      { id: "i3-q-is-globalisation-making-cultures-more-similar", text: "Is globalisation making cultures more similar?", sub: "PART 3" },
      { id: "i3-q-what-role-should-art-play-in", text: "What role should art play in education?", sub: "PART 3" },
      { id: "i3-q-how-might-artificial-intelligence-change-the", text: "How might artificial intelligence change the nature of work?", sub: "PART 3" },
      { id: "i3-q-is-it-possible-to-balance-economic", text: "Is it possible to balance economic growth and environmental protection?", sub: "PART 3" },
      { id: "i3-q-why-do-some-ideas-spread-faster", text: "Why do some ideas spread faster than others?", sub: "PART 3" },
      { id: "i3-q-does-social-media-encourage-superficial-communication", text: "Does social media encourage superficial communication?", sub: "PART 3" },
      { id: "i3-q-how-should-societies-value-creative-jobs", text: "How should societies value creative jobs?", sub: "PART 3" },
      { id: "i3-q-is-competition-in-education-healthy", text: "Is competition in education healthy?", sub: "PART 3" },
      { id: "i3-q-what-responsibilities-do-tourists-have", text: "What responsibilities do tourists have?", sub: "PART 3" },
      { id: "i3-q-can-cities-ever-be-truly-sustainable", text: "Can cities ever be truly sustainable?", sub: "PART 3" },
      { id: "i3-q-is-it-more-important-to-preserve", text: "Is it more important to preserve the past or to plan for the future?", sub: "PART 3" },
      { id: "i3-q-how-does-language-influence-the-way", text: "How does language influence the way we think?", sub: "PART 3" },
      { id: "i3-q-why-do-people-sometimes-distrust-experts", text: "Why do people sometimes distrust experts?", sub: "PART 3" },
      { id: "i3-q-will-printed-books-disappear", text: "Will printed books disappear?", sub: "PART 3" }
    ],
    first: [
      { id: "i3-f-whats-something-that-shaped-who-you", text: "What's something that shaped who you are today?", sub: "PART 1" },
      { id: "i3-f-what-do-you-find-most-rewarding", text: "What do you find most rewarding about your work or studies?", sub: "PART 1" },
      { id: "i3-f-whats-an-idea-that-changed-your", text: "What's an idea that changed your thinking?", sub: "PART 1" },
      { id: "i3-f-how-would-your-friends-describe-you", text: "How would your friends describe you?", sub: "PART 1" },
      { id: "i3-f-whats-a-place-that-inspires-you", text: "What's a place that inspires you?", sub: "PART 1" },
      { id: "i3-f-what-are-you-curious-about-at", text: "What are you curious about at the moment?", sub: "PART 1" },
      { id: "i3-f-whats-a-book-youd-recommend-and", text: "What's a book you'd recommend, and why?", sub: "PART 1" },
      { id: "i3-f-whats-a-habit-youre-trying-to", text: "What's a habit you're trying to build?", sub: "PART 1" },
      { id: "i3-f-what-would-you-do-with-a", text: "What would you do with a year off?", sub: "PART 1" },
      { id: "i3-f-whats-a-tradition-you-value", text: "What's a tradition you value?", sub: "PART 1" },
      { id: "i3-f-what-kind-of-people-do-you", text: "What kind of people do you admire?", sub: "PART 1" },
      { id: "i3-f-whats-the-most-interesting-conversation-youve", text: "What's the most interesting conversation you've had recently?", sub: "PART 1" },
      { id: "i3-f-how-do-you-like-to-spend", text: "How do you like to spend a free day?", sub: "PART 1" },
      { id: "i3-f-whats-a-skill-you-taught-yourself", text: "What's a skill you taught yourself?", sub: "PART 1" },
      { id: "i3-f-what-are-your-plans-after-ielts", text: "What are your plans after IELTS?", sub: "PART 1" }
    ]
  }
];

/* Screen text & timing for Speed Swap, per level. Editable in Edit mode. {n}, {total} are filled in. */
WU.content.swapScreen = {
  shared: {
    id: 'swap-screen',
    tag: 'SPEED SWAP', round: 'Round {n} of {total}', rounds: 5, secs: 90,
    setupTag: 'SET UP', setup: 'Label students around the U: A, B, A, B...',
    frame: '', rule: 'Each partner asks one follow-up question.', ruleShow: true, ready: 'Look at your partner. Ready?',
    askA: 'A asks B', askB: 'B asks A', switchOn: true, switchA: 'SWITCH: now B asks A', switchB: 'SWITCH: now A asks B',
    chain: 'Chain: the person on the left end starts. Answer, then ask the next person. The last person asks the first.',
    noPartner: 'No partner? Join the nearest pair.',
    swap: 'SWAP!', endTag: 'FINISHED', end: 'Tell the class one thing your partner said.',
    demo: 'TEACHER DEMO: watch first!', demoShow: false
  },
  levels: [
    { secs: 60, rule: 'One word is OK! Pointing is OK!', demoShow: true, setup: 'Say your letter: A, B, A, B...', ready: 'Ready?',
      askA: 'A asks. B answers.', askB: 'B asks. A answers.', switchA: 'SWITCH! B asks.', switchB: 'SWITCH! A asks.',
      chain: 'Ask the next person!', noPartner: 'No partner? Join a pair.', end: 'Say one thing your partner said.' },
    {}, {}, {},
    { secs: 120, rule: 'Answer fully, then ask your partner "Why?"' },
    { secs: 120, rule: 'Answer fully, then ask your partner "Why?"' },
    { secs: 120, rule: 'Answer fully, then ask your partner "Why?"' }
  ]
};

/* The round cycle for a U-shaped room (nobody moves seats). Repeats until the last round.
   kind: pair | group. icon: right | left | group | none (drawn by the game). order: position in the cycle.
   id is PERMANENT: teacher edits (Edit mode) point at it. */
WU.content.swapCycle = (function () {
  var P = ['a1', 'a2', 'a2p', 'b1', 'i1', 'i2', 'i3'];
  return P.map(function (p, i) {
    var easy = i === 0;
    return [
      { id: p + '-c-right', kind: 'pair', icon: 'right', order: 1, text: easy ? 'A: talk to B on your RIGHT' : 'A: talk to the B on your RIGHT' },
      { id: p + '-c-left', kind: 'pair', icon: 'left', order: 2, text: easy ? 'A: talk to B on your LEFT' : 'A: talk to the B on your LEFT' },
      { id: p + '-c-group', kind: 'group', icon: 'group', order: 3, text: easy ? 'Make groups of 4!' : 'Groups of 4: join the pair next to you' }
    ];
  });
})();
