/* Warm Up: content for TUG OF WAR. Generated with a permanent id on every item.
   topics[level]: { id, left, leftPic, right, rightPic, motion, frame }
     Two sides (left / right words + pictures), or a debate motion (IELTS): then the sides are FOR and AGAINST.
     frame = this topic's sentence frame; none = the level frame. No politics, religion, or anything that could hurt a student.
   id is PERMANENT: teacher edits (Edit mode) point at it. Never change or reuse an id. */
window.WU = window.WU || {}; WU.content = WU.content || {};
WU.content.tug = [
  /* ---------- 0. Beginner (A1) ---------- */
  { topics: [
      { id: "a1-t-pizza-vs-burgers", left: "pizza", leftPic: "pizza", right: "burgers", rightPic: "burger" },
      { id: "a1-t-cats-vs-dogs", left: "cats", leftPic: "cat", right: "dogs", rightPic: "dog" },
      { id: "a1-t-apples-vs-bananas", left: "apples", leftPic: "apple", right: "bananas", rightPic: "banana" },
      { id: "a1-t-tea-vs-coffee", left: "tea", leftPic: "tea", right: "coffee", rightPic: "coffee" },
      { id: "a1-t-football-vs-tennis", left: "football", leftPic: "football", right: "tennis", rightPic: "tennis" },
      { id: "a1-t-cars-vs-bikes", left: "cars", leftPic: "car", right: "bikes", rightPic: "bike" },
      { id: "a1-t-juice-vs-milk", left: "juice", leftPic: "juice", right: "milk", rightPic: "milk" },
      { id: "a1-t-chocolate-vs-ice-cream", left: "chocolate", leftPic: "chocolate", right: "ice cream", rightPic: "ice cream" },
      { id: "a1-t-lions-vs-elephants", left: "lions", leftPic: "lion", right: "elephants", rightPic: "elephant" },
      { id: "a1-t-the-sun-vs-snow", left: "the sun", leftPic: "sun", right: "snow", rightPic: "snow" },
      { id: "a1-t-books-vs-tv", left: "books", leftPic: "book", right: "TV", rightPic: "TV" },
      { id: "a1-t-trains-vs-planes", left: "trains", leftPic: "train", right: "planes", rightPic: "plane" },
      { id: "a1-t-cake-vs-cookies", left: "cake", leftPic: "cake", right: "cookies", rightPic: "cookie" },
      { id: "a1-t-the-beach-vs-mountains", left: "the beach", leftPic: "beach", right: "mountains", rightPic: "mountain" },
      { id: "a1-t-the-guitar-vs-the-piano", left: "the guitar", leftPic: "guitar", right: "the piano", rightPic: "piano" },
      { id: "a1-t-fish-vs-birds", left: "fish", leftPic: "fish", right: "birds", rightPic: "bird" },
      { id: "a1-t-carrots-vs-tomatoes", left: "carrots", leftPic: "carrot", right: "tomatoes", rightPic: "tomato" },
      { id: "a1-t-buses-vs-taxis", left: "buses", leftPic: "bus", right: "taxis", rightPic: "taxi" },
      { id: "a1-t-sandwiches-vs-pizza", left: "sandwiches", leftPic: "sandwich", right: "pizza", rightPic: "pizza" },
      { id: "a1-t-rain-vs-snow", left: "rain", leftPic: "rain", right: "snow", rightPic: "snow" },
      { id: "a1-t-strawberries-vs-grapes", left: "strawberries", leftPic: "strawberry", right: "grapes", rightPic: "grapes" },
      { id: "a1-t-cheese-vs-eggs", left: "cheese", leftPic: "cheese", right: "eggs", rightPic: "egg" },
      { id: "a1-t-monkeys-vs-giraffes", left: "monkeys", leftPic: "monkey", right: "giraffes", rightPic: "giraffe" },
      { id: "a1-t-robots-vs-teddy-bears", left: "robots", leftPic: "robot", right: "teddy bears", rightPic: "teddy bear" },
      { id: "a1-t-horses-vs-cows", left: "horses", leftPic: "horse", right: "cows", rightPic: "cow" },
      { id: "a1-t-dresses-vs-t-shirts", left: "dresses", leftPic: "dress", right: "T-shirts", rightPic: "T-shirt" }
    ] },
  /* ---------- 1. Elementary (A2) ---------- */
  { topics: [
      { id: "a2-t-summer-vs-winter", left: "summer", leftPic: "sun", right: "winter", rightPic: "snow" },
      { id: "a2-t-cats-vs-dogs", left: "cats", leftPic: "cat", right: "dogs", rightPic: "dog" },
      { id: "a2-t-books-vs-films", left: "books", leftPic: "book", right: "films", rightPic: "TV" },
      { id: "a2-t-trains-vs-planes", left: "trains", leftPic: "train", right: "planes", rightPic: "plane" },
      { id: "a2-t-tea-vs-coffee", left: "tea", leftPic: "tea", right: "coffee", rightPic: "coffee" },
      { id: "a2-t-football-vs-basketball", left: "football", leftPic: "football", right: "basketball", rightPic: "basketball" },
      { id: "a2-t-the-beach-vs-the-mountains", left: "the beach", leftPic: "beach", right: "the mountains", rightPic: "mountain" },
      { id: "a2-t-mornings-vs-evenings", left: "mornings", leftPic: "sun", right: "evenings", rightPic: "moon" },
      { id: "a2-t-pizza-vs-noodles", left: "pizza", leftPic: "pizza", right: "noodles", rightPic: "noodles" },
      { id: "a2-t-bikes-vs-cars", left: "bikes", leftPic: "bike", right: "cars", rightPic: "car" },
      { id: "a2-t-phones-vs-computers", left: "phones", leftPic: "phone", right: "computers", rightPic: "computer" },
      { id: "a2-t-sweet-food-vs-salty-food", left: "sweet food", leftPic: "cake", right: "salty food", rightPic: "cheese" },
      { id: "a2-t-big-parties-vs-small-parties", left: "big parties", leftPic: "balloon", right: "small parties", rightPic: "present" },
      { id: "a2-t-rain-vs-snow", left: "rain", leftPic: "rain", right: "snow", rightPic: "snow" },
      { id: "a2-t-the-sea-vs-the-swimming-pool", left: "the sea", leftPic: "boat", right: "the swimming pool", rightPic: "swimming" },
      { id: "a2-t-breakfast-vs-dinner", left: "breakfast", leftPic: "egg", right: "dinner", rightPic: "soup" },
      { id: "a2-t-the-cinema-vs-tv-at-home", left: "the cinema", leftPic: "camera", right: "TV at home", rightPic: "TV" },
      { id: "a2-t-cooking-at-home-vs-eating-out", left: "cooking at home", leftPic: "pan", right: "eating out", rightPic: "chef" },
      { id: "a2-t-music-vs-sport", left: "music", leftPic: "guitar", right: "sport", rightPic: "ball" },
      { id: "a2-t-the-zoo-vs-the-park", left: "the zoo", leftPic: "lion", right: "the park", rightPic: "park" },
      { id: "a2-t-board-games-vs-video-games", left: "board games", leftPic: "box", right: "video games", rightPic: "computer" },
      { id: "a2-t-buses-vs-walking", left: "buses", leftPic: "bus", right: "walking", rightPic: "shoes" },
      { id: "a2-t-the-city-vs-a-farm", left: "the city", leftPic: "city", right: "a farm", rightPic: "farm" },
      { id: "a2-t-birthdays-vs-holidays", left: "birthdays", leftPic: "cake", right: "holidays", rightPic: "plane" },
      { id: "a2-t-drawing-vs-singing", left: "drawing", leftPic: "pencil", right: "singing", rightPic: "microphone" }
    ] },
  /* ---------- 2. Pre-Intermediate (A2+) ---------- */
  { topics: [
      { id: "a2p-t-living-in-the-city-vs-living", left: "living in the city", leftPic: "city", right: "living in the countryside", rightPic: "farm" },
      { id: "a2p-t-travelling-alone-vs-travelling-with-friends", left: "travelling alone", leftPic: "bag", right: "travelling with friends", rightPic: "family" },
      { id: "a2p-t-e-books-vs-paper-books", left: "e-books", leftPic: "phone", right: "paper books", rightPic: "book" },
      { id: "a2p-t-studying-in-the-morning-vs-studying", left: "studying in the morning", leftPic: "sun", right: "studying at night", rightPic: "moon" },
      { id: "a2p-t-cooking-at-home-vs-fast-food", left: "cooking at home", leftPic: "pan", right: "fast food", rightPic: "burger" },
      { id: "a2p-t-hot-countries-vs-cold-countries", left: "hot countries", leftPic: "sun", right: "cold countries", rightPic: "snow" },
      { id: "a2p-t-texting-vs-calling", left: "texting", leftPic: "phone", right: "calling", rightPic: "phone" },
      { id: "a2p-t-the-gym-vs-playing-outside", left: "the gym", leftPic: "ball", right: "playing outside", rightPic: "park" },
      { id: "a2p-t-holidays-at-home-vs-holidays-abroad", left: "holidays at home", leftPic: "house", right: "holidays abroad", rightPic: "plane" },
      { id: "a2p-t-cats-as-pets-vs-dogs-as", left: "cats as pets", leftPic: "cat", right: "dogs as pets", rightPic: "dog" },
      { id: "a2p-t-winter-sports-vs-summer-sports", left: "winter sports", leftPic: "snowman", right: "summer sports", rightPic: "swimming" },
      { id: "a2p-t-trains-vs-planes", left: "trains", leftPic: "train", right: "planes", rightPic: "plane" },
      { id: "a2p-t-watching-sport-vs-playing-sport", left: "watching sport", leftPic: "TV", right: "playing sport", rightPic: "football" },
      { id: "a2p-t-big-schools-vs-small-schools", left: "big schools", leftPic: "school", right: "small schools", rightPic: "school" },
      { id: "a2p-t-shopping-online-vs-shopping-in-shops", left: "shopping online", leftPic: "computer", right: "shopping in shops", rightPic: "shop" },
      { id: "a2p-t-series-vs-films", left: "series", leftPic: "TV", right: "films", rightPic: "camera" },
      { id: "a2p-t-learning-with-a-teacher-vs-learning", left: "learning with a teacher", leftPic: "teacher", right: "learning with an app", rightPic: "phone" },
      { id: "a2p-t-getting-up-early-vs-sleeping-late", left: "getting up early", leftPic: "clock", right: "sleeping late", rightPic: "bed" },
      { id: "a2p-t-camping-vs-hotels", left: "camping", leftPic: "fire", right: "hotels", rightPic: "house" },
      { id: "a2p-t-a-big-city-break-vs-a", left: "a big city break", leftPic: "city", right: "a quiet beach holiday", rightPic: "beach" },
      { id: "a2p-t-homemade-food-vs-restaurant-food", left: "homemade food", leftPic: "pan", right: "restaurant food", rightPic: "chef" },
      { id: "a2p-t-the-radio-vs-podcasts", left: "the radio", leftPic: "microphone", right: "podcasts", rightPic: "phone" },
      { id: "a2p-t-walking-to-school-vs-taking-the", left: "walking to school", leftPic: "shoes", right: "taking the bus", rightPic: "bus" },
      { id: "a2p-t-old-films-vs-new-films", left: "old films", leftPic: "TV", right: "new films", rightPic: "camera" },
      { id: "a2p-t-team-sports-vs-individual-sports", left: "team sports", leftPic: "football", right: "individual sports", rightPic: "tennis" }
    ] },
  /* ---------- 3. Intermediate (B1) ---------- */
  { topics: [
      { id: "b1-t-learning-online-vs-learning-in-a", left: "learning online", leftPic: "computer", right: "learning in a classroom", rightPic: "school" },
      { id: "b1-t-public-transport-vs-driving-a-car", left: "public transport", leftPic: "bus", right: "driving a car", rightPic: "car" },
      { id: "b1-t-living-alone-vs-living-with-friends", left: "living alone", leftPic: "house", right: "living with friends", rightPic: "family" },
      { id: "b1-t-working-in-a-team-vs-working", left: "working in a team", leftPic: "family", right: "working alone", rightPic: "desk" },
      { id: "b1-t-a-job-you-love-vs-a", left: "a job you love", leftPic: "heart", right: "a job with free time", rightPic: "sun" },
      { id: "b1-t-e-mails-vs-phone-calls", left: "e-mails", leftPic: "computer", right: "phone calls", rightPic: "phone" },
      { id: "b1-t-paper-maps-vs-gps-apps", left: "paper maps", leftPic: "book", right: "GPS apps", rightPic: "phone" },
      { id: "b1-t-reading-the-book-vs-watching-the", left: "reading the book", leftPic: "book", right: "watching the film", rightPic: "TV" },
      { id: "b1-t-travelling-by-train-vs-travelling-by", left: "travelling by train", leftPic: "train", right: "travelling by plane", rightPic: "plane" },
      { id: "b1-t-city-life-vs-village-life", left: "city life", leftPic: "city", right: "village life", rightPic: "farm" },
      { id: "b1-t-planning-a-holiday-vs-being-spontaneous", left: "planning a holiday", leftPic: "pencil", right: "being spontaneous", rightPic: "bag" },
      { id: "b1-t-studying-in-silence-vs-studying-with", left: "studying in silence", leftPic: "book", right: "studying with music", rightPic: "guitar" },
      { id: "b1-t-summer-holidays-vs-winter-holidays", left: "summer holidays", leftPic: "sun", right: "winter holidays", rightPic: "snow" },
      { id: "b1-t-visiting-museums-vs-relaxing-on-the", left: "visiting museums", leftPic: "camera", right: "relaxing on the beach", rightPic: "beach" },
      { id: "b1-t-cooking-dinner-vs-ordering-food", left: "cooking dinner", leftPic: "pan", right: "ordering food", rightPic: "phone" },
      { id: "b1-t-being-an-early-bird-vs-being", left: "being an early bird", leftPic: "sun", right: "being a night owl", rightPic: "owl" },
      { id: "b1-t-learning-an-instrument-vs-learning-a", left: "learning an instrument", leftPic: "piano", right: "learning a sport", rightPic: "ball" },
      { id: "b1-t-big-supermarkets-vs-small-local-shops", left: "big supermarkets", leftPic: "shop", right: "small local shops", rightPic: "shop" },
      { id: "b1-t-handwritten-notes-vs-typed-notes", left: "handwritten notes", leftPic: "pen", right: "typed notes", rightPic: "computer" },
      { id: "b1-t-a-quiet-weekend-vs-a-busy", left: "a quiet weekend", leftPic: "bed", right: "a busy weekend", rightPic: "clock" },
      { id: "b1-t-watching-sport-live-vs-watching-it", left: "watching sport live", leftPic: "football", right: "watching it on TV", rightPic: "TV" },
      { id: "b1-t-electric-bikes-vs-normal-bikes", left: "electric bikes", leftPic: "bike", right: "normal bikes", rightPic: "bike" },
      { id: "b1-t-living-near-the-sea-vs-living", left: "living near the sea", leftPic: "boat", right: "living near the mountains", rightPic: "mountain" },
      { id: "b1-t-concerts-vs-festivals", left: "concerts", leftPic: "singer", right: "festivals", rightPic: "balloon" },
      { id: "b1-t-podcasts-vs-audiobooks", left: "podcasts", leftPic: "microphone", right: "audiobooks", rightPic: "book" }
    ] },
  /* ---------- 4. IELTS 1 (B2) ---------- */
  { topics: [
      { id: "i1-t-homework-should-be-banned", motion: "Homework should be banned." },
      { id: "i1-t-zoos-should-be-closed", motion: "Zoos should be closed." },
      { id: "i1-t-everyone-should-learn-to-cook-at", motion: "Everyone should learn to cook at school." },
      { id: "i1-t-phones-should-not-be-allowed-in", motion: "Phones should not be allowed in classrooms." },
      { id: "i1-t-tourism-does-more-harm-than-good", motion: "Tourism does more harm than good to old cities." },
      { id: "i1-t-children-should-start-school-at-a", motion: "Children should start school at a later age." },
      { id: "i1-t-video-games-are-good-for-young", motion: "Video games are good for young people." },
      { id: "i1-t-city-centres-should-be-free-of", motion: "City centres should be free of cars." },
      { id: "i1-t-printed-books-will-disappear", motion: "Printed books will disappear." },
      { id: "i1-t-all-schools-should-have-uniforms", motion: "All schools should have uniforms." },
      { id: "i1-t-everyone-should-learn-a-second-language", motion: "Everyone should learn a second language." },
      { id: "i1-t-online-learning-is-as-good-as", motion: "Online learning is as good as classroom learning." },
      { id: "i1-t-professional-athletes-are-good-role-models", motion: "Professional athletes are good role models." },
      { id: "i1-t-working-from-home-is-better-than", motion: "Working from home is better than working in an office." },
      { id: "i1-t-famous-people-deserve-more-privacy", motion: "Famous people deserve more privacy." },
      { id: "i1-t-travel-is-the-best-education", motion: "Travel is the best education." },
      { id: "i1-t-museums-should-be-free-for-everyone", motion: "Museums should be free for everyone." },
      { id: "i1-t-art-is-as-important-as-science", motion: "Art is as important as science at school." },
      { id: "i1-t-plastic-bags-should-be-banned", motion: "Plastic bags should be banned." },
      { id: "i1-t-exams-are-the-best-way-to", motion: "Exams are the best way to measure learning." },
      { id: "i1-t-a-four-day-school-week-would", motion: "A four-day school week would be better." },
      { id: "i1-t-handwriting-should-still-be-taught", motion: "Handwriting should still be taught." },
      { id: "i1-t-robots-will-make-our-lives-better", motion: "Robots will make our lives better." },
      { id: "i1-t-reality-tv-should-be-taken-off", motion: "Reality TV should be taken off the air." },
      { id: "i1-t-space-exploration-is-a-waste-of", motion: "Space exploration is a waste of time." },
      { id: "i1-t-its-better-to-live-in-a", motion: "It's better to live in a city than in the countryside." }
    ] },
  /* ---------- 5. IELTS 2 (band 6.0) ---------- */
  { topics: [
      { id: "i2-t-social-media-does-more-harm-than", motion: "Social media does more harm than good." },
      { id: "i2-t-advertising-aimed-at-children-should-be", motion: "Advertising aimed at children should be banned." },
      { id: "i2-t-students-should-choose-all-their-own", motion: "Students should choose all their own subjects." },
      { id: "i2-t-gap-years-are-a-waste-of", motion: "Gap years are a waste of time." },
      { id: "i2-t-team-sports-are-more-valuable-than", motion: "Team sports are more valuable than individual sports." },
      { id: "i2-t-fast-fashion-should-be-discouraged", motion: "Fast fashion should be discouraged." },
      { id: "i2-t-every-city-should-have-free-public", motion: "Every city should have free public transport." },
      { id: "i2-t-children-should-not-have-smartphones-before", motion: "Children should not have smartphones before the age of 12." },
      { id: "i2-t-university-is-not-necessary-for-a", motion: "University is not necessary for a successful career." },
      { id: "i2-t-tourists-should-pay-extra-to-visit", motion: "Tourists should pay extra to visit historic city centres." },
      { id: "i2-t-artificial-intelligence-should-be-used-to", motion: "Artificial intelligence should be used to mark exams." },
      { id: "i2-t-traditional-festivals-are-losing-their-meaning", motion: "Traditional festivals are losing their meaning." },
      { id: "i2-t-remote-work-is-better-for-society", motion: "Remote work is better for society." },
      { id: "i2-t-schools-should-teach-life-skills-instead", motion: "Schools should teach life skills instead of more academic subjects." },
      { id: "i2-t-celebrities-should-stay-out-of-public", motion: "Celebrities should stay out of public debates." },
      { id: "i2-t-it-is-better-to-specialise-early", motion: "It is better to specialise early." },
      { id: "i2-t-cities-should-replace-roads-with-parks", motion: "Cities should replace roads with parks." },
      { id: "i2-t-news-should-be-free-for-everyone", motion: "News should be free for everyone." },
      { id: "i2-t-competition-in-schools-does-more-harm", motion: "Competition in schools does more harm than good." },
      { id: "i2-t-films-are-better-than-books-at", motion: "Films are better than books at telling stories." },
      { id: "i2-t-everyone-should-do-volunteer-work", motion: "Everyone should do volunteer work." },
      { id: "i2-t-learning-history-is-less-useful-than", motion: "Learning history is less useful than learning science." },
      { id: "i2-t-public-libraries-are-still-essential", motion: "Public libraries are still essential." },
      { id: "i2-t-smart-homes-make-people-lazy", motion: "Smart homes make people lazy." },
      { id: "i2-t-extreme-sports-should-require-a-licence", motion: "Extreme sports should require a licence." },
      { id: "i2-t-its-better-to-be-a-generalist", motion: "It's better to be a generalist than a specialist." }
    ] },
  /* ---------- 6. IELTS 3 (band 7.0+) ---------- */
  { topics: [
      { id: "i3-t-technology-has-made-us-less-patient", motion: "Technology has made us less patient." },
      { id: "i3-t-talent-matters-less-than-hard-work", motion: "Talent matters less than hard work." },
      { id: "i3-t-preserving-old-traditions-holds-societies-back", motion: "Preserving old traditions holds societies back." },
      { id: "i3-t-art-should-never-be-judged-by", motion: "Art should never be judged by its commercial success." },
      { id: "i3-t-global-tourism-is-destroying-what-it", motion: "Global tourism is destroying what it came to see." },
      { id: "i3-t-machines-will-one-day-be-more", motion: "Machines will one day be more creative than humans." },
      { id: "i3-t-experts-deserve-more-trust-than-they", motion: "Experts deserve more trust than they get." },
      { id: "i3-t-convenience-is-the-enemy-of-quality", motion: "Convenience is the enemy of quality." },
      { id: "i3-t-cities-should-be-designed-for-pedestrians", motion: "Cities should be designed for pedestrians, not cars." },
      { id: "i3-t-universal-access-to-the-internet-should", motion: "Universal access to the internet should be treated as a basic right." },
      { id: "i3-t-standardised-testing-should-be-abolished", motion: "Standardised testing should be abolished." },
      { id: "i3-t-the-attention-economy-is-harmful-to", motion: "The attention economy is harmful to creativity." },
      { id: "i3-t-museums-should-return-objects-to-their", motion: "Museums should return objects to their countries of origin." },
      { id: "i3-t-being-bilingual-changes-how-you-think", motion: "Being bilingual changes how you think." },
      { id: "i3-t-anonymity-online-does-more-harm-than", motion: "Anonymity online does more harm than good." },
      { id: "i3-t-space-tourism-is-a-waste-of", motion: "Space tourism is a waste of resources." },
      { id: "i3-t-boredom-is-essential-for-creativity", motion: "Boredom is essential for creativity." },
      { id: "i3-t-competition-brings-out-the-best-in", motion: "Competition brings out the best in people." },
      { id: "i3-t-nostalgia-prevents-progress", motion: "Nostalgia prevents progress." },
      { id: "i3-t-printed-newspapers-still-have-a-future", motion: "Printed newspapers still have a future." },
      { id: "i3-t-work-life-balance-is-more-important", motion: "Work-life balance is more important than career success." },
      { id: "i3-t-learning-from-failure-is-overrated", motion: "Learning from failure is overrated." },
      { id: "i3-t-sport-should-be-kept-separate-from", motion: "Sport should be kept separate from commercial interests." },
      { id: "i3-t-algorithms-know-us-better-than-our", motion: "Algorithms know us better than our friends do." },
      { id: "i3-t-a-good-translator-is-an-artist", motion: "A good translator is an artist." },
      { id: "i3-t-cities-will-be-better-places-to", motion: "Cities will be better places to live in 2050." }
    ] }
];

/* Screen text & rules for Tug of War, per level. Editable in Edit mode. {side} is filled in.
   strength = steps per good reason; distance = steps from the middle to a team's line. */
WU.content.tugScreen = {
  shared: {
    id: 'tug-screen',
    tag: 'TUG OF WAR', vs: 'VS', leftSide: 'LEFT SIDE', rightSide: 'RIGHT SIDE', forLabel: 'FOR', againstLabel: 'AGAINST',
    strength: 1, distance: 5, frame: '___ is better because ___.',
    rule: 'Give a NEW reason. Good reason = PULL!', ruleShow: true,
    turn: '{side}: your turn!', win: '{side} WINS!',
    demo: 'TEACHER DEMO: I pull first!', demoShow: false
  },
  levels: [
    { distance: 4, frame: 'I like ___.', rule: 'Say "I like ___!" = PULL!', demoShow: true },
    {}, {}, { distance: 6 },
    { distance: 6, frame: '', rule: "Answer the other team's last point, then add yours." },
    { distance: 6, frame: '', rule: "Answer the other team's last point, then add yours." },
    { distance: 7, frame: '', rule: "Answer the other team's last point, then add yours." }
  ]
};
